import {Miniflare} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=process.cwd();
const serverRoot=path.join(root,'dist/server');
const modules=['index.js',...(await readdir(serverRoot,{recursive:true})).filter(p=>p!=='index.js'&&/\.m?js$/.test(p))].map(p=>({type:'ESModule',path:path.join(serverRoot,p)}));
const mf=new Miniflare({modules,modulesRoot:serverRoot,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
let passed=0;
const check=(condition,label)=>{assert.ok(condition,label);passed++;console.log('PASS '+label);};
const headers=user=>user?{'oai-authenticated-user-id':'test_'+user,'oai-authenticated-user-email':user+'@example.test','oai-authenticated-user-full-name':'Test '+user,'oai-authenticated-user-full-name-encoding':'percent-encoded-utf-8'}:{};
async function api(user,body,query=''){const response=await mf.dispatchFetch('https://rstmc.test/api/social'+query,{method:body?'POST':'GET',headers:{...headers(user),...(body?{'Content-Type':'application/json',Origin:'https://rstmc.test'}:{})},body:body?JSON.stringify(body):undefined});let data;try{data=await response.json();}catch{throw new Error('Non-JSON API response '+response.status);}return {status:response.status,data};}
async function sendFile(user,body){const req=new Request('https://rstmc.test/api/upload',{method:'POST',headers:{...headers(user),Origin:'https://rstmc.test'},body});return mf.dispatchFetch(req.url,{method:'POST',headers:Object.fromEntries(req.headers),body:await req.arrayBuffer()});}
try{
 const database=await mf.getD1Database('DB');
 const migration=await readFile('drizzle/0000_calm_gideon.sql','utf8');
 for(const statement of migration.split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await database.prepare(statement).run();
 const guest=await api();check(guest.status===200&&guest.data.me===null&&guest.data.posts.length===16,'Guest can browse seeded feed');
 check((await api(null,{action:'reaction',id:'demo_coast',kind:'like',active:true})).status===401,'Anonymous mutations rejected');
 const a=await api('alice'),b=await api('bob'),c=await api('charlie');check(a.data.me.id==='test_alice'&&b.data.me.id==='test_bob','Account isolation and creation');
 check((await api('alice',{action:'reaction',id:'demo_coast',kind:'like',active:true})).status===200,'Like saved');
 await api('alice',{action:'reaction',id:'demo_coast',kind:'like',active:true});const liked=(await api('alice')).data.posts.find(p=>p.id==='demo_coast');check(liked.likes===2439&&liked.liked===1,'Repeated like is idempotent');
 check((await api('bob')).data.posts.find(p=>p.id==='demo_coast').liked===0,'Like identity isolated');
 await api('alice',{action:'reaction',id:'demo_coast',kind:'like',active:false});check((await api('alice')).data.posts.find(p=>p.id==='demo_coast').likes===2438,'Unlike persisted');
 await api('alice',{action:'reaction',id:'demo_coast',kind:'save',active:true});check((await api('alice',null,'?saved=1')).data.length===1,'Saved post query persists');
 check((await api('bob',null,'?saved=1')).data.length===0,'Saved posts remain private');
 await api('alice',{action:'follow',id:'demo_anaya',active:true});await api('alice',{action:'follow',id:'demo_anaya',active:true});check((await api('alice')).data.people.find(p=>p.id==='demo_anaya').followers===1,'Follow is idempotent and counted');
 check((await api('alice',null,'?relations=demo_anaya&kind=followers')).data[0].id==='test_alice','Follower list is backed by real relationships');
 const comment=await api('alice',{action:'comment',id:'demo_coast',body:'Test comment <script>alert(1)</script>'});check(comment.status===200,'Comment saved as text');
 await api('bob',{action:'delete_comment',id:comment.data.id});check((await api('alice',null,'?comments=demo_coast')).data.some(x=>x.id===comment.data.id),'Another user cannot delete the comment');
 await api('alice',{action:'delete_comment',id:comment.data.id});check(!(await api('alice',null,'?comments=demo_coast')).data.some(x=>x.id===comment.data.id),'Comment owner can delete');
 const form=new FormData();form.append('file',new File([await readFile('public/media/coast.jpg')],'photo.jpg',{type:'image/jpeg'}));const uploadedResponse=await sendFile('alice',form);const uploaded=await uploadedResponse.json();check(uploadedResponse.status===200&&uploaded.url?.startsWith('/api/media/'),'Photo uploaded to object storage');
 const media=await mf.dispatchFetch('https://rstmc.test'+uploaded.url);check(media.status===200&&media.headers.get('content-type')==='image/jpeg'&&(await media.arrayBuffer()).byteLength>10000,'Uploaded photo is served correctly');
 const bad=new FormData();bad.append('file',new File(['<svg onload=alert(1)>'],'bad.svg',{type:'image/jpeg'}));check((await sendFile('alice',bad)).status===400,'Disguised active-content upload rejected');
 const post=await api('alice',{action:'create_post',kind:'post',media:[uploaded.url],caption:'A test moment',location:'Test studio'});check(post.status===200,'Post creation succeeds');
 const postId=post.data.id;check((await api('alice',null,'?post='+postId)).data[0].caption==='A test moment','Direct post link retrieves persisted post');
 check((await api('bob',{action:'create_post',kind:'post',media:[uploaded.url],caption:'Stolen asset',location:''})).status===400,'Another account cannot claim an upload');
 check((await api('bob',{action:'delete_post',id:postId})).status===403,'Post ownership enforced on delete');
 const updated=await api('alice',{action:'profile',username:'alice_test',name:'Alice',bio:'Hello from the test',avatar:uploaded.url});check(updated.status===200&&(await api('alice')).data.me.username==='alice_test','Profile edits persist');
 check((await api('bob',{action:'profile',username:'alice_test',name:'Bob',bio:'',avatar:''})).status===409,'Duplicate usernames rejected');
 check((await api('alice',{action:'profile',username:'bad username!',name:'Alice',bio:'',avatar:''})).status===400,'Invalid usernames rejected');
 await api('bob',{action:'reaction',id:postId,kind:'like',active:true});check((await api('alice')).data.notifications.some(n=>n.kind==='like'&&n.actor_id==='test_bob'),'Notifications arrive for real activity');
 await api('alice',{action:'read_notifications'});check((await api('alice')).data.notifications.every(n=>n.read_at!==null),'Notification read state persists');
 check((await api('alice',{action:'message',id:'test_bob',body:'Hello Bob'})).status===200,'Direct message saved');
 check((await api('bob',null,'?messages=test_alice')).data[0].body==='Hello Bob','Recipient receives message');
 check((await api('charlie',null,'?messages=test_alice')).data.length===0,'Third party cannot read private messages');
 check((await api('bob')).data.unreadMessages===1,'Unread message count correct');
 await api('bob',{action:'read_messages',id:'test_alice'});check((await api('bob')).data.unreadMessages===0,'Reading messages clears unread count');
 check((await api('alice',{action:'message',id:'demo_anaya',body:'Hello'})).status===400,'Sample recipients do not pretend to receive messages');
 check((await api('alice',{action:'message',id:'test_alice',body:'Remember this note'})).status===200,'Private self notes work');
 const story=await api('alice',{action:'create_post',kind:'story',media:[uploaded.url],caption:'Story test',location:''});check(story.status===200,'Story upload succeeds');
 const storyData=(await api('alice',null,'?post='+story.data.id)).data[0];check(storyData.expires_at-storyData.created_at===86400000,'Story lifespan is exactly 24 hours');
 await database.prepare('UPDATE posts SET expires_at=? WHERE id=?').bind(Date.now()-1000,story.data.id).run();check((await api('alice',null,'?post='+story.data.id)).data.length===0,'Expired stories disappear from retrieval');
 const vf=new FormData();vf.append('file',new File([await readFile('public/media/flowers.mp4')],'flower.mp4',{type:'video/mp4'}));const vr=await sendFile('alice',vf);const vu=await vr.json();check(vr.status===200,'Video upload succeeds');
 check((await api('alice',{action:'create_post',kind:'reel',media:[vu.url],caption:'Reel test',location:''})).status===200,'Reel creation succeeds');
 const range=await mf.dispatchFetch('https://rstmc.test'+vu.url,{headers:{Range:'bytes=0-1023'}});check(range.status===206&&(await range.arrayBuffer()).byteLength===1024,'Video range requests support seeking');
 check((await mf.dispatchFetch('https://rstmc.test'+vu.url,{headers:{Range:'bytes=999999999-'}})).status===416,'Invalid video ranges return 416');
 check((await api('alice',{action:'create_post',kind:'reel',media:[uploaded.url],caption:'Invalid reel',location:''})).status===400,'Photo cannot be submitted as a reel');
 const cross=await mf.dispatchFetch('https://rstmc.test/api/social',{method:'POST',headers:{...headers('alice'),'Content-Type':'application/json',Origin:'https://evil.test'},body:JSON.stringify({action:'delete_post',id:postId})});check(cross.status===403,'Cross-origin mutations rejected');
 await api('alice',{action:'delete_post',id:postId});check((await api('alice',null,'?post='+postId)).data.length===0,'Post owner can remove a post');
 console.log(`\n${passed} integration checks passed.`);
}finally{await mf.dispose();}
