import { createHash } from 'node:crypto';
import type { Pool } from 'pg';

type Environment = Record<string, string | undefined>;
type VerificationEmail = { user: { email: string }; url: string };

export function brevoConfiguration(env: Environment = process.env) {
  const apiKey = env.BREVO_API_KEY?.trim();
  const senderEmail = env.BREVO_SENDER_EMAIL?.trim();
  if (!apiKey || !senderEmail || !/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(senderEmail)) {
    throw new Error('Configure BREVO_API_KEY and a verified BREVO_SENDER_EMAIL before enabling authentication.');
  }
  return { apiKey, senderEmail, senderName: env.BREVO_SENDER_NAME?.trim() || 'RSTMC' };
}

// Atomically reserve a send across serverless instances, using the existing rate-limit table.
// No raw recipient address is stored here. This app reserves at most 300 sends per UTC day.
export async function claimVerificationEmail(pool: Pick<Pool, 'query'>, email: string, now = Date.now()) {
  const key = `verification-email:${createHash('sha256').update(email.trim().toLowerCase()).digest('hex')}`;
  const dayStart = Math.floor(now / 86400000) * 86400000;
  const result = await pool.query(`
    WITH recipient AS (
      INSERT INTO "rateLimit" (id, key, count, "lastRequest") VALUES ($1, $1, 1, $2)
      ON CONFLICT (key) DO UPDATE SET "lastRequest" = EXCLUDED."lastRequest", count = 1
      WHERE "rateLimit"."lastRequest" <= $2 - 60000
      RETURNING id
    )
    INSERT INTO "rateLimit" (id, key, count, "lastRequest")
    SELECT 'verification-email:daily', 'verification-email:daily', 1, $3 WHERE EXISTS (SELECT 1 FROM recipient)
    ON CONFLICT (key) DO UPDATE SET
      count = CASE WHEN "rateLimit"."lastRequest" < $3 THEN 1 ELSE "rateLimit".count + 1 END,
      "lastRequest" = $3
    WHERE "rateLimit"."lastRequest" < $3 OR "rateLimit".count < 300
    RETURNING count
  `, [key, now, dayStart]);
  return result.rows.length > 0;
}

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

export function createVerificationEmailSender(env: Environment = process.env, fetcher: typeof fetch = fetch) {
  const { apiKey, senderEmail, senderName } = brevoConfiguration(env);
  return async ({ user, url }: VerificationEmail) => {
    // The URL is generated by Better Auth after its host and origin checks.
    const link = new URL(url);
    if (link.protocol !== 'https:' && !(link.protocol === 'http:' && ['localhost', '127.0.0.1'].includes(link.hostname))) {
      throw new Error('Invalid verification email URL.');
    }
    link.searchParams.set('callbackURL', new URL('/verify-email?verified=1', link.origin).href);
    const verificationUrl = link.href;
    const text = `Verify your email for RSTMC\n\nOpen this link to verify your email address:\n${verificationUrl}\n\nThis link expires in 15 minutes. After verification, sign in with your email and password.\n\nIf you did not request this email, you can ignore it.`;
    let response: Response;
    try {
      response = await fetcher('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: { 'api-key': apiKey, 'content-type': 'application/json', accept: 'application/json' },
        signal: AbortSignal.timeout(10000),
        body: JSON.stringify({
          sender: { name: senderName, email: senderEmail },
          to: [{ email: user.email }],
          subject: 'Verify your email for RSTMC',
          textContent: text,
          htmlContent: `<html><body style="font-family:Arial,sans-serif;color:#171717"><h1>Verify your email for RSTMC</h1><p>Confirm your email address to finish creating your account.</p><p><a href="${escapeHtml(verificationUrl)}" style="background:#e94378;color:white;padding:12px 20px;border-radius:8px;display:inline-block;text-decoration:none">Verify email</a></p><p>This link expires in 15 minutes. After verification, sign in with your email and password.</p><p>If the button does not work, copy this link into your browser:</p><p>${escapeHtml(verificationUrl)}</p><p>If you did not request this email, you can ignore it.</p></body></html>`,
          tags: ['email-verification'],
        }),
      });
    } catch {
      // Never log a request body, address, token, or provider credentials.
      throw new Error('Brevo verification email request failed.');
    }
    if (!response.ok) throw new Error(`Brevo verification email rejected (HTTP ${response.status}).`);
    const result = await response.json().catch(() => null) as { messageId?: unknown } | null;
    if (typeof result?.messageId !== 'string') throw new Error('Brevo did not acknowledge the verification email.');
  };
}
