import { db } from './server';

/**
 * Remove the autogenerated demo dataset from whichever production database
 * the deployment is actually connected to.
 *
 * This deliberately targets only profiles explicitly marked is_demo=1.
 * Verified real users and their content are untouched.
 */
export async function seed(){
  const database = db();
  await database.batch([
    database.prepare("DELETE FROM profiles WHERE is_demo=1"),
    database.prepare("INSERT INTO app_settings (key,value,updated_at,updated_by) VALUES (?,?,?,?) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value,updated_at=EXCLUDED.updated_at,updated_by=EXCLUDED.updated_by")
      .bind("maintenance.demo_cleanup","completed",Date.now(),"system"),
  ]);
}
