// Public UI copy registry. Keep existing keys stable when changing defaults.
export const LABEL_DEFAULTS = {
  "nav.reels": "Reels",
  "nav.home": "Home",
  "nav.search": "Search",
  "nav.explore": "Explore",
  "nav.messages": "Messages",
  "nav.notifications": "Notifications",
  "nav.create": "Create",
  "nav.profile": "Profile",
  "nav.saved": "Saved",
  "action.like": "Like",
  "action.share": "Share",
  "action.follow": "Follow",
  "action.following": "Following",
  "feed.forYou": "For you",
  "state.loading": "Loading",
  "auth.signIn": "Sign in",
  "auth.signUp": "Sign up",
  "access_screen.administrator_sign_in": "Administrator sign-in",
  "app.this_post_is_no_longer_available": "This post is no longer available.",
  "app.could_not_load_this_post": "Could not load this post.",
  "app.creation_is_not_available": "Creation is not available.",
  "app.post_hidden": "Post hidden",
  "app.undo": "Undo",
  "app.could_not_restore_the_post": "Could not restore the post.",
  "app.comments_are_unavailable": "Comments are unavailable.",
  "app.sign_in_required": "Sign in required",
  "app.link_copied": "Link copied.",
  "app.you_no_longer_see": "You no longer see ",
  "app.s_content_and_they_can_t_message_you": "'s content and they can't message you.",
  "app.unblocked": "Unblocked ",
  "app.main_navigation": "Main navigation",
  "app.more": "More",
  "app.dark_mode": "Dark mode",
  "app.light_mode": "Light mode",
  "app.about_rstmc": "About RSTMC",
  "app.settings_and_privacy": "Settings and privacy",
  "app.more_options": "More options",
  "app.skip_to_content": "Skip to content",
  "app.share_your_moments_on": "Share your moments on ",
  "app.this_section_is_not_available": "This section is not available",
  "app.the_site_administrator_has_removed_this_navigation_destination": "The site administrator has removed this navigation destination.",
  "app.let_s_try_that_again": "Let’s try that again",
  "app.we_couldn_t_connect_to_your_feed_please_try_again_in_a_moment": "We couldn’t connect to your feed. Please try again in a moment.",
  "app.reload_feed": "Reload feed",
  "app.share_a_moment": "Share a moment",
  "app.create_a_post_story_or_reel": "Create a post, story or reel.",
  "app.this_is_a_sample_profile_message_real_members_in_messages": "This is a sample profile. Message real members in Messages.",
  "app.you_cannot_message_this_profile_while_it_is_blocked": "You cannot message this profile while it is blocked.",
  "app.your_own_corner_of_rstmc": "Your own corner of RSTMC",
  "app.sign_in_to_create_a_profile_and_share_your_world": "Sign in to create a profile and share your world.",
  "app.your_conversations_here": "Your conversations, here",
  "app.sign_in_to_send_messages_and_save_notes_to_yourself": "Sign in to send messages and save notes to yourself.",
  "app.make_yourself_at_home": "Make yourself at home",
  "app.sign_in_to_share_your_moments_follow_people_and_join_the_conversa": "Sign in to share your moments, follow people, and join the conversation.",
  "app.delete_this_post": "Delete this post?",
  "app.the_post_its_comments_and_likes_will_be_removed": "The post, its comments, and likes will be removed.",
  "app.keep_post": "Keep post",
  "app.delete_post": "Delete post",
  "app.share_this_moment": "Share this moment",
  "app.post_link": "Post link",
  "app.select_and_copy_the_link_above": "Select and copy the link above.",
  "app.copy": "Copy",
  "app.a_moment_on_rstmc": "A moment on RSTMC",
  "app.share_to_another_app": "Share to another app",
  "app.send_in_a_message": "Send in a message",
  "app.saved_messages": "Saved messages",
  "app.sent": "Sent",
  "app.send": "Send",
  "app.share": "Share ",
  "app.s_profile": "’s profile",
  "app.profile_link": "Profile link",
  "app.on_rstmc": " on RSTMC",
  "app.spam": "Spam",
  "app.harassment_or_bullying": "Harassment or bullying",
  "app.false_information": "False information",
  "app.misleading_content": "Misleading content",
  "app.inappropriate_content": "Inappropriate content",
  "app.something_else": "Something else",
  "app.report": "Report ",
  "app.reports_are_private_a_human_will_review_what_you_send": "Reports are private. A human will review what you send.",
  "app.thank_you_your_report_has_been_recorded_and_will_be_reviewed": "Thank you. Your report has been recorded and will be reviewed.",
  "app.report_reason": "Report reason",
  "app.add_details_optional": "Add details (optional)",
  "app.cancel": "Cancel",
  "app.send_report": "Send report",
  "app.a_place_for_your_photos_stories_reels_and_conversations": "A place for your photos, stories, reels, and conversations.",
  "app.rstmc_is_an_independent_social_app_inspired_by_instagram_it_is_no": "RSTMC is an independent social app inspired by Instagram. It is not affiliated with Instagram or Meta.",
  "app.your_data": "Your data",
  "app.your_posts_comments_saved_items_follows_and_messages_are_stored_w": "Your posts, comments, saved items, follows, and messages are stored with your account. Saved posts and private conversations are only visible to you and the relevant participants. Stories expire after 24 hours.",
  "app.sample_content": "Sample content",
  "app.the_starter_profiles_captions_and_engagement_counts_are_fictional": "The starter profiles, captions, and engagement counts are fictional examples. Sample profiles do not receive messages. All features also work with your own uploaded photos and videos.",
  "app.photo_credits": "Photo credits",
  "app.sample_flower_video_mdn_public_domain_media_collection": "Sample flower video: MDN public-domain media collection.",
  "appearance.announcement": "Announcement",
  "appearance.featured_announcement": "Featured announcement",
  "appearance.site_footer": "Site footer",
  "appearance.pages": "Pages",
  "appearance.learn_more": "Learn more",
  "appearance.dismiss_announcement": "Dismiss ",
  "appearance.dismiss": "×",
  "auth_form.could_not_start_the_preview_account": "Could not start the preview account.",
  "auth_form.setting_up_preview": "Setting up preview…",
  "auth_form.please_wait_a_minute_before_requesting_another_email": "Please wait a minute before requesting another email.",
  "auth_form.unable_to_request_a_verification_email": "Unable to request a verification email.",
  "auth_form.unable_to_connect_please_try_again": "Unable to connect. Please try again.",
  "auth_form.verify_your_email": "Verify your email",
  "auth_form.check_your_inbox_and_spam_folder_if_this_address_belongs_to_an_un": "Check your inbox and spam folder. If this address belongs to an unverified account, a link will arrive shortly.",
  "auth_form.enter_your_account_email_to_request_a_new_verification_link": "Enter your account email to request a new verification link.",
  "auth_form.links_expire_after_15_minutes_once_verified_sign_in_with_your_ema": "Links expire after 15 minutes. Once verified, sign in with your email and password.",
  "auth_form.email": "Email",
  "auth_form.please_wait": "Please wait…",
  "auth_form.you_can_resend_in_one_minute": "You can resend in one minute",
  "auth_form.resend_verification_email": "Resend verification email",
  "auth_form.send_verification_email": "Send verification email",
  "auth_form.back_to_sign_in": "Back to sign in",
  "auth_form.back_to_home_and_sign_in": "Back to home and sign in",
  "auth_form.please_enter_your_account_email": "Please enter your account email.",
  "auth_form.unable_to_request_a_reset_email": "Unable to request a reset email.",
  "auth_form.reset_your_password": "Reset your password",
  "auth_form.if_that_address_has_an_account_a_reset_link_is_on_its_way_it_expi": "If that address has an account, a reset link is on its way. It expires in 15 minutes and works only once.",
  "auth_form.enter_the_email_you_signed_up_with_and_we_ll_send_a_reset_link": "Enter the email you signed up with and we’ll send a reset link.",
  "auth_form.send_reset_email": "Send reset email",
  "auth_form.reset_link_sent_check_your_inbox_and_spam_it_expires_in_15_minute": "Reset link sent. Check your inbox (and spam) — it expires in 15 minutes.",
  "auth_form.done": "Done",
  "auth_form.please_enter_your_name": "Please enter your name.",
  "auth_form.your_passwords_do_not_match": "Your passwords do not match.",
  "auth_form.too_many_attempts_please_wait_a_minute_and_try_again": "Too many attempts. Please wait a minute and try again.",
  "auth_form.unable_to_sign_in": "Unable to sign in.",
  "auth_form.create_your_account": "Create your account",
  "auth_form.sign_in_to_rstmc": "Sign in to RSTMC",
  "auth_form.use_your_email_and_password": "Use your email and password.",
  "auth_form.name": "Name",
  "auth_form.password": "Password",
  "auth_form.use_at_least_12_characters_we_ll_email_you_a_verification_link_fo": "Use at least 12 characters. We’ll email you a verification link. Forgot it? Reset links last 15 minutes.",
  "auth_form.confirm_password": "Confirm password",
  "auth_form.create_account": "Create account",
  "auth_form.already_have_an_account_sign_in": "Already have an account? Sign in",
  "auth_form.new_here_create_an_account": "New here? Create an account",
  "auth_form.forgot_your_password": "Forgot your password?",
  "auth_form.unable_to_sign_out": "Unable to sign out.",
  "auth_form.unable_to_sign_out_please_try_again": "Unable to sign out. Please try again.",
  "auth_form.signing_out": "Signing out…",
  "auth_form.sign_out": "Sign out",
  "common.just_now": "just now",
  "common.m": "m",
  "common.h": "h",
  "common.d": "d",
  "common.w": "w",
  "common.your_change_could_not_be_saved_please_try_again": "Your change could not be saved. Please try again.",
  "common.your_browser_could_not_process_this_photo": "Your browser could not process this photo.",
  "common.could_not_process_photo": "Could not process photo.",
  "common.choose_a_file_smaller_than_20_mb": "Choose a file smaller than 20 MB.",
  "common.open": "Open ",
  "common.your_profile": "your profile",
  "common.this_photo_could_not_be_loaded": "This photo could not be loaded.",
  "common.symbol": "/",
  "common.previous_photo": "Previous photo",
  "common.next_photo": "Next photo",
  "common.photo_navigation": "Photo navigation",
  "create.choose_up_to_6_photos_or_one_video": "Choose up to 6 photos, or one video.",
  "create.videos_must_be_shared_on_their_own": "Videos must be shared on their own.",
  "create.a_story_uses_a_single_photo_or_video": "A story uses a single photo or video.",
  "create.uploading": "Uploading",
  "create.sharing": "Sharing",
  "create.select_media": "Select media",
  "create.preview": "Preview",
  "create.details": "Details",
  "create.create": "Create ",
  "create.a_reel": "a reel",
  "create.a_story": "a story",
  "create.a_post": "a post",
  "create.step": "Step ",
  "create.post": "Post",
  "create.story": "Story",
  "create.reel": "Reel",
  "create.upload_photos_or_video": "Upload photos or video",
  "create.your_next_moment_starts_here": "Your next moment starts here",
  "create.choose": "Choose ",
  "create.a_video": "a video",
  "create.photos_or_a_video": "photos or a video",
  "create.to_share": " to share",
  "create.select_from_your_device": "Select from your device",
  "create.drag_drop_works_too_jpg_png_webp_gif_mp4_or_webm_up_to_20_mb": "Drag & drop works too · JPG, PNG, WebP, GIF, MP4 or WebM · Up to 20 MB",
  "create.upload": "Upload ",
  "create.remove_upload": "Remove upload ",
  "create.move_upload": "Move upload ",
  "create.add_photo": "Add photo",
  "create.photo": "Photo ",
  "create.display_style_for_photo": "Display style for photo ",
  "create.fill_frame": "Fill frame",
  "create.fit_in_frame": "Fit in frame",
  "create.describe_photo": "Describe photo ",
  "create.for_people_using_a_screen_reader": " for people using a screen reader",
  "create.alt_text_what_s_in_this_photo": "Alt text (what’s in this photo)",
  "create.replace": "Replace",
  "create.next": "Next",
  "create.write_a_caption": "Write a caption",
  "create.write_a_caption_use_hashtags_to_make_it_discoverable": "Write a caption… Use #hashtags to make it discoverable.",
  "create.2_200": "/2,200",
  "create.add_location": "Add location",
  "create.choose_a_category": "Choose a category",
  "create.your_story_will_disappear_after_24_hours_people_can_reply_to_it_i": "Your story will disappear after 24 hours. People can reply to it in Messages.",
  "create.reels_appear_in_the_reels_feed_with_their_original_frame_size": "Reels appear in the Reels feed with their original frame size.",
  "create.back": "Back",
  "create.symbol": "…",
  "create.tag_up_to_10_people": "Tag up to 10 people.",
  "create.symbol_2": "@",
  "create.tag_people": "Tag people",
  "create.remove": "Remove ",
  "create.from_tags": " from tags",
  "create.tag_suggestions": "Tag suggestions",
  "create.edit_post": "Edit post",
  "create.caption_location_category_tags_and_alt_text": "Caption, location, category, tags, and alt text.",
  "create.edit_caption": "Edit caption",
  "create.edit_location": "Edit location",
  "create.saving": "Saving…",
  "create.save_changes": "Save changes",
  "create.please_choose_a_photo": "Please choose a photo.",
  "create.edit_profile": "Edit profile",
  "create.choose_profile_photo": "Choose profile photo",
  "create.change_photo": "Change photo",
  "create.username": "Username",
  "create.bio": "Bio",
  "create.150": "/150",
  "create.website": "Website",
  "create.https": "https://",
  "create.shown_on_your_profile": "Shown on your profile",
  "floating_dock.bottom_navigation": "Bottom navigation",
  "messages.unread_messages": " unread messages",
  "messages.find_someone_to_message": "Find someone to message",
  "messages.search_people": "Search people",
  "messages.search_conversations": "Search conversations",
  "messages.in_conversations": "In conversations",
  "messages.your_conversations": "Your conversations",
  "messages.notes_links_and_little_reminders": "Notes, links, and little reminders",
  "messages.start_a_conversation": "Start a conversation",
  "messages.no_members_found": "No members found.",
  "messages.messages_are_available_between_real_members_sample_profiles_don_t": "Messages are available between real members. Sample profiles don’t receive messages.",
  "messages.back_to_conversations": "Back to conversations",
  "messages.only_you_can_see_these_messages": "Only you can see these messages",
  "messages.load_earlier_messages": "Load earlier messages",
  "messages.start_of_this_conversation": "Start of this conversation",
  "messages.sending": "Sending…",
  "messages.delete_message": "Delete message",
  "messages.delete": "Delete",
  "messages.a_little_space_for_yourself": "A little space for yourself",
  "messages.say_hello": "Say hello",
  "messages.save_a_thought_a_link_or_a_reminder_it_ll_be_here_when_you_need_i": "Save a thought, a link, or a reminder. It’ll be here when you need it.",
  "messages.start_your_conversation_with": "Start your conversation with ",
  "messages.retry": "Retry",
  "messages.add_a_smile": "Add a smile",
  "messages.write_a_message": "Write a message",
  "messages.message": "Message…",
  "messages.send_message": "Send message",
  "post_card.post_options": "Post options",
  "post_card.go_to_profile": "Go to profile",
  "post_card.copy_link": "Copy link",
  "post_card.remove_from_saved": "Remove from saved",
  "post_card.save_post": "Save post",
  "post_card.hide_post": "Hide post",
  "post_card.unlike": "Unlike",
  "post_card.view_comments": "View comments",
  "post_card.share_post": "Share post",
  "post_card.unsave_post": "Unsave post",
  "post_card.views": " views",
  "post_card.liked": "Liked",
  "post_card.unliked": "Unliked",
  "post_card.symbol": "… ",
  "post_card.more": "more",
  "post_card.video_by": "Video by ",
  "post_card.photo_by": "Photo by ",
  "post_card.photos_by": "Photos by ",
  "post_card.post_by": "Post by ",
  "post_card.symbol_2": " · ",
  "post_card.view_all": "View all ",
  "post_card.start_the_conversation": "Start the conversation",
  "post_card.delete_comment": "Delete comment",
  "post_viewer.post_not_available": "Post not available",
  "post_viewer.close": "Close",
  "post_viewer.view_the_photo_or_video_with_its_comments_press_escape_to_close": "View the photo or video with its comments. Press Escape to close.",
  "post_viewer.close_post": "Close post",
  "post_viewer.shared_a_moment": "Shared a moment.",
  "post_viewer.view_earlier_comments": "View earlier comments",
  "post_viewer.be_the_first_to_say_something": "Be the first to say something.",
  "post_viewer.add_a_comment": "Add a comment…",
  "post_viewer.followers": "Followers",
  "post_viewer.people": "People ",
  "post_viewer.followed_by": "followed by ",
  "post_viewer.no_followers_yet": "No followers yet.",
  "post_viewer.not_following_anyone_yet": "Not following anyone yet.",
  "reels.make_it_a_moving_moment": "Make it a moving moment",
  "reels.share_a_short_video_and_start_the_reel_collection": "Share a short video and start the reel collection.",
  "reels.create_a_reel": "Create a reel",
  "reels.create_reel": "Create reel",
  "reels.reels_feed": "Reels feed",
  "reels.of": " of ",
  "reels.reel_by": "Reel by ",
  "reels.reel_video": "Reel video",
  "reels.this_video_couldn_t_load_please_refresh_to_try_again": "This video couldn’t load. Please refresh to try again.",
  "reels.play_video": "Play video",
  "reels.pause_reel": "Pause reel",
  "reels.play_reel": "Play reel",
  "reels.unmute_reel": "Unmute reel",
  "reels.mute_reel": "Mute reel",
  "reels.sample_reel_original_clip": "Sample reel · Original clip",
  "reels.original_video": "Original video",
  "reels.s": "s",
  "reels.share_reel": "Share reel",
  "reels.unsave_reel": "Unsave reel",
  "reels.save_reel": "Save reel",
  "reels.seek_video": "Seek video",
  "reset_password_form.use_at_least_12_characters": "Use at least 12 characters.",
  "reset_password_form.unable_to_update_the_password": "Unable to update the password.",
  "reset_password_form.password_updated": "Password updated",
  "reset_password_form.your_password_has_been_changed_and_other_signed_in_devices_were_s": "Your password has been changed and other signed-in devices were signed out.",
  "reset_password_form.sign_in_with_the_new_password": "Sign in with the new password",
  "reset_password_form.choose_a_new_password": "Choose a new password",
  "reset_password_form.your_current_password_will_stop_working_everywhere_you_are_signed": "Your current password will stop working everywhere you are signed in.",
  "reset_password_form.new_password": "New password",
  "reset_password_form.confirm_new_password": "Confirm new password",
  "reset_password_form.updating": "Updating…",
  "reset_password_form.update_password": "Update password",
  "settings.your_account_is_now_private": "Your account is now private.",
  "settings.your_account_is_public_again": "Your account is public again.",
  "settings.please_wait_a_minute_before_trying_again": "Please wait a minute before trying again.",
  "settings.unable_to_start_the_email_change": "Unable to start the email change.",
  "settings.a_confirmation_link_was_sent_to_the_new_address_your_email_stays_": "A confirmation link was sent to the new address. Your email stays the same until you open it.",
  "settings.unable_to_start_account_deletion": "Unable to start account deletion.",
  "settings.a_deletion_link_is_on_its_way_to_your_email_your_account_stays_un": "A deletion link is on its way to your email. Your account stays until you open it.",
  "settings.privacy_collections_and_your_account": "Privacy, collections, and your account.",
  "settings.privacy": "Privacy",
  "settings.private_account": "Private account",
  "settings.only_approved_followers_can_see_your_posts_and_your_profile_conte": "Only approved followers can see your posts and your profile content.",
  "settings.toggle_private_account": "Toggle private account",
  "settings.collections": "Collections",
  "settings.organize_saved_posts_into_groups_of_your_own": "Organize saved posts into groups of your own.",
  "settings.new_collection_name": "New collection name",
  "settings.add": "Add",
  "settings.saved": " saved",
  "settings.delete_collection": "Delete collection ",
  "settings.account_email": "Account email",
  "settings.currently_signed_in_as": "Currently signed in as ",
  "settings.changing_your_email_sends_a_confirmation_to_the_new_address": ". Changing your email sends a confirmation to the new address.",
  "settings.new_email_address": "New email address",
  "settings.change_email": "Change email",
  "settings.danger_zone": "Danger zone",
  "settings.delete_your_account": "Delete your account",
  "settings.permanently_removes_your_profile_posts_messages_and_saved_items_a": "Permanently removes your profile, posts, messages, and saved items. A link is sent to your email to confirm.",
  "settings.delete_account": "Delete account",
  "settings.sign_out_of_this_device": "Sign out of this device",
  "settings.confirm_account_deletion": "Confirm account deletion",
  "settings.permanently_delete_your_account_this_cannot_be_undone": "Permanently delete your account? This cannot be undone.",
  "settings.keep_my_account": "Keep my account",
  "settings.email_me_the_deletion_link": "Email me the deletion link",
  "stories.your_story": "Your story",
  "stories.more_stories": "More stories",
  "stories.story_by": "Story by ",
  "stories.use_the_arrow_keys_for_the_next_or_previous_story_space_pauses_pl": "Use the arrow keys for the next or previous story. Space pauses playback.",
  "stories.rstmc": "RSTMC",
  "stories.symbol": ".",
  "stories.close_story": "Close story",
  "stories.view_who_saw_this_story": "View who saw this story",
  "stories.close_reply": "Close reply",
  "stories.reply_to_this_story": "Reply to this story",
  "stories.play_story": "Play story",
  "stories.pause_story": "Pause story",
  "stories.unmute_story": "Unmute story",
  "stories.mute_story": "Mute story",
  "stories.story_photo": "Story photo",
  "stories.previous_story": "Previous story",
  "stories.next_story": "Next story",
  "stories.reply_sent_to": "Reply sent to ",
  "stories.reply_to": "Reply to ",
  "stories.reply": "Reply…",
  "stories.send_reply": "Send reply",
  "stories.who_viewed_this_story": "Who viewed this story",
  "stories.viewed_by": "Viewed by",
  "stories.close_viewer_list": "Close viewer list",
  "stories.only_you_have_seen_this_so_far": "Only you have seen this so far.",
  "views.a_fresh_perspective_awaits": "A fresh perspective awaits",
  "views.your_photos_will_appear_here": "Your photos will appear here.",
  "views.open_post_by": "Open post by ",
  "views.comments": " comments",
  "views.keep_a_little_inspiration": "Keep a little inspiration",
  "views.share_your_first_moment": "Share your first moment",
  "views.no_posts_yet": "No posts yet",
  "views.tap_the_bookmark_on_a_post_to_keep_it_here": "Tap the bookmark on a post to keep it here.",
  "views.your_photos_and_videos_deserve_a_place_here": "Your photos and videos deserve a place here.",
  "views.their_next_moment_will_appear_here": "Their next moment will appear here.",
  "views.explore_posts": "Explore posts",
  "views.create_a_post": "Create a post",
  "views.your_following_feed": "Your following feed",
  "views.their_latest_moments_will_appear_here": "Their latest moments will appear here.",
  "views.find_people": "Find people",
  "views.make_this_feed_yours": "Make this feed yours",
  "views.follow_a_few_people_to_see_their_latest_moments_here": "Follow a few people to see their latest moments here.",
  "views.load_more_posts": "Load more posts",
  "views.symbol": "✓",
  "views.you_re_all_caught_up": "You’re all caught up",
  "views.a_good_moment_to_make_a_moment": "A good moment to make a moment.",
  "views.your_world_shared": "Your world, shared",
  "views.a_little_more_you": "A little more you.",
  "views.edit": "Edit",
  "views.suggested_for_you": "Suggested for you",
  "views.see_all": "See all",
  "views.about": "About",
  "views.symbol_2": "·",
  "views.discover_rstmc_with_sample_profiles_and_posts": "Discover RSTMC with sample profiles and posts.",
  "views.make_it_yours_by_sharing_your_own_moments": "Make it yours by sharing your own moments.",
  "views.2026_rstmc": "© 2026 RSTMC",
  "views.people_places_and_moments": "People, places, and moments.",
  "views.search_people_places_and_hashtags": "Search people, places and hashtags",
  "views.clear_search": "Clear search",
  "views.recent": "Recent",
  "views.clear_all": "Clear all",
  "views.from_recent_searches": " from recent searches",
  "views.people": "People",
  "views.sample_profile": " · Sample profile",
  "views.you": "You",
  "views.no_accounts_match": "No accounts match “",
  "views.try_another_name": "”. Try another name.",
  "views.posts": "Posts",
  "views.nothing_found_for": "Nothing found for “",
  "views.symbol_3": "”.",
  "views.still_searching": "Still searching…",
  "views.discover_people": "Discover people",
  "views.explore_what_s_new": "Explore what’s new",
  "views.photos_and_reels_from_across_rstmc": "Photos and reels from across RSTMC.",
  "views.a_different_perspective_every_scroll": "A different perspective, every scroll.",
  "views.load_more_moments": "Load more moments",
  "views.you_ve_explored_everything_for_now": "You’ve explored everything for now.",
  "views.symbol_4": "#",
  "views.posts_and_reels_shared_with_this_hashtag": "Posts and reels shared with this hashtag.",
  "views.no_posts_use_this_hashtag_yet": "No posts use this hashtag yet.",
  "views.all": "All",
  "views.likes": "Likes",
  "views.comments_2": "Comments",
  "views.follows": "Follows",
  "views.tags": "Tags",
  "views.new_activity": "New activity",
  "views.recent_activity": "Recent activity",
  "views.filter_notifications": "Filter notifications",
  "views.when_someone_likes_comments_or_follows_you_you_ll_see_it_here": "When someone likes, comments, or follows you, you’ll see it here.",
  "views.nothing_here_yet": "Nothing here yet",
  "views.no": "No ",
  "views.notifications_yet": "notifications yet.",
  "views.liked_your_post": "liked your post",
  "views.started_following_you": "started following you",
  "views.commented_on_your_post": "commented on your post",
  "views.tagged_you_in_a_post": "tagged you in a post",
  "views.interacted_with_you": "interacted with you",
  "views.sent_you_an_announcement": "sent you an announcement",
  "views.and": " and ",
  "views.other": " other",
  "views.new": "New",
  "views.verified": "Verified",
  "views.private": "Private",
  "views.message": "Message",
  "views.share_profile": "Share profile",
  "views.report": "Report",
  "views.unblock": "Unblock ",
  "views.block": "Block ",
  "views.unblock_2": "Unblock",
  "views.block_2": "Block",
  "views.posts_2": " posts",
  "views.followers": " followers",
  "views.following": " following",
  "views.a_little_space_to_share_your_world": "A little space to share your world.",
  "views.sample_profile_2": "Sample profile",
  "views.little_things_to_come_back_to_only_you_can_see_this": "Little things to come back to. Only you can see this.",
  "views.your_saved_moments": "Your saved moments",
  "views.sign_in_to_keep_posts_to_come_back_to": "Sign in to keep posts to come back to.",
  "metadata.title": "{site} — Your world, shared",
  "metadata.description": "Share the moments that matter. Photos, stories, reels, and conversations on {site}.",
  "metadata.sectionTitle": "{section} — {site}",
  "common.homeLink": "{site} home",
  "common.avatarFallback": "R",
  "common.goToPhoto": "Go to photo {number}",
  "common.pluralSuffix": "s",
  "auth.previewAccount": "Use the local preview account",
  "post.commentPlaceholder": "Add a comment…",
  "create.stepOf": " of 3 · ",
  "create.of": " of ",
  "create.earlier": " earlier",
  "create.later": " later",
  "post.likes": "likes",
  "post.like": "like",
  "post.comments": " comments",
  "category.travel": "Travel",
  "category.nature": "Nature",
  "category.photography": "Photography",
  "category.architecture": "Architecture",
  "category.lifestyle": "Lifestyle",
  "verify.title": "Verify your email — RSTMC",
  "reset.title": "Reset your password — RSTMC",
  "page.rstmc": "RSTMC",
  "page._": ".",
  "page.functiongram_deployment_preview": "FunctionGram · deployment preview",
  "page.a_home_for_your_moments_": "A home for your moments.",
  "page.the_app_has_been_prepared_for_vercel_its_database_media_storage_o": "The app has been prepared for Vercel. Its database, media storage, or account email delivery still needs configuration before accounts, posts, and messages can be used.",
  "page.project_owner_connect_neon_postgresql_a_public_vercel_blob_store_": "Project owner: connect Neon PostgreSQL, a public Vercel Blob store, and Brevo transactional email, then configure the missing environment variables and redeploy.",
  "page.the_existing_rstmc_site_is_a_separate_deployment_its_accounts_and": "The existing RSTMC site is a separate deployment. Its accounts and data have not been migrated.",
  "page.sign_in_to_continue": "Sign in to continue",
  "page.browsing_is_available_to_signed_in_members_": "Browsing is available to signed-in members.",
  "page.rstmc_home": "RSTMC home",
  "page.your_account_was_deleted": "Your account was deleted",
  "page.your_profile_posts_and_messages_have_been_removed_thanks_for_spen": "Your profile, posts, and messages have been removed. Thanks for spending time with us.",
  "page.go_home": "Go home",
  "page.this_link_is_invalid_or_has_expired_please_try_again_from_the_ema": "This link is invalid or has expired. Please try again from the email you received.",
  "page.your_email_address_was_updated_sign_in_with_it_": "Your email address was updated. Sign in with it.",
  "page.email_verified_sign_in_to_continue_": "Email verified. Sign in to continue.",
  "page.this_reset_link_is_invalid_or_has_expired_reset_links_work_once_a": "This reset link is invalid or has expired. Reset links work once and last 15 minutes.",
  "page.back_to_sign_in": "Back to sign in",
  "error.please_open_rstmc_to_make_this_change": "Please open RSTMC to make this change.",
  "error.please_complete_the_required_fields": "Please complete the required fields.",
  "error.this_request_is_too_large": "This request is too large.",
  "error.please_check_your_input": "Please check your input.",
  "error.sign_in_to_join_the_conversation": "Sign in to join the conversation.",
  "error.post_not_found": "Post not found.",
  "error.invalid_hashtag": "Invalid hashtag.",
  "error.invalid_relationship": "Invalid relationship.",
  "error.story_not_found": "Story not found.",
  "error.type_at_least_two_characters": "Type at least two characters.",
  "error.check_the_media_options_and_try_again": "Check the media options and try again.",
  "error.choose_a_valid_photo_layout": "Choose a valid photo layout.",
  "error.could_not_read_the_media_size_please_try_again": "Could not read the media size. Please try again.",
  "error.a_tagged_account_is_no_longer_available": "A tagged account is no longer available.",
  "error.invalid_action": "Invalid action.",
  "error.choose_another_profile": "Choose another profile.",
  "error.profile_not_found": "Profile not found.",
  "error.comment_not_found": "Comment not found.",
  "error.you_can_only_delete_your_own_comments_or_comments_on_your_posts": "You can only delete your own comments, or comments on your posts.",
  "error.use_3_30_letters_numbers_dots_or_underscores_for_your_username": "Use 3–30 letters, numbers, dots, or underscores for your username.",
  "error.enter_a_complete_website_url_starting_with_https": "Enter a complete website URL, starting with https://.",
  "error.enter_a_valid_http_s_website_url": "Enter a valid http(s) website URL.",
  "error.please_upload_a_profile_photo": "Please upload a profile photo.",
  "error.that_username_is_taken_try_another": "That username is taken. Try another.",
  "error.choose_a_post_story_or_reel": "Choose a post, story, or reel.",
  "error.reels_are_currently_paused": "Reels are currently paused.",
  "error.add_up_to_6_photos_or_one_video": "Add up to 6 photos or one video.",
  "error.choose_a_valid_category": "Choose a valid category.",
  "error.one_of_your_uploads_is_unavailable_please_upload_it_again": "One of your uploads is unavailable. Please upload it again.",
  "error.stories_and_reels_need_one_file_a_photo_post_can_include_up_to_6_image": "Stories and reels need one file. A photo post can include up to 6 images.",
  "error.you_can_only_edit_your_own_posts": "You can only edit your own posts.",
  "error.only_your_stories_can_be_highlighted": "Only your stories can be highlighted.",
  "error.you_can_only_delete_your_own_posts": "You can only delete your own posts.",
  "error.this_story_is_no_longer_available": "This story is no longer available.",
  "error.this_is_a_sample_profile_you_can_message_real_members_or_save_a_note_t": "This is a sample profile. You can message real members or save a note to yourself.",
  "error.you_cannot_message_this_profile": "You cannot message this profile.",
  "error.message_not_found": "Message not found.",
  "error.invalid_setting": "Invalid setting.",
  "error.choose_what_you_are_reporting": "Choose what you are reporting.",
  "error.you_cannot_report_your_own_profile": "You cannot report your own profile.",
  "error.choose_a_reason_for_the_report": "Choose a reason for the report.",
  "error.give_the_collection_a_longer_name": "Give the collection a longer name.",
  "error.collection_not_found": "Collection not found.",
  "error.you_can_only_delete_your_own_collections": "You can only delete your own collections.",
  "error.unknown_action": "Unknown action.",
  "error.sign_in_to_browse": "Sign in to browse.",
  "error.this_feature_is_currently_unavailable": "This feature is currently unavailable.",
  "error.invalid_upload_name": "Invalid upload name.",
  "error.invalid_upload": "Invalid upload.",
  "error.choose_a_supported_photo_or_video_smaller_than_20_mb": "Choose a supported photo or video smaller than 20 MB.",
  "error.please_start_a_new_upload": "Please start a new upload.",
  "error.you_have_reached_today_s_upload_limit_try_again_tomorrow": "You have reached today’s upload limit. Try again tomorrow.",
  "error.upload_not_found": "Upload not found.",
  "error.this_upload_has_expired_start_again": "This upload has expired. Start again.",
  "error.the_upload_size_did_not_match_try_again": "The upload size did not match. Try again.",
  "error.your_upload_is_not_ready_please_try_again": "Your upload is not ready. Please try again.",
  "error.the_file_contents_do_not_match_its_photo_or_video_type": "The file contents do not match its photo or video type.",
  "error.a_verified_mp4_or_webm_video_is_required": "A verified MP4 or WebM video is required.",
  "error.could_not_verify_video_duration_choose_a_video_with_readable_duration_": "Could not verify video duration. Choose a video with readable duration metadata.",
  "error.a_reel_requires_one_video": "A reel requires one video.",
  "error.video_exceeds_the_current_20_mb_upload_limit": "Video exceeds the current 20 MB upload limit.",
  "error.choose_a_registered_video": "Choose a registered video.",
  "error.video_asset_is_unavailable_or_too_large": "Video asset is unavailable or too large.",
  "error.untrusted_media_host": "Untrusted media host.",
  "error.video_exceeds_the_current_upload_limit": "Video exceeds the current upload limit.",
  "error.could_not_read_video_metadata_please_try_again": "Could not read video metadata. Please try again.",
  "nav.tag": "Tag",
  "kind.post": "post",
  "kind.reel": "reel",
  "kind.story": "story",
  "relation.following": "following ",
  "notification.like": "like",
  "notification.comment": "comment",
  "notification.follow": "follow",
  "notification.tag": "tag",
  "notification.announcement": "announcement",
  "common.position": "{number} of {total}",
  "page.this_page_does_not_exist_404_": "This page does not exist (404).",
  "page.back_to_home": "Back to home",
  "page.sign_in_to_rstmc_with_your_verified_admin_account_then_return_to_": "Sign in to RSTMC with your verified admin account, then return to this address.",
  "page.open_rstmc_to_sign_in": "Open RSTMC to sign in",
  "page.access_denied": "Access denied",
  "page.administrator_access_is_required_your_account_does_not_have_permi": "Administrator access is required. Your account does not have permission to view this page.",
  "page.return_to_rstmc": "Return to RSTMC",
  "media.disabled": "Uploads are currently disabled.",
  "media.typeDisabled": "This media type is currently disabled.",
  "media.tooLarge": "Choose a file smaller than {max} MB.",
  "media.maxItems": "Choose up to {max} photos, or one video.",
  "media.hint": "Drag & drop works too · {types} · Up to {max} MB per file · {quota} MB per day · {items} photos per post"
} as const;
