import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes} from 'node:crypto';
import {isIP} from 'node:net';
import type {PoolLike,QueryExecutor} from '../postgres';
import {authorizeAdmin,insertAudit,saveSetting,transaction} from './core';
import {AdminError} from './validation';
import {invalidateModerationConfig,validateModeration} from '../moderation-policy';
export type ReportFilters={status:string;reason:string;target:string;q:string;page:number};
type ReportItem={id:string;reporter_id:string;reporter_username:string|null;target_type:string;target_id:string;reason:string;details:string;created_at:number;status:string;assigned_to:string|null;handled_by:string|null;handled_at:number|null;notes:string|null;action_taken:string|null;action_target_type:string|null;action_target_id:string|null;assignee_username:string|null;target_username:string|null;target_author_id:string|null};
const REPORT_STATUSES=['new','triage','actioned','dismissed'];
const REPORT_REASONS=['spam','harassment','false_information','misleading','inappropriate','other'];
export function reportFilters(input:Record<string,unknown>):ReportFilters{
 const status=String(input.status||'new'),reason=String(input.reason||''),target=String(input.target||'all'),q=String(input.q||''),page=Number(input.page||1);
 if(!REPORT_STATUSES.includes(status)&&status!=='all'||reason&&!REPORT_REASONS.includes(reason)||!['all','post','profile'].includes(target)||q.length>100||!Number.isSafeInteger(page)||page<1||page>10000)throw new AdminError('Invalid report filters.');return {status,reason,target,q,page};
}
export async function reportQueue(db:QueryExecutor,input:Record<string,unknown>={}){
 const filter=reportFilters(input),where:string[]=[],values:unknown[]=[];const bind=(v:unknown)=>{values.push(v);return '$'+values.length;};
 if(filter.status!=='all')where.push(`r.status=${bind(filter.status)}`);if(filter.reason)where.push(`r.reason=${bind(filter.reason)}`);if(filter.target!=='all')where.push(`r.target_type=${bind(filter.target)}`);
 if(filter.q){const q='%'+filter.q.replace(/[\\%_]/g,'\\$&')+'%';where.push(`(r.target_id ILIKE ${bind(q)} OR r.reporter_id ILIKE ${bind(q)} OR reporter.username ILIKE ${bind(q)} OR COALESCE(target_profile.username,author.username,'') ILIKE ${bind(q)})`);}
 const clause=where.length?' WHERE '+where.join(' AND '):'';
 const {rows:[total]}=await db.query('SELECT COUNT(*) total FROM reports r LEFT JOIN profiles reporter ON reporter.id=r.reporter_id LEFT JOIN posts p ON r.target_type=\'post\' AND p.id=r.target_id LEFT JOIN profiles author ON author.id=p.author_id LEFT JOIN profiles target_profile ON r.target_type=\'profile\' AND target_profile.id=r.target_id '+clause,values);
 const {rows}=await db.query(`SELECT r.id,r.reporter_id,r.target_type,r.target_id,r.reason,r.details,r.created_at,r.status,r.assigned_to,r.handled_by,r.handled_at,r.notes,r.action_taken,r.action_target_type,r.action_target_id,reporter.username reporter_username,COALESCE(target_profile.username,author.username) target_username,COALESCE(p.author_id,r.target_id) target_author_id,assignee.username assignee_username FROM reports r LEFT JOIN profiles reporter ON reporter.id=r.reporter_id LEFT JOIN posts p ON r.target_type='post' AND p.id=r.target_id LEFT JOIN profiles author ON author.id=p.author_id LEFT JOIN profiles target_profile ON r.target_type='profile' AND target_profile.id=r.target_id LEFT JOIN profiles assignee ON assignee.id=r.assigned_to ${clause} ORDER BY CASE r.status WHEN 'new' THEN 0 WHEN 'triage' THEN 1 WHEN 'actioned' THEN 2 ELSE 3 END,r.created_at DESC,r.id LIMIT 50 OFFSET $${values.length+1}`,[...values,(filter.page-1)*50]);
 const {rows:counts}=await db.query('SELECT status,COUNT(*) total FROM reports GROUP BY status');
 return {filter,total:Number(total.total),items:rows as unknown as ReportItem[],counts:Object.fromEntries(counts.map(row=>[String(row.status),Number(row.total)])) as Record<string,number>};
}
export async function publishModerationSettings(pool:PoolLike,actorId:string,input:unknown){let config;try{config=validateModeration(input);}catch(error){if(error instanceof AdminError)throw error;throw new AdminError('Invalid moderation settings.');}await saveSetting(pool,actorId,'moderation.config',JSON.stringify(config));invalidateModerationConfig();return config;}
function requiredText(value:unknown,max:number,label:string){if(typeof value!=='string'||value.length>max||!value.trim())throw new AdminError(`Enter ${label} (up to ${max} characters).`);return value.trim();}
export async function setProfileModeration(pool:PoolLike,actorId:string,body:Record<string,unknown>){
 const profileId=requiredText(body.profileId,100,'an account ID'),reason=typeof body.reason==='string'?body.reason.trim():'';if(reason.length>500||typeof body.shadowBanned!=='boolean'||typeof body.commentBanned!=='boolean')throw new AdminError('Choose valid moderation states and a reason (up to 500 characters).');if((body.shadowBanned||body.commentBanned)&&!reason)throw new AdminError('A reason is required while a restriction is active.');const auditReason=reason||'Moderation restrictions cleared.';
 return transaction(pool,async db=>{const actor=await authorizeAdmin(db,actorId);if(profileId===actorId)throw new AdminError('You cannot apply account restrictions to your own profile.',403);const {rows:[profile]}=await db.query('SELECT p.id,u.role FROM profiles p JOIN "user" u ON u.id=p.id WHERE p.id=$1 AND p.deleted_at IS NULL FOR UPDATE OF p,u',[profileId]);if(!profile)throw new AdminError('Profile not found.',404);if(profile.role==='owner'&&actor.role!=='owner')throw new AdminError('Owner accounts are protected.',403);if(profile.role==='admin'&&actor.role!=='owner')throw new AdminError('Only the owner can restrict an administrator.',403);
 const {rows:[before]}=await db.query('SELECT shadow_banned,comment_banned,shadow_reason,comment_reason FROM profile_moderation WHERE profile_id=$1 FOR UPDATE',[profileId]);
 await db.query(`INSERT INTO profile_moderation(profile_id,shadow_banned,comment_banned,shadow_reason,comment_reason,updated_at,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(profile_id) DO UPDATE SET shadow_banned=EXCLUDED.shadow_banned,comment_banned=EXCLUDED.comment_banned,shadow_reason=EXCLUDED.shadow_reason,comment_reason=EXCLUDED.comment_reason,updated_at=EXCLUDED.updated_at,updated_by=EXCLUDED.updated_by`,[profileId,body.shadowBanned,body.commentBanned,body.shadowBanned?reason:'',body.commentBanned?reason:'',Date.now(),actor.userId]);
 const after={shadow_banned:body.shadowBanned,comment_banned:body.commentBanned,reason:body.shadowBanned||body.commentBanned?reason:''};await insertAudit(db,actor,{action:'moderation.account',targetType:'profile',targetId:profileId,before:before||{shadow_banned:false,comment_banned:false},after,reason:auditReason});return after;});
}
export async function accountModeration(db:QueryExecutor,profileId:string){if(!profileId||profileId.length>100)throw new AdminError('Enter an account ID.');const {rows:[profile]}=await db.query('SELECT id FROM profiles WHERE id=$1 AND deleted_at IS NULL',[profileId]);if(!profile)throw new AdminError('Profile not found.',404);const {rows:[row]}=await db.query('SELECT shadow_banned,comment_banned,shadow_reason,comment_reason,updated_at,updated_by FROM profile_moderation WHERE profile_id=$1',[profileId]);return row||{shadow_banned:false,comment_banned:false,shadow_reason:'',comment_reason:''};}
export async function closeReport(pool:PoolLike,actorId:string,body:Record<string,unknown>){
 const id=requiredText(body.id,100,'a report ID'),action=String(body.action||''),reason=typeof body.reason==='string'?body.reason.trim():'';if(!['hide','ban','dismiss'].includes(action)||reason.length>500||(action!=='dismiss'&&!reason))throw new AdminError('Choose a report action and provide a reason (up to 500 characters).');
 return transaction(pool,async db=>{
  const actor=await authorizeAdmin(db,actorId);const {rows:[report]}=await db.query('SELECT * FROM reports WHERE id=$1 FOR UPDATE',[id]);if(!report)throw new AdminError('Report not found.',404);if(['actioned','dismissed'].includes(report.status))throw new AdminError('This report is already resolved.',409);
  let actionTargetType:string|undefined,actionTargetId:string|undefined;
  if(action==='hide'){
   if(report.target_type!=='post')throw new AdminError('Only a post report can be resolved by hiding this item.');const {rows:[post]}=await db.query('SELECT id,hidden_at,deleted_at FROM posts WHERE id=$1 FOR UPDATE',[report.target_id]);if(!post||post.deleted_at!=null)throw new AdminError('Reported post is unavailable.',404);
   await db.query('UPDATE posts SET hidden_at=$1,hidden_by=$2,hidden_reason=$3 WHERE id=$4',[Date.now(),actor.userId,reason,report.target_id]);await insertAudit(db,actor,{action:'content.hide',targetType:'post',targetId:report.target_id,before:{hidden_at:post.hidden_at},after:{hidden_at:Date.now(),hidden_by:actor.userId},reason});actionTargetType='post';actionTargetId=report.target_id;
  }
  if(action==='ban'){
   let profileId=String(report.target_id);if(report.target_type==='post'){const {rows:[post]}=await db.query('SELECT author_id FROM posts WHERE id=$1',[report.target_id]);if(!post)throw new AdminError('Reported post is unavailable.',404);profileId=String(post.author_id);}else if(report.target_type!=='profile')throw new AdminError('This report target cannot be banned.');
   const {rows:[user]}=await db.query('SELECT id,email,role,banned,"banReason","banExpires" FROM "user" WHERE id=$1 FOR UPDATE',[profileId]);if(!user)throw new AdminError('Reported account is unavailable.',404);if(user.role==='owner'&&user.id!==actor.userId)throw new AdminError('Owner accounts are protected.',403);if(user.role==='admin'&&actor.role!=='owner')throw new AdminError('Only the owner can ban an administrator.',403);if(user.id===actor.userId)throw new AdminError('You cannot ban your own account.',403);
   const before={banned:user.banned,reason:user.banReason};await db.query('UPDATE "user" SET banned=true,"banReason"=$1,"banExpires"=NULL,"updatedAt"=now() WHERE id=$2',[reason,user.id]);await db.query('DELETE FROM session WHERE "userId"=$1',[user.id]);await insertAudit(db,actor,{action:'users.ban',targetType:'user',targetId:user.id,before,after:{banned:true},reason});actionTargetType='user';actionTargetId=user.id;
  }
  const newStatus=action==='dismiss'?'dismissed':'actioned';const notes=typeof body.notes==='string'?body.notes.trim():String(report.notes||'');if(notes.length>2000)throw new AdminError('Report notes are limited to 2,000 characters.');
  await db.query('UPDATE reports SET status=$1,handled_by=$2,handled_at=$3,assigned_to=COALESCE(assigned_to,$2),notes=$4,action_taken=$5,action_target_type=$6,action_target_id=$7 WHERE id=$8',[newStatus,actor.userId,Date.now(),notes,action==='dismiss'?null:action,actionTargetType||null,actionTargetId||null,id]);
  await insertAudit(db,actor,{action:'reports.'+action,targetType:report.target_type,targetId:report.target_id,before:{status:report.status},after:{status:newStatus,action_target_type:actionTargetType||null,action_target_id:actionTargetId||null},reason});return {status:newStatus};
 });
}
const secret=()=>{if(!process.env.BETTER_AUTH_SECRET||process.env.BETTER_AUTH_SECRET.length<32)throw new AdminError('Rate-limit controls are unavailable until the auth secret is configured.',503);return createHash('sha256').update(process.env.BETTER_AUTH_SECRET).digest();};
function seal(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',secret(),iv),data=Buffer.concat([cipher.update(JSON.stringify({issuedAt:Date.now(),value}),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64url');}
function unseal(token:unknown){if(typeof token!=='string'||token.length>1024)throw new AdminError('Invalid rate-limit selection.');try{const bytes=Buffer.from(token,'base64url');if(bytes.length<29||bytes.length>700)throw new Error();const decipher=createDecipheriv('aes-256-gcm',secret(),bytes.subarray(0,12));decipher.setAuthTag(bytes.subarray(12,28));const payload=JSON.parse(Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString('utf8')) as {issuedAt:number;value:string};if(!Number.isSafeInteger(payload.issuedAt)||payload.issuedAt>Date.now()+60000||payload.issuedAt<Date.now()-15*60_000||typeof payload.value!=='string')throw new Error();return payload.value;}catch(error){if(error instanceof AdminError)throw error;throw new AdminError('Invalid or expired rate-limit selection.',403);}}
const digest=(value:string)=>createHmac('sha256',secret()).update(value).digest('hex').slice(0,16);
export async function rateLimitQueue(db:QueryExecutor,pageInput:unknown=1){const page=Number(pageInput);if(!Number.isSafeInteger(page)||page<1||page>10000)throw new AdminError('Invalid rate-limit page.');const {rows:[summary]}=await db.query('SELECT COUNT(*) buckets,COALESCE(SUM(count),0) hits FROM "rateLimit" WHERE "lastRequest">$1',[Date.now()-86400000]);const {rows}=await db.query('SELECT key,count,"lastRequest" FROM "rateLimit" WHERE "lastRequest">$1 ORDER BY "lastRequest" DESC,key LIMIT 50 OFFSET $2',[Date.now()-86400000,(page-1)*50]);const items=rows.map(row=>{const key=String(row.key),split=key.lastIndexOf('|'),ip=split<0?key:key.slice(0,split),path=split<0?'unknown path':key.slice(split+1);return {client:digest(ip),path:path.slice(0,160),count:Number(row.count),lastRequest:Number(row.lastRequest),clientToken:seal(ip)};});return {page,total:Number(summary.buckets),hits:Number(summary.hits),items};}
export async function clearRateLimit(pool:PoolLike,actorId:string,body:Record<string,unknown>){const ip=unseal(body.clientToken);if(ip.includes('|')||!(isIP(ip)||ip==='no-trusted-ip'))throw new AdminError('Invalid client selection.',403);return transaction(pool,async db=>{const actor=await authorizeAdmin(db,actorId);const {rows:[before]}=await db.query('SELECT COUNT(*) buckets,COALESCE(SUM(count),0) hits FROM "rateLimit" WHERE split_part(key,\'|\',1)=$1',[ip]);if(!Number(before.buckets))throw new AdminError('No current rate-limit entries for this client.',404);await db.query('DELETE FROM "rateLimit" WHERE split_part(key,\'|\',1)=$1',[ip]);await insertAudit(db,actor,{action:'rateLimit.clear',targetType:'rateLimitClient',targetId:digest(ip),before:{buckets:Number(before.buckets),hits:Number(before.hits)},after:{buckets:0,hits:0}});return {buckets:Number(before.buckets)};});}
export async function updateReport(pool:PoolLike,actorId:string,body:Record<string,unknown>){
 const id=requiredText(body.id,100,'a report ID'),operation=body.operation==='assign'?'assign':body.operation==='notes'?'notes':'';if(!operation)throw new AdminError('Choose a report update.');const notes=typeof body.notes==='string'?body.notes.trim():'';if(notes.length>2000)throw new AdminError('Report notes are limited to 2,000 characters.');
 return transaction(pool,async db=>{const actor=await authorizeAdmin(db,actorId);const {rows:[report]}=await db.query('SELECT status,assigned_to,notes FROM reports WHERE id=$1 FOR UPDATE',[id]);if(!report)throw new AdminError('Report not found.',404);if(['actioned','dismissed'].includes(report.status))throw new AdminError('This report is already resolved.',409);
  if(operation==='assign')await db.query("UPDATE reports SET assigned_to=$1,status='triage' WHERE id=$2",[actor.userId,id]);else await db.query('UPDATE reports SET notes=$1 WHERE id=$2',[notes,id]);
  await insertAudit(db,actor,{action:operation==='assign'?'reports.assign':'reports.notes',targetType:'report',targetId:id,before:{status:report.status,assigned_to:report.assigned_to,notes:report.notes},after:{status:operation==='assign'?'triage':report.status,assigned_to:operation==='assign'?actor.userId:report.assigned_to,notes:operation==='notes'?notes:report.notes}});return {ok:true};
 });
}
