"use client";
import {useEffect,useRef,useState,type CSSProperties,type FormEvent} from 'react';
import {ImagePlus,Plus,X,Film,Camera,MapPin,ArrowLeft,ArrowRight,GripVertical,Check,Search,Accessibility,UploadCloud} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Modal,Avatar,IconButton,Busy,upload,request} from './common';
import {toast} from 'sonner';
import type {MediaOption,Person} from '@/lib/types';

type Kind='post'|'reel'|'story';
type Draft={key:string;file:File;preview:string;url?:string;ratio:MediaOption['ratio'];fit:MediaOption['fit'];alt:string};
const accepted=['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm'];
const steps=['Media','Adjust','Details','Publish'];
const categories=['For you','Travel','Nature','Photography','Architecture','Lifestyle'];
export function CreateDialog({kind:initialKind,me,people,onClose,onCreated}:{kind:Kind;me:Person;people:Person[];onClose:()=>void;onCreated:()=>Promise<void>}){
 const [kind,setKind]=useState<Kind>(initialKind),[files,setFiles]=useState<Draft[]>([]),[step,setStep]=useState(0),[selected,setSelected]=useState(0),[caption,setCaption]=useState(''),[hashtags,setHashtags]=useState(''),[location,setLocation]=useState(''),[category,setCategory]=useState('For you'),[tags,setTags]=useState<Person[]>([]),[tagQuery,setTagQuery]=useState(''),[tagResults,setTagResults]=useState<Person[]>([]),[tagLoading,setTagLoading]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[status,setStatus]=useState(''),[error,setError]=useState('');
 const input=useRef<HTMLInputElement>(null),urls=useRef(new Set<string>()),lock=useRef(false);
 useEffect(()=>()=>{urls.current.forEach(url=>URL.revokeObjectURL(url));},[]);
 useEffect(()=>{if(!tagQuery.trim())return;const controller=new AbortController();const timer=window.setTimeout(()=>{setTagLoading(true);void request<Person[]>('/api/social?accounts='+encodeURIComponent(tagQuery.trim()),undefined,controller.signal).then(setTagResults).catch(()=>{}).finally(()=>{if(!controller.signal.aborted)setTagLoading(false);});},260);return()=>{window.clearTimeout(timer);controller.abort();};},[tagQuery]);
 const choose=(selectedFiles:FileList|null)=>{if(!selectedFiles?.length)return;setError('');const items=Array.from(selectedFiles);if(items.some(f=>!accepted.includes(f.type)||f.size>20*1024*1024||!f.size)){setError('Choose JPG, PNG, WebP, GIF, MP4 or WebM files under 20 MB each.');return;}const combined=[...files.map(x=>x.file),...items];if(combined.length>6||(kind!=='post'&&combined.length>1)||(combined.some(f=>f.type.startsWith('video/'))&&combined.length>1)||(kind==='reel'&&combined.some(f=>!f.type.startsWith('video/')))){setError(kind==='reel'?'A reel needs one video.':'Choose up to 6 photos, or one video on its own.');return;}const added=items.map(file=>{const preview=URL.createObjectURL(file);urls.current.add(preview);return {key:crypto.randomUUID(),file,preview,ratio:'original' as const,fit:'contain' as const,alt:''};});setFiles(list=>[...list,...added]);if(input.current)input.current.value='';};
 const remove=(index:number)=>{const file=files[index];if(!file)return;URL.revokeObjectURL(file.preview);urls.current.delete(file.preview);setFiles(list=>list.filter((_,i)=>i!==index));setSelected(i=>Math.max(0,Math.min(i,files.length-2)));};
 const reorder=(direction:number)=>{const other=selected+direction;if(other<0||other>=files.length)return;setFiles(list=>{const result=[...list];[result[selected],result[other]]=[result[other],result[selected]];return result;});setSelected(other);};
 const update=(key:string,patch:Partial<Draft>)=>setFiles(list=>list.map(f=>f.key===key?{...f,...patch}:f));
 const changeKind=(next:Kind)=>{if(next==='reel'&&files.some(f=>!f.file.type.startsWith('video/'))||next!=='post'&&files.length>1){setError('Remove extra media before switching to '+next+'.');return;}setKind(next);setError('');};
 const preparedTags=[...new Set(hashtags.split(/[\s,]+/).map(h=>h.replace(/^#+/,'').replace(/[^\p{L}\p{N}_]/gu,'')).filter(Boolean))].map(h=>'#'+h).join(' ');
 const finalCaption=[caption.trim(),preparedTags].filter(Boolean).join('\n\n');
 const publish=async()=>{if(lock.current||!files.length)return;if(finalCaption.length>2200){setError('Shorten the caption or hashtags to 2,200 characters.');setStep(2);return;}lock.current=true;setBusy(true);setProgress(0);setStatus('Preparing your media');setError('');try{
   const media:string[]=[];for(let i=0;i<files.length;i++){const f=files[i];setStatus(`Uploading ${i+1} of ${files.length}`);let url=f.url;if(!url){const result=await upload(f.file,percent=>setProgress(Math.round((i+percent/100)/files.length*90)));url=result.url;update(f.key,{url});}media.push(url);setProgress(Math.round((i+1)/files.length*90));}
   setStatus('Publishing your '+kind);setProgress(95);
   await request('/api/social',{action:'create_post',kind,media,media_options:files.map(f=>({ratio:f.ratio,fit:f.fit,alt:f.alt})),tagged_users:tags.map(p=>p.id),caption:finalCaption,location,category});setProgress(100);onClose();void onCreated().catch(()=>toast.error('Published, but the feed could not refresh. Reload to see your post.'));
  }catch(e){setError((e as Error).message);setStatus('');}finally{lock.current=false;setBusy(false);}};
 const active=files[selected];
 return <Modal open onClose={()=>{if(!busy)onClose();}} title="Create a moment" description="Share a photo, story, or reel with your community." className="create-modal"><Tabs value={kind} onValueChange={v=>changeKind(v as Kind)}><TabsList variant="line" className="product-tabs"><TabsTrigger value="post"><ImagePlus size={17}/>Post</TabsTrigger><TabsTrigger value="story"><Camera size={17}/>Story</TabsTrigger><TabsTrigger value="reel"><Film size={17}/>Reel</TabsTrigger></TabsList></Tabs>
   <div className="create-steps" aria-label="Creation steps">{steps.map((name,i)=><span key={name} className={step===i?'current':step>i?'done':''}><i>{step>i?<Check size={13}/>:String(i+1).padStart(2,'0')}</i>{name}</span>)}</div>
   <input ref={input} type="file" accept={kind==='reel'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm'} multiple={kind==='post'} onChange={e=>choose(e.target.files)} className="sr-only" aria-label="Choose photos or video"/>
   <div className="create-content">
    {step===0&&<div className="create-select"><button type="button" className="upload-drop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files);}}><span className="upload-icons"><ImagePlus/><Film/></span><strong>{files.length?'Add another moment':'Your next moment starts here'}</strong><span>{kind==='reel'?'Select a video':'Choose photos or a video'} from your device</span><span className="primary-button">Browse files <ArrowRight size={16}/></span><small>JPG, PNG, WebP, GIF, MP4 or WebM · Up to 20 MB each</small></button>{files.length>0&&<div className="selected-files"><strong>{files.length} {files.length===1?'file':'files'} selected</strong><div>{files.map((f,i)=><div className="selected-file" key={f.key}>{f.file.type.startsWith('video/')?<Film/>:<img src={f.preview} alt=""/>}<span>{f.file.name}</span><IconButton label={'Remove '+f.file.name} onClick={()=>remove(i)}><X size={16}/></IconButton></div>)}</div></div>}</div>}
    {step===1&&active&&<div className="create-adjust"><div className="adjust-preview" style={active.ratio!=='original'?{'--preview-ratio':active.ratio.replace(':',' / '),'--preview-fit':active.fit} as CSSProperties:undefined} data-framed={active.ratio!=='original'}>{active.file.type.startsWith('video/')?<video key={active.key} src={active.preview} controls playsInline preload="metadata"/>:<img src={active.preview} alt={active.alt||'Preview of '+active.file.name}/>}</div><div className="adjust-controls"><div className="field-title"><strong>Frame your moment</strong><span>Original keeps the whole image in view.</span></div><div className="option-row" role="group" aria-label="Aspect ratio">{(['original','1:1','4:5','16:9'] as const).map(r=><button key={r} type="button" className={active.ratio===r?'chosen':''} onClick={()=>update(active.key,{ratio:r})}>{r==='original'?'Original':r}</button>)}</div><div className="option-row" role="group" aria-label="Image fit"><button type="button" className={active.fit==='contain'?'chosen':''} onClick={()=>update(active.key,{fit:'contain'})}>Fit whole image</button><button type="button" className={active.fit==='cover'?'chosen':''} onClick={()=>update(active.key,{fit:'cover'})}>Fill frame</button></div><div className="reorder-row"><IconButton label="Move media left" disabled={selected===0} onClick={()=>reorder(-1)}><ArrowLeft size={18}/></IconButton><GripVertical size={18}/><span>{selected+1} of {files.length}</span><IconButton label="Move media right" disabled={selected===files.length-1} onClick={()=>reorder(1)}><ArrowRight size={18}/></IconButton><button type="button" className="text-action danger" onClick={()=>remove(selected)}>Remove</button></div>{files.length>1&&<div className="create-thumbnails">{files.map((f,i)=><button type="button" key={f.key} className={selected===i?'active':''} onClick={()=>setSelected(i)} aria-label={'Preview media '+(i+1)}>{f.file.type.startsWith('video/')?<Film/>:<img src={f.preview} alt=""/>}</button>)}</div>}</div></div>}
    {step===2&&<div className="create-details"><div className="user-line"><Avatar person={me} size={40}/><div><strong>{me.username}</strong><small>Sharing a {kind}</small></div></div><label className="field-title" htmlFor="create-caption"><strong>Caption</strong><span>Tell the story behind it.</span></label><textarea id="create-caption" placeholder="What’s happening?" maxLength={2200} rows={4} value={caption} onChange={e=>setCaption(e.target.value)}/><span className="character-count">{finalCaption.length}/2,200</span><label className="create-field">Hashtags<input placeholder="#moments #nature" maxLength={300} value={hashtags} onChange={e=>setHashtags(e.target.value)}/></label><label className="create-field">Location<span className="location-input"><MapPin size={18}/><input placeholder="Add a location" maxLength={100} value={location} onChange={e=>setLocation(e.target.value)}/></span></label><label className="create-field">Explore category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>
      {kind!=='story'&&<div className="tag-people"><label className="create-field">Tag people<span className="location-input"><Search size={18}/><input placeholder="Search accounts to tag" value={tagQuery} maxLength={80} onChange={e=>setTagQuery(e.target.value)}/></span></label>{tags.length>0&&<div className="tag-chips">{tags.map(p=><button type="button" key={p.id} onClick={()=>setTags(t=>t.filter(x=>x.id!==p.id))}>@{p.username}<X size={14}/></button>)}</div>}{tagQuery&&<div className="tag-results">{tagLoading?<Busy/>:tagResults.filter(p=>p.id!==me.id&&!tags.some(t=>t.id===p.id)).slice(0,6).map(p=><button type="button" key={p.id} onClick={()=>{setTags(t=>[...t,p].slice(0,10));setTagQuery('');}}><Avatar person={p} size={28}/><span>{p.username}</span></button>)}{!tagLoading&&!tagResults.length&&<span>No accounts found.</span>}</div>}</div>}
      <details className="alt-details"><summary><Accessibility size={18}/> Accessibility text <span>Describe your media</span></summary>{files.map((f,i)=><label key={f.key}>Media {i+1}<input maxLength={300} value={f.alt} placeholder="Describe this image or video" onChange={e=>update(f.key,{alt:e.target.value})}/></label>)}</details>{kind==='story'&&<p className="form-hint">Stories disappear after 24 hours unless added to your highlights.</p>}</div>}
    {step===3&&<div className="publish-summary"><div className="publish-cover">{files[0]?.file.type.startsWith('video/')?<video src={files[0].preview} muted playsInline preload="metadata"/>:<img src={files[0]?.preview} alt="Post preview"/>}</div><div><span className="eyebrow">Ready to share</span><h2>{kind==='post'?'A new moment':kind==='reel'?'A new reel':'Your story'}</h2><p>{files.length} {files.length===1?'file':'files'} · {category}{location?' · '+location:''}</p><p className="publish-caption">{finalCaption||'No caption'}</p>{tags.length>0&&<small>With {tags.map(t=>'@'+t.username).join(', ')}</small>}</div>{busy&&<div className="upload-status" role="status"><div><span>{status}</span><strong>{progress}%</strong></div><progress value={progress} max={100}/></div>}</div>}
   </div>
   {error&&<p role="alert" className="form-error create-error">{error}</p>}
   <div className="create-footer">{step>0?<button type="button" className="secondary-button" disabled={busy} onClick={()=>{setError('');setStep(s=>s-1);}}><ArrowLeft size={16}/>Back</button>:<span/>}{step<3?<button type="button" className="primary-button" disabled={!files.length} onClick={()=>{setError('');setStep(s=>s+1);}}>Continue<ArrowRight size={16}/></button>:<button type="button" className="primary-button" disabled={busy||!files.length} onClick={()=>void publish()}>{busy?<><Busy/>Publishing…</>:<><UploadCloud size={17}/>Publish {kind}</>}</button>}</div>
  </Modal>;
}
export function EditProfile({me,onClose,onSaved}:{me:Person;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(me.name),[username,setUsername]=useState(me.username),[bio,setBio]=useState(me.bio),[website,setWebsite]=useState(me.website||''),[avatar,setAvatar]=useState(me.avatar),[busy,setBusy]=useState(false),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null),lock=useRef(false);
 const photo=async(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')){setError('Choose a photo, not a video.');return;}setBusy(true);try{const r=await upload(file);setAvatar(r.url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await request('/api/social',{action:'profile',username,name,bio,website,avatar});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 return <Modal open onClose={()=>!busy&&onClose()} title="Edit profile"><form onSubmit={submit} className="edit-form"><div className="edit-avatar"><Avatar person={{...me,avatar}} size={78}/><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" aria-label="Choose profile photo" onChange={e=>void photo(e.target.files?.[0])}/><button type="button" className="secondary-button" onClick={()=>input.current?.click()} disabled={busy}>Change photo</button></div><label>Name<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>Username<input required minLength={3} maxLength={30} pattern="[a-zA-Z0-9_][a-zA-Z0-9_.]{2,29}" value={username} onChange={e=>setUsername(e.target.value)} autoCapitalize="none" spellCheck={false}/></label><label>Bio<textarea maxLength={150} rows={3} value={bio} onChange={e=>setBio(e.target.value)}/><span className="form-hint">{bio.length}/150</span></label><label>Website<input type="url" maxLength={200} placeholder="https://your-site.com" value={website} onChange={e=>setWebsite(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="primary-button wide">{busy?<Busy/>:'Save changes'}</button></form></Modal>;
}
