"use client";
import {useState,useRef,type FormEvent} from 'react';
import {ImagePlus,Plus,X,Film,Camera,MapPin} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Modal,Avatar,IconButton,Busy,upload,request} from './common';
import {toast} from 'sonner';
import type {Person} from '@/lib/types';
export function CreateDialog({kind:initialKind,me,onClose,onCreated}:{kind:'post'|'reel'|'story';me:Person;onClose:()=>void;onCreated:()=>Promise<void>}){
 const [kind,setKind]=useState(initialKind),[files,setFiles]=useState<{url:string;type:string}[]>([]),[caption,setCaption]=useState(''),[location,setLocation]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
 const choose=async(selected:FileList|null)=>{if(!selected?.length)return;setError('');const items=Array.from(selected);if(items.length+files.length>6){setError('Choose up to 6 photos, or one video.');return;}if((items.some(f=>f.type.startsWith('video/'))&&(items.length+files.length>1))||(files.some(f=>f.type.startsWith('video/')))){setError('Videos must be shared on their own.');return;}setBusy('Uploading');try{const added:{url:string;type:string}[]=[];for(const file of items)added.push(await upload(file));setFiles(v=>[...v,...added]);}catch(e){setError((e as Error).message);}finally{setBusy('');if(input.current)input.current.value='';}};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!files.length||busy)return;setBusy('Sharing');setError('');try{await request('/api/social',{action:'create_post',kind,media:files.map(f=>f.url),caption,location});await onCreated();toast.success(kind==='story'?'Your story is live for 24 hours.':'Your '+kind+' has been shared.');onClose();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
 return <Modal open onClose={()=>{if(!busy)onClose();}} title="Create something worth sharing" className="create-modal"><Tabs value={kind} onValueChange={v=>setKind(v as typeof kind)}><TabsList variant="line" className="product-tabs"><TabsTrigger value="post"><ImagePlus size={17}/>Post</TabsTrigger><TabsTrigger value="story"><Camera size={17}/>Story</TabsTrigger><TabsTrigger value="reel"><Film size={17}/>Reel</TabsTrigger></TabsList></Tabs><form onSubmit={submit} className="create-form"><input ref={input} type="file" accept={kind==='reel'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm'} multiple={kind==='post'} onChange={e=>void choose(e.target.files)} className="sr-only" aria-label="Upload photos or video"/>
 {!files.length?<button type="button" className="upload-drop" onClick={()=>input.current?.click()} disabled={!!busy} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void choose(e.dataTransfer.files);}}><span className="upload-icons"><ImagePlus/><Film/></span><strong>{busy||'Your next moment starts here'}</strong><span>Choose {kind==='reel'?'a video':'photos or a video'} to share</span><span className="primary-button">{busy?<Busy/>:'Select from your device'}</span><small>JPG, PNG, WebP, GIF, MP4 or WebM · Up to 20 MB</small></button>:<div className="upload-previews">{files.map((file,i)=><div key={file.url}>{file.type.startsWith('video/')?<video src={file.url} controls playsInline/>:<img src={file.url} alt={'Upload '+(i+1)}/>}<IconButton label={'Remove upload '+(i+1)} onClick={()=>setFiles(v=>v.filter((_,n)=>i!==n))}><X size={17}/></IconButton></div>)}{kind==='post'&&files.length<6&&!files.some(f=>f.type.startsWith('video/'))&&<button type="button" className="add-another" onClick={()=>input.current?.click()} disabled={!!busy}><Plus/>Add photo</button>}</div>}
 <div className="create-details"><div className="user-line"><Avatar person={me} size={36}/><strong>{me.username}</strong></div><textarea aria-label="Write a caption" placeholder="Write a caption…" maxLength={2200} rows={3} value={caption} onChange={e=>setCaption(e.target.value)}/><span className="character-count">{caption.length}/2,200</span><label className="location-input"><MapPin size={18}/><input placeholder="Add location" aria-label="Add location" maxLength={100} value={location} onChange={e=>setLocation(e.target.value)}/></label></div>{kind==='story'&&<p className="form-hint">Your story will disappear after 24 hours.</p>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary-button wide" disabled={!files.length||!!busy}>{busy?<><Busy/>{busy}…</>:'Share '+kind}</button></form></Modal>;
}
export function EditProfile({me,onClose,onSaved}:{me:Person;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(me.name),[username,setUsername]=useState(me.username),[bio,setBio]=useState(me.bio),[avatar,setAvatar]=useState(me.avatar),[busy,setBusy]=useState(false),[error,setError]=useState('');const input=useRef<HTMLInputElement>(null);
 const photo=async(file?:File)=>{if(!file)return;setBusy(true);try{const r=await upload(file);if(!r.type.startsWith('image/'))throw new Error('Please choose a photo.');setAvatar(r.url);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await request('/api/social',{action:'profile',username,name,bio,avatar});await onSaved();toast.success('Your profile has been updated.');onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Modal open onClose={()=>!busy&&onClose()} title="Edit profile"><form onSubmit={submit} className="edit-form"><div className="edit-avatar"><Avatar person={{...me,avatar}} size={76}/><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" aria-label="Choose profile photo" onChange={e=>void photo(e.target.files?.[0])}/><button type="button" className="text-action" onClick={()=>input.current?.click()} disabled={busy}>Change photo</button></div><label>Name<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>Username<input required minLength={3} maxLength={30} pattern="[a-zA-Z0-9_][a-zA-Z0-9_.]{2,29}" value={username} onChange={e=>setUsername(e.target.value)} autoCapitalize="none" spellCheck={false}/></label><label>Bio<textarea maxLength={150} rows={3} value={bio} onChange={e=>setBio(e.target.value)}/><span className="form-hint">{bio.length}/150</span></label>{error&&<p role="alert" className="form-error">{error}</p>}<button disabled={busy} className="primary-button wide">{busy?<Busy/>:'Save changes'}</button></form></Modal>;
}
