"use client";
import {useEffect,useRef,useState} from 'react';
import {Search as SearchIcon,X,Clock3,Compass,Film,Layers3,RefreshCw,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Avatar,Busy,Empty,IconButton,count,request} from './common';
import type {Person,Post,SearchResults} from '@/lib/types';

const categories=['For you','Travel','Nature','Photography','Architecture','Lifestyle'];
function VideoTile({src}:{src:string}){const ref=useRef<HTMLDivElement>(null),[near,setNear]=useState(false);useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){setNear(true);observer.disconnect();}},{rootMargin:'240px'});observer.observe(node);return()=>observer.disconnect();},[]);return <div className="grid-video" ref={ref}>{near&&<video muted playsInline preload="metadata" src={src} onLoadedMetadata={e=>{if(e.currentTarget.duration>.15)e.currentTarget.currentTime=.1;}}/>}<Film size={25} className="grid-video-fallback"/></div>;}
export function PostGrid({posts,onPost,variant='profile',empty}:{posts:Post[];onPost:(p:Post)=>void;variant?:'profile'|'explore';empty?:string}){return posts.length?<div className={'photo-grid '+(variant==='explore'?'explore-grid':'')}>{posts.map(p=><button className="grid-photo" key={p.id} onClick={()=>onPost(p)} aria-label={'Open post by '+p.author.username+': '+p.caption.slice(0,65)}>{p.media_type==='video'?<VideoTile src={p.media[0]}/>:<img src={p.media[0]} alt={p.media_options?.[0]?.alt||p.caption||'Photo by '+p.author.username} loading="lazy" decoding="async"/>}{(p.media_type==='video'||p.media.length>1)&&<span className="grid-media-icon">{p.media_type==='video'?<Film size={19}/>:<Layers3 size={18}/>}</span>}<span className="grid-hover"><span><span>♥</span> {count(p.likes)} <span className="grid-separator">·</span> {p.comment_count} comments</span><strong>@{p.author.username}</strong></span></button>)}</div>:<Empty icon={<Compass/>} heading="Nothing here yet" body={empty||'When moments are shared, you’ll find them here.'}/>;}

function remember(query:string,setRecent:(items:string[])=>void){const text=query.trim();if(!text)return;try{const previous=JSON.parse(localStorage.getItem('rstmc-recent-searches')||'[]') as string[];const next=[text,...previous.filter(x=>x!==text)].slice(0,8);localStorage.setItem('rstmc-recent-searches',JSON.stringify(next));setRecent(next);}catch{}}
export function SearchPage({query,setQuery,people,personCache,meId,cache,onLoaded,onPost,onProfile,onFollow,followPending}:{query:string;setQuery:(v:string)=>void;people:Person[];personCache:Record<string,Person>;meId?:string;cache:Record<string,Post>;onLoaded:(p:Post[])=>void;onPost:(p:Post)=>void;onProfile:(id:string)=>void;onFollow:(p:Person)=>void;followPending:string|null}){
 const [results,setResults]=useState<SearchResults>({people:[],posts:[]}),[recent,setRecent]=useState<string[]>(()=>{if(typeof window==='undefined')return [];try{const stored=JSON.parse(localStorage.getItem('rstmc-recent-searches')||'[]');return Array.isArray(stored)?stored.filter((item):item is string=>typeof item==='string').slice(0,8):[];}catch{return [];}}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!query.trim())return;const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);setError('');void request<SearchResults>('/api/social?search='+encodeURIComponent(query.trim()),undefined,controller.signal).then(r=>{setResults(r);onLoaded(r.posts);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},260);return()=>{window.clearTimeout(timer);controller.abort();};},[query,retry,onLoaded]);
 const changeQuery=(value:string)=>{setQuery(value);if(!value.trim()){setResults({people:[],posts:[]});setLoading(false);setError('');}};
 const suggested=people.filter(p=>p.id!==meId).slice(0,6),accounts=(query?results.people:suggested).map(p=>personCache[p.id]||p);
 return <section className="discovery-view search-view"><div className="section-heading"><span className="eyebrow">People / Places / Moments</span><h1>Search</h1><p>Find the people and perspectives that move you.</p></div><form className="search-field large" onSubmit={e=>{e.preventDefault();remember(query,setRecent);(e.currentTarget.querySelector('input') as HTMLInputElement)?.blur();}}><SearchIcon size={21}/><input aria-label="Search accounts, posts and hashtags" placeholder="Search accounts, posts, #hashtags…" value={query} onChange={e=>changeQuery(e.target.value)} autoComplete="off"/>{query&&<IconButton label="Clear search" onClick={()=>changeQuery('')}><X size={18}/></IconButton>}</form>
 {!query&&recent.length>0&&<div className="recent-searches"><div className="subheading"><h2>Recent searches</h2><button className="text-action" onClick={()=>{localStorage.removeItem('rstmc-recent-searches');setRecent([]);}}>Clear all</button></div><div className="recent-chips">{recent.map(term=><button key={term} onClick={()=>setQuery(term)}><Clock3 size={15}/>{term}</button>)}</div></div>}
 {error?<div className="inline-error" role="alert">{error}<button className="secondary-button" onClick={()=>setRetry(v=>v+1)}>Retry</button></div>:<>{loading&&<div className="search-loading" aria-label="Searching"><span/><span/><span/></div>}{!loading&&<><div className="subheading"><h2>{query?'Accounts':'Suggested people'}</h2><span>{query&&accounts.length?accounts.length+' found':''}</span></div><div className="people-results">{accounts.filter(p=>p.id!==meId).map(p=><div className="person-result" key={p.id}><Avatar person={p} size={46} onClick={()=>{remember(query,setRecent);onProfile(p.id);}}/><button className="person-detail" onClick={()=>{remember(query,setRecent);onProfile(p.id);}}><strong>{p.username}</strong><span>{p.name}{p.is_demo?' · Sample profile':''}</span></button><button className={'follow-button '+(p.followed?'following':'')} disabled={followPending===p.id} onClick={()=>onFollow(p)}>{followPending===p.id?<Busy/>:p.followed?'Following':'Follow'}</button></div>)}</div>{query&&<><div className="subheading"><h2>Moments</h2><span>{results.posts.length?results.posts.length+' found':''}</span></div><PostGrid variant="explore" posts={results.posts.map(p=>cache[p.id]||p)} onPost={p=>{remember(query,setRecent);onPost(p);}} empty={accounts.length?'No posts matched that search.':'No accounts or posts found. Try another search.'}/></>}</>}</>}
 </section>;
}
export function ExplorePage({category,setCategory,cache,onLoaded,onPost,onSearch}:{category:string;setCategory:(v:string)=>void;cache:Record<string,Post>;onLoaded:(p:Post[])=>void;onPost:(p:Post)=>void;onSearch:()=>void}){
 const [items,setItems]=useState<Post[]>([]),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[hasMore,setHasMore]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);const offset=useRef(0);
 useEffect(()=>{const controller=new AbortController();offset.current=0;void request<Post[]>('/api/social?explore=1&category='+encodeURIComponent(category),undefined,controller.signal).then(batch=>{setItems(batch);onLoaded(batch);offset.current=batch.length;setHasMore(batch.length===24);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[category,retry,onLoaded]);
 const changeCategory=(value:string)=>{setCategory(value);setLoading(true);setError('');setItems([]);};
 const next=async()=>{if(more)return;setMore(true);setError('');try{const batch=await request<Post[]>('/api/social?explore=1&category='+encodeURIComponent(category)+'&offset='+offset.current);setItems(list=>[...list,...batch.filter(p=>!list.some(q=>q.id===p.id))]);onLoaded(batch);offset.current+=batch.length;setHasMore(batch.length===24);}catch(e){setError((e as Error).message);}finally{setMore(false);}};
 return <section className="discovery-view explore-view"><div className="section-heading"><span className="eyebrow">A fresh perspective</span><h1>Explore</h1><p>A different perspective, every scroll.</p></div><button className="search-field explore-search" onClick={onSearch}><SearchIcon size={19}/><span>Find people, places and hashtags</span><ArrowUpRight size={17}/></button><Tabs value={category} onValueChange={changeCategory}><TabsList className="category-tabs">{categories.map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs>
 {loading?<div className="grid-skeleton" aria-label="Loading explore"><span/><span/><span/><span/><span/><span/></div>:error&&!items.length?<Empty icon={<Compass/>} heading="Explore couldn’t load" body={error} action={<button className="primary-button" onClick={()=>{setLoading(true);setError('');setRetry(v=>v+1);}}><RefreshCw size={16}/>Retry</button>}/>:<><PostGrid variant="explore" posts={items.map(p=>cache[p.id]||p)} onPost={onPost} empty="Nothing in this category yet. Try another perspective."/>{hasMore&&<div className="load-more"><button className="secondary-button" disabled={more} onClick={()=>void next()}>{more?<Busy/>:'Show more moments'}</button></div>}{error&&<div className="inline-error" role="alert">{error}<button className="secondary-button" onClick={()=>void next()}>Retry</button></div>}</>}
 </section>;
}
