"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {Send,Search,SquarePen,ArrowLeft,Bookmark,Smile,Check} from 'lucide-react';
import {Avatar,Empty,IconButton,Busy,request,timeAgo} from './common';
import {toast} from 'sonner';
import type {Person,Message} from '@/lib/types';

export function Messages({me,people,initialRecipient,onProfile}:{me:Person;people:Person[];initialRecipient:string|null;onProfile:(id:string)=>void}){
 const [recipient,setRecipient]=useState(initialRecipient||me.id),[query,setQuery]=useState(''),[searchResults,setSearchResults]=useState<Person[]>([]),[body,setBody]=useState(''),[messages,setMessages]=useState<Message[]>([]),[inbox,setInbox]=useState<Message[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[mobileChat,setMobileChat]=useState(!!initialRecipient),[error,setError]=useState('');
 const content=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),queryInput=useRef<HTMLInputElement>(null),sequence=useRef(0),stick=useRef(true),lock=useRef(false);
 const person=[me,...people,...searchResults].find(p=>p.id===recipient)||me;
 const load=useCallback(async()=>{const version=++sequence.current;try{const [items,all]=await Promise.all([request<Message[]>('/api/social?messages='+encodeURIComponent(recipient)),request<Message[]>('/api/social?inbox=1')]);if(version!==sequence.current)return;setMessages(prev=>[...items,...prev.filter(m=>m.id.startsWith('pending:'))]);setInbox(all);setError('');if(document.visibilityState==='visible'&&(window.innerWidth>700||mobileChat))void request('/api/social',{action:'read_messages',id:recipient}).catch(()=>{});}catch(e){if(version===sequence.current)setError((e as Error).message);}finally{if(version===sequence.current)setLoading(false);}},[recipient,mobileChat]);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void load();});const timer=window.setInterval(()=>{if(document.visibilityState==='visible'&&!lock.current)void load();},7000);return()=>{active=false;sequence.current++;window.clearInterval(timer);};},[load]);
 useEffect(()=>{if(stick.current&&content.current)content.current.scrollTop=content.current.scrollHeight;},[messages.length,recipient]);
 useEffect(()=>{if(!query.trim())return;const controller=new AbortController();const timer=window.setTimeout(()=>{void request<Person[]>('/api/social?accounts='+encodeURIComponent(query.trim()),undefined,controller.signal).then(setSearchResults).catch(()=>{});},260);return()=>{controller.abort();window.clearTimeout(timer);};},[query]);
 const select=(id:string)=>{if(recipient!==id){sequence.current++;setRecipient(id);setBody('');setMessages([]);setLoading(true);setError('');stick.current=true;}setMobileChat(true);};
 const send=async()=>{const text=body.trim();if(!text||lock.current)return;lock.current=true;setBusy(true);setBody('');const temp='pending:'+crypto.randomUUID();const optimistic:Message={id:temp,sender_id:me.id,recipient_id:recipient,body:text,created_at:Date.now(),read_at:null};setMessages(list=>[...list,optimistic]);stick.current=true;try{const saved=await request<Message>('/api/social',{action:'message',id:recipient,body:text});setMessages(list=>list.map(m=>m.id===temp?saved:m));setInbox(list=>[saved,...list]);}catch(e){setMessages(list=>list.filter(m=>m.id!==temp));setBody(v=>v||text);toast.error((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 const base=[me,...people.filter(p=>p.id!==me.id&&!p.is_demo),...searchResults.filter(p=>p.id!==me.id&&!p.is_demo)];const contacts=base.filter((p,i)=>base.findIndex(x=>x.id===p.id)===i).filter(p=>query?(p.name+' '+p.username).toLowerCase().includes(query.toLowerCase()):p.id===me.id||inbox.some(m=>m.sender_id===p.id||m.recipient_id===p.id)).sort((a,b)=>{const last=(p:Person)=>inbox.find(m=>m.sender_id===p.id||m.recipient_id===p.id)?.created_at||0;return last(b)-last(a);});
 return <div className={'messages-layout '+(mobileChat?'show-chat':'')}><aside className="conversation-list"><header><div><span className="eyebrow">Your circle</span><h1>Messages</h1></div><IconButton label="Find someone to message" onClick={()=>queryInput.current?.focus()}><SquarePen size={21}/></IconButton></header><label className="search-field"><Search size={18}/><input ref={queryInput} placeholder="Search people" aria-label="Search conversations" value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value.trim())setSearchResults([]);}}/></label><h3>{query?'People':'Conversations'}</h3><div className="conversation-entries">{contacts.map(p=>{const last=inbox.find(m=>p.id===me.id?m.sender_id===me.id&&m.recipient_id===me.id:m.sender_id===p.id||m.recipient_id===p.id);const unread=p.id!==me.id&&inbox.some(m=>m.sender_id===p.id&&m.recipient_id===me.id&&!m.read_at);return <button key={p.id} className={'conversation '+(recipient===p.id?'selected':'')+(unread?' unread':'')} onClick={()=>select(p.id)}><Avatar person={p} size={48}/><span><strong>{p.id===me.id?'Saved messages':p.username}</strong><small>{last?last.body:p.id===me.id?'Notes, links and little reminders':'Start a conversation'}</small></span>{last&&<time>{timeAgo(last.created_at)}</time>}{unread&&<i aria-label="Unread messages"/>}</button>;})}{!contacts.length&&<div className="no-results">{query?'No members found.':'No conversations yet. Search for a member to say hello.'}</div>}</div><p className="messages-note">Private conversations are only visible to their participants. Sample profiles don’t receive messages.</p></aside>
 <section className="chat-panel"><header><IconButton className="chat-back" label="Back to conversations" onClick={()=>setMobileChat(false)}><ArrowLeft/></IconButton><Avatar person={person} size={42}/><button onClick={()=>onProfile(person.id)}><strong>{person.id===me.id?'Saved messages':person.username}</strong><span>{person.id===me.id?'Only you can see these':'View profile'}</span></button></header><div className="chat-content" ref={content} onScroll={e=>{const el=e.currentTarget;stick.current=el.scrollHeight-el.scrollTop-el.clientHeight<90;}}>{loading?<div className="message-skeletons" aria-label="Loading conversation"><span/><span/><span/></div>:messages.length?messages.map(m=><div key={m.id} className={'message-row '+(m.sender_id===me.id?'outgoing':'incoming')}><p>{m.body.split(/(https?:\/\/[^\s]+)/g).map((text,i)=>/^https?:\/\//.test(text)?<a key={i} href={text} target="_blank" rel="noopener noreferrer" className="message-link">{text}</a>:text)}</p><time title={new Date(m.created_at).toLocaleString()}>{m.id.startsWith('pending:')?'Sending…':<>{new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}{m.sender_id===me.id&&<Check size={12} aria-label="Sent"/>}</>}</time></div>):<Empty icon={person.id===me.id?<Bookmark/>:<Send/>} heading={person.id===me.id?'A little space for yourself':'Say hello'} body={person.id===me.id?'Save a thought, a link or a reminder. It’ll be here when you need it.':'Start your conversation with '+person.name+'.'}/>}{error&&<div className="inline-error" role="alert">{error}<button onClick={()=>void load()} className="secondary-button">Retry</button></div>}</div><form className="message-compose" onSubmit={e=>{e.preventDefault();void send();}}><IconButton label="Add a smile" onClick={()=>{setBody(v=>v+' 😊');input.current?.focus();}}><Smile size={21}/></IconButton><input ref={input} aria-label="Write a message" placeholder="Message…" value={body} maxLength={2000} onChange={e=>setBody(e.target.value)}/><button aria-label="Send message" className="message-send" disabled={!body.trim()||busy}>{busy?<Busy/>:<Send size={18}/>}</button></form></section></div>;
}
