"use client";
import {useRef,useState,type FormEvent,type RefObject} from 'react';
import {Heart,MessageCircle,Send,Bookmark,MoreHorizontal,Smile,Link as LinkIcon,EyeOff,UserRound,Trash2} from 'lucide-react';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {Avatar,IconButton,count,timeAgo,Busy} from './common';
import {MediaCarousel} from './media';
import type {Post,Person,Comment} from '@/lib/types';

export type PostActions={react:(p:Post,kind:'like'|'save'|'hidden'|'seen',active:boolean)=>Promise<void>;comment:(p:Post,body:string)=>Promise<Comment>;openPost:(p:Post)=>void;openProfile:(id:string)=>void;searchTag:(tag:string)=>void;share:(p:Post)=>void;deletePost:(p:Post)=>void;copyLink:(p:Post)=>void;me:Person|null};
export function PostHeader({post:p,actions:a,menu=true}:{post:Post;actions:PostActions;menu?:boolean}){return <header className="post-header"><Avatar person={p.author} size={42} onClick={()=>a.openProfile(p.author_id)}/><div className="post-user"><div><button className="username" onClick={()=>a.openProfile(p.author_id)}>{p.author.username}</button><span className="post-time"> · {timeAgo(p.created_at)}</span></div>{(p.location||p.author.name)&&<span className="post-location">{p.location||p.author.name}</span>}</div>
  {menu&&<DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label="Post options"><MoreHorizontal/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="social-menu"><DropdownMenuItem onClick={()=>a.openProfile(p.author_id)}><UserRound/>Go to profile</DropdownMenuItem><DropdownMenuItem onClick={()=>a.copyLink(p)}><LinkIcon/>Copy link</DropdownMenuItem><DropdownMenuItem onClick={()=>void a.react(p,'save',!p.saved)}><Bookmark/>{p.saved?'Remove from saved':'Save post'}</DropdownMenuItem><DropdownMenuSeparator/>{a.me?.id===p.author_id?<DropdownMenuItem variant="destructive" onClick={()=>a.deletePost(p)}><Trash2/>Delete post</DropdownMenuItem>:<DropdownMenuItem onClick={()=>void a.react(p,'hidden',true)}><EyeOff/>Hide post</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>}
 </header>;}
export function PostToolbar({post:p,actions:a,onComment}:{post:Post;actions:PostActions;onComment:()=>void}){const [pending,setPending]=useState('');const lock=useRef(false);const react=async(kind:'like'|'save',active:boolean)=>{if(lock.current)return;lock.current=true;setPending(kind);try{await a.react(p,kind,active);}finally{lock.current=false;setPending('');}};return <div className="post-actions"><IconButton label={p.liked?'Unlike':'Like'} className="heart-action" active={!!p.liked} disabled={!!pending} onClick={()=>void react('like',!p.liked)}><Heart fill={p.liked?'currentColor':'none'}/></IconButton><IconButton label="View comments" onClick={onComment}><MessageCircle/></IconButton><IconButton label="Share post" onClick={()=>a.share(p)}><Send/></IconButton><IconButton className="save-button" label={p.saved?'Unsave post':'Save post'} active={!!p.saved} disabled={!!pending} onClick={()=>void react('save',!p.saved)}><Bookmark fill={p.saved?'currentColor':'none'}/></IconButton></div>;}
export function PostCaption({post:p,actions:a}:{post:Post;actions:PostActions}){const [more,setMore]=useState(false);const shortened=!more&&p.caption.length>180;const text=shortened?p.caption.slice(0,180):p.caption;return <p className="post-caption"><button className="username" onClick={()=>a.openProfile(p.author_id)}>{p.author.username}</button>{' '}{text.split(/(#[\p{L}\p{N}_]+)/u).map((part,i)=>part.startsWith('#')?<button key={i} className="hashtag" onClick={()=>a.searchTag(part)}>{part}</button>:part)}{shortened&&<>… <button className="caption-more" onClick={()=>setMore(true)}>more</button></>}</p>;}
export function CommentComposer({post,actions,onSubmitted,inputRef}:{post:Post;actions:PostActions;onSubmitted?:(comment:Comment)=>void;inputRef?:RefObject<HTMLInputElement|null>}){const [body,setBody]=useState(''),[sending,setSending]=useState(false);const localInput=useRef<HTMLInputElement>(null),lock=useRef(false);const input=inputRef||localInput;const submit=async(e:FormEvent)=>{e.preventDefault();if(!body.trim()||lock.current)return;lock.current=true;setSending(true);try{const created=await actions.comment(post,body.trim());setBody('');onSubmitted?.(created);}catch{}finally{lock.current=false;setSending(false);}};return <form onSubmit={submit} className="comment-form"><IconButton label="Add a smile" onClick={()=>{setBody(v=>v+' 😊');input.current?.focus();}}><Smile size={21}/></IconButton><input ref={input} aria-label="Add a comment" value={body} maxLength={1000} onChange={e=>setBody(e.target.value)} placeholder="Add a comment…"/><button className="text-action" disabled={!body.trim()||sending}>{sending?<Busy/>:'Post'}</button></form>;}
export function PostCard({post:p,actions:a}:{post:Post;actions:PostActions}){
  const [heart,setHeart]=useState(false);const like=()=>{if(!a.me){void a.react(p,'like',true);return;}if(!p.liked)void a.react(p,'like',true);setHeart(true);window.setTimeout(()=>setHeart(false),750);};
  return <article className="post-card" aria-label={'Post by '+p.author.username}><PostHeader post={p} actions={a}/><div className="post-media"><MediaCarousel post={p} onDoubleLike={like}/>{heart&&<Heart className="double-heart" fill="currentColor" aria-hidden="true"/>}</div><div className="post-body"><PostToolbar post={p} actions={a} onComment={()=>a.openPost(p)}/><div className="like-count" aria-live="polite">{count(p.likes)} {p.likes===1?'like':'likes'}</div><PostCaption post={p} actions={a}/>{p.comment_preview&&<button className="comment-preview" onClick={()=>a.openPost(p)}><strong>{p.comment_preview.username}</strong> {p.comment_preview.body}</button>}<button className="view-comments" onClick={()=>a.openPost(p)}>{p.comment_count?(p.comment_count===1?'View 1 comment':'View all '+p.comment_count+' comments'):'Start the conversation'}</button><CommentComposer post={p} actions={a}/></div></article>;
}
