"use client";
import {useEffect,useState} from 'react';
import {Grid3X3,Film,Bookmark,Camera,Tag,Link2,Share2,MoreHorizontal,Plus,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Avatar,Busy,Empty,request,count} from './common';
import {PostGrid} from './discovery';
import type {Person,Post} from '@/lib/types';

export function ProfilePage({profile,me,tab,setTab,posts,cache,onLoaded,onPost,onStory,onCreate,onEdit,onFollow,followPending,onMessage,onRelations,onShare,highlightVersion,now}:{profile:Person;me:Person|null;tab:string;setTab:(v:string)=>void;posts:Post[];cache:Record<string,Post>;onLoaded:(items:Post[])=>void;onPost:(p:Post)=>void;onStory:(items:Post[],index:number)=>void;onCreate:()=>void;onEdit:()=>void;onFollow:(p:Person)=>void;followPending:string|null;onMessage:()=>void;onRelations:(kind:'followers'|'following')=>void;onShare:()=>void;highlightVersion:number;now:number}){
 const own=profile.id===me?.id;
 return <section className="profile-view"><div className="profile-top"><Avatar person={profile} size={138}/><div className="profile-info"><div className="profile-title"><div><span className="eyebrow">{own?'Your space':'Profile'}</span><h1>{profile.username}</h1></div><div className="profile-buttons">{own?<><button className="secondary-button" onClick={onEdit}>Edit profile</button><button className="secondary-button" onClick={onShare}><Share2 size={16}/>Share</button></>:<><button className={'primary-button '+(profile.followed?'following':'')} disabled={followPending===profile.id} onClick={()=>onFollow(profile)}>{followPending===profile.id?<Busy/>:profile.followed?'Following':'Follow'}</button><button className="secondary-button" onClick={onMessage}>Message</button><DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button profile-more" aria-label="More profile actions"><MoreHorizontal/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="social-menu"><DropdownMenuItem onClick={onShare}><Link2/>Share profile</DropdownMenuItem></DropdownMenuContent></DropdownMenu></>}</div></div><div className="profile-stats"><span><strong>{count(profile.post_count)}</strong> posts</span><button onClick={()=>onRelations('followers')}><strong>{count(profile.followers)}</strong> followers</button><button onClick={()=>onRelations('following')}><strong>{count(profile.following)}</strong> following</button></div><strong className="profile-name">{profile.name}</strong><p className="profile-bio">{profile.bio||'A little space to share your world.'}</p>{profile.website&&<a className="profile-website" href={profile.website} target="_blank" rel="noopener noreferrer"><Link2 size={15}/>{profile.website.replace(/^https?:\/\//,'').replace(/\/$/,'')}</a>}{!!profile.is_demo&&<span className="sample-label">Sample profile</span>}</div></div>
 <ProfileHighlights key={profile.id} id={profile.id} own={own} posts={posts} cache={cache} version={highlightVersion} now={now} onLoaded={onLoaded} onStory={onStory}/>
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="profile-tabs"><TabsTrigger value="posts"><Grid3X3 size={17}/>Posts</TabsTrigger><TabsTrigger value="reels"><Film size={17}/>Reels</TabsTrigger><TabsTrigger value="tagged"><Tag size={17}/>Tagged</TabsTrigger>{own&&<TabsTrigger value="saved"><Bookmark size={17}/>Saved</TabsTrigger>}</TabsList></Tabs>
 <ProfileGrid key={profile.id+':'+tab} id={profile.id} tab={tab} posts={posts} cache={cache} onLoaded={onLoaded} onPost={onPost} onCreate={onCreate} own={own}/></section>;
}
export function ProfileHighlights({id,own,posts,cache,version,now,onLoaded,onStory}:{id:string;own:boolean;posts:Post[];cache:Record<string,Post>;version:number;now:number;onLoaded:(items:Post[])=>void;onStory:(items:Post[],index:number)=>void}){
 const [items,setItems]=useState<Post[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();void request<Post[]>('/api/social?highlights='+encodeURIComponent(id),undefined,controller.signal).then(result=>{setItems(result);onLoaded(result);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[id,version,retry,onLoaded]);
 const active=posts.filter(p=>p.kind==='story'&&p.author_id===id&&(!p.expires_at||p.expires_at>now));const list=items.map(p=>cache[p.id]||p);
 if(!own&&!list.length)return null;
 return <div className="profile-highlights"><div className="subheading"><h2>Highlights</h2><span>Stories worth keeping</span></div>{loading&&!items.length?<div className="highlight-skeletons" aria-label="Loading highlights"><span/><span/><span/></div>:<div className="highlights-rail">{list.map((p,i)=><button className="highlight-item" key={p.id} onClick={()=>onStory(list,i)}><span className="highlight-cover">{p.media_type==='video'?<Film size={26}/>:<img src={p.media[0]} alt="" loading="lazy"/>}</span><span>{p.location||p.caption.split(/[\s.!?]/)[0]||'Moment'}</span></button>)}{own&&active.length>0&&<button className="highlight-item" onClick={()=>onStory(active,0)}><span className="highlight-add"><Plus size={26}/></span><span>Add highlight</span></button>}{own&&!list.length&&!active.length&&<div className="highlight-empty"><Camera size={21}/>Stories you add to highlights will stay here.</div>}</div>}{error&&<div className="inline-error" role="alert">{error}<button onClick={()=>{setError('');setLoading(true);setRetry(v=>v+1);}}><RefreshCw size={15}/>Retry</button></div>}</div>;
}
export function ProfileGrid({id,tab,posts,cache,onLoaded,onPost,onCreate,own}:{id:string;tab:string;posts:Post[];cache:Record<string,Post>;onLoaded:(items:Post[])=>void;onPost:(p:Post)=>void;onCreate:()=>void;own:boolean}){
 const [loaded,setLoaded]=useState<Post[]|null>(null),[error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();const url=tab==='saved'?'/api/social?saved=1':tab==='tagged'?'/api/social?tagged='+encodeURIComponent(id):'/api/social?profile='+encodeURIComponent(id);void request<Post[]>(url,undefined,controller.signal).then(items=>{setLoaded(items);onLoaded(items);}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message);});return()=>controller.abort();},[id,tab,retry,onLoaded]);
 const filtered=(loaded||posts).map(p=>cache[p.id]||p).filter(p=>p.kind!=='story'&&(tab==='saved'?!!p.saved:tab==='tagged'?p.tagged_users?.includes(id):tab==='reels'?p.author_id===id&&p.kind==='reel':p.author_id===id&&p.kind==='post'));
 if(error&&!filtered.length)return <Empty icon={<Camera/>} heading="Moments couldn’t load" body={error} action={<button className="primary-button" onClick={()=>{setLoaded(null);setError('');setRetry(v=>v+1);}}>Retry</button>}/>;
 if(loaded===null&&!filtered.length)return <div className="grid-skeleton" aria-label="Loading posts"><span/><span/><span/><span/><span/><span/></div>;
 if(filtered.length)return <PostGrid posts={filtered} onPost={onPost}/>;
 const heading=tab==='saved'?'Keep a little inspiration':tab==='tagged'?'Nothing tagged yet':tab==='reels'?'No reels yet':own?'Share your first moment':'No posts yet';const body=tab==='saved'?'Bookmark a post to keep it here. Only you can see this.':tab==='tagged'?'Posts that tag this account will appear here.':own?'Your photos and videos deserve a place here.':'Their next moment will appear here.';
 return <Empty icon={tab==='saved'?<Bookmark/>:<Camera/>} heading={heading} body={body} action={own&&tab!=='tagged'&&<button className="primary-button" onClick={onCreate}>{tab==='saved'?'Explore moments':'Create a post'}</button>}/>;
}
