"use client";
import {useEffect,useRef,useState} from 'react';
import {Heart,MessageCircle,Send,Bookmark,Film,ChevronDown,ChevronUp,RefreshCw} from 'lucide-react';
import {Avatar,IconButton,Empty,Busy,count,request} from './common';
import {VideoPlayer} from './media';
import type {Post} from '@/lib/types';
import type {PostActions} from './post-card';

export function Reels({posts,cache,actions,onCreate,onLoaded,suspended}:{posts:Post[];cache:Record<string,Post>;actions:PostActions;onCreate:()=>void;onLoaded:(posts:Post[])=>void;suspended:boolean}){
 const [items,setItems]=useState<Post[]>(posts.filter(p=>p.kind==='reel')),[current,setCurrent]=useState(0),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[error,setError]=useState(''),[hasMore,setHasMore]=useState(false);
 const scroll=useRef<HTMLDivElement>(null),offset=useRef(0);
 const load=async(reset:boolean)=>{if(!reset&&more)return;if(reset){setLoading(true);setError('');}else setMore(true);try{const batch=await request<Post[]>('/api/social?reels=1&offset='+(reset?0:offset.current));if(reset)setItems(batch);else setItems(list=>[...list,...batch.filter(p=>!list.some(q=>q.id===p.id))]);offset.current=(reset?0:offset.current)+batch.length;setHasMore(batch.length===20);onLoaded(batch);}catch(e){setError((e as Error).message);}finally{setLoading(false);setMore(false);}};
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)void load(true);});return()=>{active=false;};/* Fetch the real video collection on entry. */},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{const root=scroll.current;if(!root||!items.length)return;const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&entry.intersectionRatio>=.65)setCurrent(Number((entry.target as HTMLElement).dataset.index));}},{root,threshold:[.65,.85]});root.querySelectorAll<HTMLElement>('.reel-shell').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[items.length]);
 const step=(next:number)=>{const target=Math.min(items.length-1,Math.max(0,current+next));scroll.current?.querySelectorAll<HTMLElement>('.reel-shell')[target]?.scrollIntoView({behavior:'smooth',block:'start'});};
 if(loading&&!items.length)return <div className="reels-view"><div className="section-heading"><h1>Reels</h1></div><div className="reel-skeleton" aria-label="Loading reels"><Busy/></div></div>;
 if(error&&!items.length)return <Empty icon={<Film/>} heading="Reels couldn’t load" body={error} action={<button className="primary-button" onClick={()=>void load(true)}><RefreshCw size={16}/>Retry</button>}/>;
 if(!items.length)return <Empty icon={<Film/>} heading="Make it a moving moment" body="Share a short video and start the reel collection." action={<button className="primary-button" onClick={onCreate}>Create a reel</button>}/>;
 return <section className="reels-view"><div className="reels-heading"><div><span className="eyebrow">Watch / Discover</span><h1>Reels</h1></div><button className="secondary-button" onClick={onCreate}>Create reel</button></div><div className="reel-stage"><div className="reel-scroll" ref={scroll} aria-label="Reel videos">{items.map((item,i)=><div key={item.id} className="reel-shell" data-index={i}><Reel post={cache[item.id]||posts.find(p=>p.id===item.id)||item} actions={actions} active={i===current&&!suspended}/></div>)}{hasMore&&<div className="reel-load"><button className="secondary-button" disabled={more} onClick={()=>void load(false)}>{more?<Busy/>:'Load more reels'}</button></div>}{error&&<div className="inline-error" role="alert">{error}<button onClick={()=>void load(false)}>Retry</button></div>}</div><div className="reel-navigation"><IconButton label="Previous reel" disabled={current===0} onClick={()=>step(-1)}><ChevronUp/></IconButton><span>{current+1} / {items.length}</span><IconButton label="Next reel" disabled={current===items.length-1} onClick={()=>step(1)}><ChevronDown/></IconButton></div></div></section>;
}
function Reel({post:p,actions:a,active}:{post:Post;actions:PostActions;active:boolean}){const [pending,setPending]=useState(false),lock=useRef(false);const react=async(kind:'like'|'save',value:boolean)=>{if(lock.current)return;lock.current=true;setPending(true);try{await a.react(p,kind,value);}finally{lock.current=false;setPending(false);}};return <div className="reel-player"><VideoPlayer src={p.media[0]} label={p.caption||'Reel by '+p.author.username} autoPlay active={active} className="reel-video"/><div className="reel-info"><div className="user-line"><Avatar person={p.author} size={38} onClick={()=>a.openProfile(p.author_id)}/><button className="username" onClick={()=>a.openProfile(p.author_id)}>{p.author.username}</button></div><p>{p.caption}</p><small>{p.author.is_demo?'Sample reel':'Original video'}</small></div><div className="reel-actions"><IconButton label={p.liked?'Unlike reel':'Like reel'} active={!!p.liked} disabled={pending} onClick={()=>void react('like',!p.liked)}><Heart fill={p.liked?'currentColor':'none'}/></IconButton><span>{count(p.likes)}</span><IconButton label="View comments" onClick={()=>a.openPost(p)}><MessageCircle/></IconButton><span>{p.comment_count}</span><IconButton label="Share reel" onClick={()=>a.share(p)}><Send/></IconButton><IconButton label={p.saved?'Unsave reel':'Save reel'} active={!!p.saved} disabled={pending} onClick={()=>void react('save',!p.saved)}><Bookmark fill={p.saved?'currentColor':'none'}/></IconButton></div></div>;}
