"use client";
import {useState,useEffect,useRef,useCallback,useEffectEvent} from 'react';
import {Plus,ChevronLeft,ChevronRight,X,Pause,Play,Volume2,VolumeX} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Avatar,IconButton,timeAgo} from './common';
import type {Person,Post} from '@/lib/types';
export function Stories({stories,me,onOpen,onCreate}:{stories:Post[];me:Person|null;onOpen:(i:number)=>void;onCreate:()=>void}){const rail=useRef<HTMLDivElement>(null);return <div className="stories-wrapper"><div className="stories" ref={rail}><button className="story" onClick={onCreate}><span className="your-story"><Avatar person={me} size={68}/><span className="story-plus"><Plus size={15}/></span></span><span>Your story</span></button>{stories.map((p,i)=><button className={'story '+(p.seen?'story-seen':'')} key={p.id} onClick={()=>onOpen(i)}><Avatar person={p.author} size={72} ring/><span>{p.author.username}</span></button>)}</div><IconButton className="stories-next" label="More stories" onClick={()=>rail.current?.scrollBy({left:280,behavior:'smooth'})}><ChevronRight size={18}/></IconButton></div>;}
export function StoryViewer({stories,start,onClose,onSeen,onProfile}:{stories:Post[];start:number;onClose:()=>void;onSeen:(p:Post)=>void;onProfile:(id:string)=>void}){
 const [index,setIndex]=useState(start);
 const post=stories[index];
 const next=useCallback(()=>{if(index<stories.length-1)setIndex(index+1);else onClose();},[index,stories.length,onClose]);
 useEffect(()=>{if(!post)onClose();},[post,onClose]);
 if(!post)return null;
 return <StoryPlayback key={post.id} stories={stories} index={index} setIndex={setIndex} post={post} next={next} onClose={onClose} onSeen={onSeen} onProfile={onProfile}/>;
}
function StoryPlayback({stories,index,setIndex,post,next,onClose,onSeen,onProfile}:{stories:Post[];index:number;setIndex:React.Dispatch<React.SetStateAction<number>>;post:Post;next:()=>void;onClose:()=>void;onSeen:(p:Post)=>void;onProfile:(id:string)=>void}){
 const [paused,setPaused]=useState(false),[muted,setMuted]=useState(true),[progress,setProgress]=useState(0),[ready,setReady]=useState(false);
 const video=useRef<HTMLVideoElement>(null),elapsed=useRef(0),holdPaused=useRef(false);
 const markSeen=useEffectEvent(()=>onSeen(post));
 useEffect(()=>{markSeen();},[post.id]);
 useEffect(()=>{if(paused||!ready||post.media_type==='video')return;const timer=setInterval(()=>{elapsed.current+=50;setProgress(elapsed.current/6000);if(elapsed.current>=6000)next();},50);return ()=>clearInterval(timer);},[paused,ready,post.id,next,post.media_type]);
 useEffect(()=>{if(video.current){if(paused)video.current.pause();else void video.current.play().catch(()=>setPaused(true));}},[paused,post.id]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')setIndex(v=>Math.max(0,v-1));if(e.key===' '){e.preventDefault();setPaused(v=>!v);}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle);},[next,setIndex]);
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="story-dialog" showCloseButton={false}><DialogTitle className="sr-only">Story by {post.author.username}</DialogTitle><DialogDescription className="sr-only">Use the arrow keys for the next or previous story. Space pauses playback.</DialogDescription><div className="story-fullscreen"><span className="story-brand">RSTMC<span>.</span></span><IconButton className="close-story" label="Close story" onClick={onClose}><X/></IconButton><div className="story-player" onPointerDown={e=>{if((e.target as Element).closest('button'))return;holdPaused.current=paused;setPaused(true);}} onPointerUp={e=>{if(!(e.target as Element).closest('button'))setPaused(holdPaused.current);}} onPointerCancel={()=>setPaused(holdPaused.current)}><div className="story-progress">{stories.map((p,i)=><span key={p.id}><i style={{width:(i<index?100:i===index?progress*100:0)+'%'}}/></span>)}</div><header><Avatar person={post.author} size={36}/><button onClick={()=>{onClose();onProfile(post.author_id);}}>{post.author.username}</button><span>{timeAgo(post.created_at)}</span><div className="story-tools"><IconButton label={paused?'Play story':'Pause story'} onClick={()=>setPaused(v=>!v)}>{paused?<Play size={20}/>:<Pause size={20}/>}</IconButton>{post.media_type==='video'&&<IconButton label={muted?'Unmute story':'Mute story'} onClick={()=>setMuted(v=>!v)}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}</IconButton>}</div></header>
 {post.media_type==='video'?<video key={post.id} ref={video} src={post.media[0]} autoPlay muted={muted} playsInline onLoadedData={()=>setReady(true)} onTimeUpdate={e=>setProgress(e.currentTarget.currentTime/(e.currentTarget.duration||1))} onEnded={next}/>:<img key={post.id} src={post.media[0]} alt={post.caption||'Story photo'} onLoad={()=>setReady(true)}/>}
 <div className="story-tap previous" onClick={()=>setIndex(v=>Math.max(0,v-1))} aria-hidden="true"/><div className="story-tap next" onClick={next} aria-hidden="true"/>{post.caption&&<p className="story-caption">{post.caption}</p>}</div><IconButton className="story-prev" label="Previous story" disabled={index===0} onClick={()=>setIndex(index-1)}><ChevronLeft/></IconButton><IconButton className="story-next" label="Next story" onClick={next}><ChevronRight/></IconButton></div></DialogContent></Dialog>;
}
