'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {DEFAULT_APPEARANCE,NAV_ICONS,NAV_TARGETS,validateAppearance,type Appearance,type NavItem,type Palette} from '@/lib/appearance';
import {upload,request} from '@/components/social/common';
// max=7 marks the palette fields, which are the only six-digit hex colour inputs.
function Text({label,value,onChange,max=500,type='text'}:{label:string;value:string|number;onChange:(value:string)=>void;max?:number;type?:string}){return <label>{label}<span className="admin-input-suffix">{max===7?<span className="admin-color-swatch" style={{background:String(value)}} aria-hidden="true"/>:null}<input type={type} value={value} maxLength={max} onChange={e=>onChange(e.target.value)}/></span></label>;}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <label className="appearance-toggle admin-switch"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
export function AppearanceEditor({initial,localUploads}:{initial:Appearance;localUploads:boolean}){
 const router=useRouter();const [a,setA]=useState(initial),[pending,setPending]=useState(false),[message,setMessage]=useState('');
 const set=(patch:Partial<Appearance>)=>setA(current=>({...current,...patch}));
 const nav=(i:number,patch:Partial<NavItem>)=>setA(current=>({...current,nav:current.nav.map((n,index)=>i===index?{...n,...patch}:n)}));
 const move=(i:number,direction:number)=>{const items=[...a.nav];[items[i],items[i+direction]]=[items[i+direction],items[i]];set({nav:items});};
 async function image(file:File|undefined,field:'logoLight'|'logoDark'|'favicon'|'hero'){
  if(!file)return;setPending(true);setMessage('');
  try{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG, JPEG, WebP or GIF up to 2 MB. SVG uploads are not supported.');
   let url:string;if(localUploads){const form=new FormData();form.set('key',crypto.randomUUID());form.set('file',file);url=(await request<{url:string}>('/api/dev-upload',form)).url;}else url=(await upload(file)).url;
   if(field==='hero')setA(current=>({...current,hero:{...current.hero,image:url}}));else set({[field]:url});setMessage('Upload verified. Save appearance to publish it.');
  }catch(error){setMessage(error instanceof Error?error.message:'Upload failed.');}finally{setPending(false);}
 }
 return <form className="appearance-editor" onSubmit={async e=>{e.preventDefault();setPending(true);setMessage('');try{const value=validateAppearance(a);await request('/api/admin/appearance',{value});setMessage('Appearance published and audited. Reload the public site to see it.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not save.');}finally{setPending(false);}}}>
  <section className="admin-card admin-confirm"><h2>Brand & layout</h2><div className="admin-detail"><Text label="Site name" value={a.name} max={80} onChange={name=>set({name})}/><Text label="Wordmark" value={a.wordmark} max={30} onChange={wordmark=>set({wordmark})}/>
   <label>Default theme<select value={a.defaultTheme} onChange={e=>set({defaultTheme:e.target.value as Appearance['defaultTheme']})}>{['system','light','dark'].map(v=><option key={v}>{v}</option>)}</select></label>
   <label>Header position<select value={a.headerPosition} onChange={e=>set({headerPosition:e.target.value as Appearance['headerPosition']})}><option>fixed</option><option>static</option></select></label>
   <label>Desktop sidebar<select value={a.sidebarMode} onChange={e=>set({sidebarMode:e.target.value as Appearance['sidebarMode']})}>{['auto','compact','hidden'].map(v=><option key={v}>{v}</option>)}</select></label>
   <Text label="Corner radius (0–32 px)" value={a.radius} type="number" onChange={v=>set({radius:Number(v)})}/><Text label="Glass blur (0–40 px)" value={a.blur} type="number" onChange={v=>set({blur:Number(v)})}/></div>
   {(['logoLight','logoDark','favicon'] as const).map(field=><div key={field} className="admin-detail"><Text label={field==='logoLight'?'Light logo URL':field==='logoDark'?'Dark logo URL':'Favicon URL'} value={a[field]} max={100} onChange={v=>set({[field]:v})}/><label>Upload {field}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={pending} onChange={e=>void image(e.target.files?.[0],field)}/></label></div>)}<p className="admin-muted">Images: verified uploads, maximum 2 MB. Dark logo falls back to the light logo. Blank logos use the wordmark; blank favicon uses the bundled icon.</p>
  </section>
  <section className="admin-card"><h2>Light & dark palettes</h2><div className="admin-detail">{(['light','dark'] as const).map(mode=><fieldset key={mode} className="admin-confirm"><legend>{mode}</legend>{(Object.keys(a[mode]) as (keyof Palette)[]).map(key=><Text key={key} label={`${mode} ${key}`} value={a[mode][key]} max={7} onChange={v=>set({[mode]:{...a[mode],[key]:v}})}/>)}</fieldset>)}</div><p className="admin-muted">Six-digit hex colours only. Check text contrast in both themes before publishing.</p></section>
  <section className="admin-card admin-confirm"><h2>Announcement</h2><Toggle label="Show announcement" value={a.announcement.enabled} onChange={enabled=>set({announcement:{...a.announcement,enabled}})}/>{(['text','label','url'] as const).map(key=><Text key={key} label={'Announcement '+key} value={a.announcement[key]} onChange={v=>set({announcement:{...a.announcement,[key]:v}})}/>)}</section>
  <section className="admin-card admin-confirm"><h2>Hero banner</h2><Toggle label="Show hero" value={a.hero.enabled} onChange={enabled=>set({hero:{...a.hero,enabled}})}/>{(['title','text','image','label','url'] as const).map(key=><Text key={key} label={'Hero '+key} value={a.hero[key]} onChange={v=>set({hero:{...a.hero,[key]:v}})}/>) }<label>Upload hero image<input type="file" disabled={pending} accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>void image(e.target.files?.[0],'hero')}/></label></section>
  <section className="admin-card admin-confirm"><h2>Navigation builder</h2><p>Order is shared across sidebar, dock and header. Disable or remove an item to remove it from those surfaces. Up to 12 items, 6 enabled dock items, and 2 enabled header items. This is navigation control, not an API feature flag (Phase 5).</p>
   {a.nav.map((item,i)=><fieldset className="appearance-nav-row admin-confirm" key={item.id}><legend>{item.label||'Navigation item'}</legend><div className="admin-detail"><Text label="Navigation label" value={item.label} max={30} onChange={label=>nav(i,{label})}/><label>Icon<select value={item.icon} onChange={e=>nav(i,{icon:e.target.value as NavItem['icon']})}>{NAV_ICONS.map(icon=><option key={icon}>{icon}</option>)}</select></label><Text label="Target (view name, relative URL or HTTPS)" value={item.target} onChange={target=>nav(i,{target})}/><Text label="Badge" value={item.badge} max={8} onChange={badge=>nav(i,{badge})}/></div><div className="admin-action-grid">{(['enabled','sidebar','dock','header'] as const).map(key=><Toggle key={key} label={key} value={item[key]} onChange={v=>nav(i,{[key]:v})}/>)}</div><div className="admin-action-grid"><button type="button" className="admin-button" disabled={i===0} onClick={()=>move(i,-1)}>Move up</button><button type="button" className="admin-button" disabled={i===a.nav.length-1} onClick={()=>move(i,1)}>Move down</button><button type="button" className="admin-button" onClick={()=>set({nav:a.nav.filter((_,index)=>i!==index)})}>Remove item</button></div></fieldset>)}
   <button type="button" className="admin-button" disabled={a.nav.length>=12} onClick={()=>set({nav:[...a.nav,{id:'custom-'+crypto.randomUUID().slice(0,8),label:'New link',icon:'link',target:'https://example.com',enabled:false,sidebar:true,dock:false,header:false,badge:''}]})}>Add navigation item</button><p className="admin-muted">Built-in targets: {NAV_TARGETS.join(', ')}. A removed built-in target displays an unavailable state for direct hash links.</p>
  </section>
  <section className="admin-card admin-confirm"><h2>Public footer</h2><Toggle label="Show footer" value={a.footer.enabled} onChange={enabled=>set({footer:{...a.footer,enabled}})}/><Text label="Copyright / legal row" max={160} value={a.footer.copyright} onChange={copyright=>set({footer:{...a.footer,copyright}})}/>
   {a.footer.columns.map((column,index)=><fieldset className="admin-confirm appearance-nav-row" key={index}><Text label="Column heading" value={column.title} max={40} onChange={title=>set({footer:{...a.footer,columns:a.footer.columns.map((c,i)=>i===index?{...c,title}:c)}})}/>{column.links.map((link,j)=><div className="admin-detail" key={j}><Text label="Link label" value={link.label} max={50} onChange={label=>set({footer:{...a.footer,columns:a.footer.columns.map((c,i)=>i===index?{...c,links:c.links.map((l,k)=>k===j?{...l,label}:l)}:c)}})}/><Text label="Link URL" value={link.url} onChange={url=>set({footer:{...a.footer,columns:a.footer.columns.map((c,i)=>i===index?{...c,links:c.links.map((l,k)=>k===j?{...l,url}:l)}:c)}})}/><button type="button" className="admin-button" onClick={()=>set({footer:{...a.footer,columns:a.footer.columns.map((c,i)=>i===index?{...c,links:c.links.filter((_,k)=>k!==j)}:c)}})}>Remove link</button></div>)}<button type="button" className="admin-button" disabled={column.links.length>=6} onClick={()=>set({footer:{...a.footer,columns:a.footer.columns.map((c,i)=>i===index?{...c,links:[...c.links,{label:'New link',url:'/'}]}:c)}})}>Add footer link</button><button type="button" className="admin-button" onClick={()=>set({footer:{...a.footer,columns:a.footer.columns.filter((_,i)=>i!==index)}})}>Remove column</button></fieldset>)}
   <button type="button" className="admin-button" disabled={a.footer.columns.length>=3} onClick={()=>set({footer:{...a.footer,columns:[...a.footer.columns,{title:'New column',links:[]}]}})}>Add footer column</button>
  </section>
  <div className="admin-card admin-confirm"><p>Saving replaces the full appearance configuration. Reload before editing if another administrator has published changes.</p>{message&&<p role="status">{message}</p>}<div className="admin-action-grid"><button type="submit" className="admin-button admin-primary" disabled={pending}>{pending?'Working…':'Publish appearance'}</button><button type="button" className="admin-button" disabled={pending} onClick={()=>{setA(structuredClone(DEFAULT_APPEARANCE));setMessage('Defaults loaded into the form. Publish to apply them.');}}>Load defaults into form</button><a className="admin-button" href="/" target="_blank" rel="noreferrer">View public site</a></div></div>
 </form>;
}
