'use client';
import { useEffect, useState } from 'react';
import { request } from '@/components/social/common';

type CmsPage = { id:string;slug:string;title:string;body?:string;published:boolean;seo_title:string|null;seo_description:string|null;og_image:string|null;show_in_footer:boolean;footer_order:number;created_at:number;updated_at:number;updated_by:string|null };
type Editor = { id:string;slug:string;title:string;body:string;published:boolean;seoTitle:string;seoDescription:string;ogImage:string;showInFooter:boolean;footerOrder:number };
const empty = (slug=''):Editor=>({id:'',slug,title:'',body:'',published:false,seoTitle:'',seoDescription:'',ogImage:'',showInFooter:false,footerOrder:0});
export function CmsPageManager(){
 const [pages,setPages]=useState<CmsPage[]>([]),[editor,setEditor]=useState<Editor>(empty()),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const reload=async()=>setPages(await request<CmsPage[]>('/api/admin/pages'));
 useEffect(()=>{let active=true;request<CmsPage[]>('/api/admin/pages').then(rows=>{if(active)setPages(rows);}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:'Could not load pages.');});return()=>{active=false;};},[]);
 const edit=async(id:string)=>{setBusy(true);try{const page=await request<CmsPage>('/api/admin/pages?id='+encodeURIComponent(id));setEditor({id:page.id,slug:page.slug,title:page.title,body:page.body||'',published:page.published,seoTitle:page.seo_title||'',seoDescription:page.seo_description||'',ogImage:page.og_image||'',showInFooter:page.show_in_footer,footerOrder:page.footer_order});setConfirmation('');setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Could not open page.');}finally{setBusy(false);}};
 const save=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');try{const result=await request<{id:string;slug:string}>('/api/admin/pages',{action:'save',...editor});setEditor({...editor,id:result.id,slug:result.slug});await reload();setMessage('Page saved and audited. '+(editor.published?'It is publicly available.':'Drafts return 404 to visitors.'));}catch(error){setMessage(error instanceof Error?error.message:'Could not save page.');}finally{setBusy(false);}};
 const remove=async()=>{if(!editor.id)return;setBusy(true);setMessage('');try{await request('/api/admin/pages',{action:'delete',id:editor.id,confirmation});setEditor(empty());setConfirmation('');await reload();setMessage('Page deleted and audited.');}catch(error){setMessage(error instanceof Error?error.message:'Could not delete page.');}finally{setBusy(false);}};
 const field=(name:keyof Editor,label:string,max:number,type='text')=><label>{label}<input type={type} maxLength={max} value={String(editor[name])} onChange={event=>setEditor({...editor,[name]:event.target.value})}/></label>;
 return <div className="comms-page-manager">
  <section className="admin-card"><h2>CMS pages</h2><p>Markdown pages are inert drafts until published. Public routes use `/p/&lt;slug&gt;`; raw HTML is never rendered. Published pages can be added to the public footer.</p><div className="admin-action-grid"><button className="admin-button" type="button" onClick={()=>{setEditor(empty());setMessage('New page draft.');}}>New page</button><button className="admin-button" type="button" onClick={()=>{setEditor(empty('privacy'));setMessage('Create the privacy page, then add its content.');}}>New privacy page</button><button className="admin-button" type="button" onClick={()=>{setEditor(empty('terms'));setMessage('Create the terms page, then add its content.');}}>New terms page</button></div>
   <div className="admin-table-scroll" tabIndex={0} role="region" aria-label="CMS page list"><table><caption>Existing public pages and drafts</caption><thead><tr><th>Page</th><th>Status</th><th>Footer</th><th>Updated</th><th>Action</th></tr></thead><tbody>{pages.map(page=><tr key={page.id}><td>{page.title}<small>/p/{page.slug}</small></td><td>{page.published?'Published':'Draft'}</td><td>{page.show_in_footer?'Visible':'Hidden'}</td><td>{new Date(Number(page.updated_at)).toLocaleString()}</td><td><button className="admin-button" type="button" disabled={busy} onClick={()=>void edit(page.id)}>Edit</button> {page.published&&<a className="admin-button" href={'/p/'+page.slug} target="_blank" rel="noreferrer">View</a>}</td></tr>)}{!pages.length&&<tr><td colSpan={5} className="is-empty">No CMS pages yet.</td></tr>}</tbody></table></div>
  </section>
  <form className="admin-card admin-confirm" onSubmit={save}><h2>{editor.id?'Edit page':'Create page'}</h2><div className="admin-detail">{field('title','Public page title',120)}{field('slug','URL slug',80)}{field('seoTitle','SEO title',160)}{field('seoDescription','SEO description',320)}{field('ogImage','Open Graph image (safe HTTPS or local path)',2048)}<label>Footer order<input type="number" min={0} max={1000} value={editor.footerOrder} onChange={event=>setEditor({...editor,footerOrder:Number(event.target.value)})}/></label></div>
   <label>Markdown content<textarea rows={18} maxLength={50000} value={editor.body} onChange={event=>setEditor({...editor,body:event.target.value})} placeholder={'# Privacy\n\nWrite your page in Markdown. Raw HTML is displayed as text.'}/></label>
   <div className="admin-action-grid"><label className="feature-switch"><input type="checkbox" checked={editor.published} onChange={event=>setEditor({...editor,published:event.target.checked})}/>Published (drafts are 404)</label><label className="feature-switch"><input type="checkbox" checked={editor.showInFooter} onChange={event=>setEditor({...editor,showInFooter:event.target.checked})}/>Show in footer</label></div>
   {editor.id&&<label>Type page slug <strong>{editor.slug}</strong> to delete<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label>}
   {message&&<p role="status">{message}</p>}<div className="admin-action-grid"><button className="admin-button admin-primary" disabled={busy} type="submit">{busy?'Saving…':'Save page'}</button>{editor.id&&<button className="admin-button admin-danger" type="button" disabled={busy||confirmation!==editor.slug} onClick={()=>void remove()}>Delete page</button>}</div>
  </form>
 </div>;
}
