'use client';
import {useEffect,useState} from 'react';
import {request} from '@/components/social/common';
import {CmsPageManager} from './cms';

type Conversation={first_id:string;second_id:string;first_name:string;first_email:string|null;second_name:string;second_email:string|null;message_count:number;last_at:number};
type Message={id:string;sender_id:string;recipient_id:string;body:string;created_at:number;redacted_at:number|null;redaction_reason:string|null;sender_name:string};
type Template={kind:string;enabled:boolean;template_text:string};
type Account={id:string;name:string;email:string;username:string;dm_disabled:boolean;dm_reason:string};
type MessagingLimits={maxLength:number;rateWindowSeconds:number;rateMaxMessages:number};
type Restriction={profile_id:string;name:string;email:string;username:string;dm_disabled:boolean;send_disabled:boolean;receive_disabled:boolean;suspended_until:number;reason:string};
type RestrictionDraft={send:boolean;receive:boolean;until:string;reason:string;confirm:string};
const blankDraft=():RestrictionDraft=>({send:false,receive:false,until:'',reason:'',confirm:''});
const toLocalInput=(value:number)=>{if(!value)return '';const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
type EmailState={paused:boolean;daily_cap:number;sent_today:number;remaining:number};
type Announcement={id:string;title:string;body:string;href:string|null;tone:string;starts_at:number|null;ends_at:number|null;dismissible:boolean;audience:string;published:boolean;created_at:number};
const tabs=[['messages','Messages'],['controls','DM controls'],['restrictions','Message restrictions'],['limits','Messaging limits'],['templates','Notification templates'],['broadcast','In-app broadcast'],['email','Email'],['announcements','Announcements'],['pages','CMS pages']] as const;
export function CommunicationCenter(){
 const [tab,setTab]=useState<string>('messages');
 return <><div className="admin-tabs" role="tablist" aria-label="Communication tools">{tabs.map(([value,label])=><button type="button" role="tab" aria-selected={tab===value} className={tab===value?'active':''} key={value} onClick={()=>setTab(value)}>{label}</button>)}</div>
  {tab==='messages'&&<MessageInspector/>}{tab==='controls'&&<DirectMessageControls/>}{tab==='restrictions'&&<MessageRestrictionControls/>}{tab==='limits'&&<MessagingLimitsEditor/>}{tab==='templates'&&<NotificationTemplateEditor/>}{tab==='broadcast'&&<BroadcastEditor/>}{tab==='email'&&<EmailCampaignEditor/>}{tab==='announcements'&&<AnnouncementEditor/>}{tab==='pages'&&<CmsPageManager/>}
 </>;
}
function MessageInspector(){
 const [q,setQ]=useState(''),[items,setItems]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[total,setTotal]=useState(0);
 const load=async()=>{const result=await request<{conversations:Conversation[];total:number}>('/api/admin/comms?view=conversations&q='+encodeURIComponent(q));setItems(result.conversations);setTotal(result.total);};
 useEffect(()=>{let active=true;request<{conversations:Conversation[];total:number}>('/api/admin/comms?view=conversations&q=').then(result=>{if(active){setItems(result.conversations);setTotal(result.total);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Could not load conversations.');});return()=>{active=false;};},[]);
 const inspect=async(event:React.FormEvent)=>{event.preventDefault();if(!selected)return;setBusy(true);setError('');try{const result=await request<{messages:Message[];total:number;truncated:boolean}>('/api/admin/comms',{action:'inspectConversation',firstId:selected.first_id,secondId:selected.second_id,reason,confirmation});setMessages(result.messages);setConfirmation('');setError(`Audited break-glass access: ${result.total} messages${result.truncated?' (showing newest 100)':''}.`);}catch(e){setError(e instanceof Error?e.message:'Could not inspect conversation.');}finally{setBusy(false);}};
 const moderate=async(message:Message,action:'redact'|'delete',reasonText:string,confirmText:string)=>{setBusy(true);setError('');try{await request('/api/admin/comms',{action:'moderateMessage',operation:action,id:message.id,confirmation:confirmText,reason:reasonText});setMessages(items=>action==='delete'?items.filter(item=>item.id!==message.id):items.map(item=>item.id===message.id?{...item,body:'[Message removed by moderation]',redacted_at:Date.now(),redaction_reason:reasonText}:item));setError(action==='redact'?'Message redacted and audited.':'Message removed and audited.');}catch(e){setError(e instanceof Error?e.message:'Could not change message.');}finally{setBusy(false);}};
 return <div className="comms-grid"><section className="admin-card"><h2>Private message inventory</h2><p>Conversation listings show participant metadata only. Message text is revealed only after entering a reason and the exact break-glass phrase. Each access is audited before the text is returned.</p><form className="admin-search" onSubmit={event=>{event.preventDefault();void load().catch(e=>setError(e.message));}}><label>Search participants<input maxLength={100} value={q} onChange={event=>setQ(event.target.value)} placeholder="Username, name, email, or ID"/></label><div className="admin-filter-actions"><button className="admin-button">Search</button><button type="button" className="admin-button" onClick={()=>void load().catch(e=>setError(e.message))}>Refresh</button></div></form><p>{total.toLocaleString()} conversations</p><div className="admin-table-scroll" tabIndex={0} role="region" aria-label="Message conversations"><table><thead><tr><th>Participants</th><th>Messages</th><th>Last activity</th><th>Action</th></tr></thead><tbody>{items.map(item=><tr key={item.first_id+':'+item.second_id}><td className="actor-cell">{item.first_name} <small>{item.first_email||item.first_id}</small><br/>{item.second_name} <small>{item.second_email||item.second_id}</small></td><td>{Number(item.message_count)}</td><td className="admin-cell-time">{new Date(Number(item.last_at)).toLocaleString()}</td><td className="action-cell"><button className="admin-button" type="button" onClick={()=>{setSelected(item);setMessages([]);setReason('');setConfirmation('');setError('');}}>Break glass</button></td></tr>)}{!items.length&&<tr><td colSpan={4}>No conversations match.</td></tr>}</tbody></table></div></section>
  {selected&&<section className="admin-card admin-confirm"><h2>Audited conversation inspection</h2><p>{selected.first_name} ↔ {selected.second_name} · {selected.first_id} / {selected.second_id}</p><form onSubmit={inspect}><label>Reason for access<input required minLength={8} maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Type BREAK GLASS<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)} required/></label><button className="admin-button admin-primary" disabled={busy||confirmation!=='BREAK GLASS'}>Reveal and audit</button></form>{error&&<p role="status">{error}</p>}
   {messages.map(message=><MessageRow key={message.id} message={message} busy={busy} onModerate={moderate}/>)}
  </section>}
 </div>;
}
function MessageRow({message,busy,onModerate}:{message:Message;busy:boolean;onModerate:(message:Message,action:'redact'|'delete',reason:string,confirmText:string)=>Promise<void>}){
 const [action,setAction]=useState<'redact'|'delete'>('redact'),[reason,setReason]=useState(''),[confirmation,setConfirmation]=useState('');
 return <article className="admin-message-row"><p><strong>{message.sender_name}</strong> · {new Date(Number(message.created_at)).toLocaleString()}</p><pre>{message.body}</pre>{message.redacted_at&&<small>Redacted: {message.redaction_reason}</small>}<div className="admin-detail"><label>Action<select value={action} onChange={event=>setAction(event.target.value as 'redact'|'delete')}><option value="redact">Redact text</option><option value="delete">Remove from both inboxes</option></select></label><label>Reason<input maxLength={500} required value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Type message ID<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label></div><button className="admin-button admin-danger" type="button" disabled={busy||confirmation!==message.id||reason.trim().length<3} onClick={()=>void onModerate(message,action,reason,confirmation)}>Confirm {action}</button></article>;
}
function DirectMessageControls(){
 const [q,setQ]=useState(''),[items,setItems]=useState<Account[]>([]),[reasons,setReasons]=useState<Record<string,string>>({}),[confirms,setConfirms]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>setItems(await request<Account[]>('/api/admin/comms?view=accounts&q='+encodeURIComponent(q)));
 useEffect(()=>{let active=true;request<Account[]>('/api/admin/comms?view=accounts&q=').then(rows=>{if(active)setItems(rows);}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load accounts.');});return()=>{active=false;};},[]);
 const save=async(account:Account,disabled:boolean)=>{setBusy(true);setMessage('');try{await request('/api/admin/comms',{action:'setDirectMessageControl',profileId:account.id,disabled,reason:reasons[account.id]||'',confirmation:confirms[account.id]||''});await load();setConfirms({...confirms,[account.id]:''});setMessage('Direct-message restriction saved and audited.');}catch(e){setMessage(e instanceof Error?e.message:'Could not update direct-message access.');}finally{setBusy(false);}};
 return <section className="admin-card"><h2>Per-account direct-message controls</h2><p>The existing global Messages feature switch remains under Features. These per-account controls deny new sends when either participant is restricted; historical conversations are not hidden or deleted.</p><form className="admin-search" onSubmit={event=>{event.preventDefault();void load().catch(e=>setMessage(e.message));}}><label>Find account<input minLength={2} maxLength={100} value={q} onChange={event=>setQ(event.target.value)}/></label><div className="admin-filter-actions"><button className="admin-button">Search</button></div></form><div className="admin-table-scroll" tabIndex={0} role="region" aria-label="Direct-message account controls"><table><thead><tr><th>Account</th><th>Current state</th><th>Reason</th><th>Confirm account ID</th><th>Action</th></tr></thead><tbody>{items.map(account=><tr key={account.id}><td className="actor-cell">{account.username||account.name}<small>{account.email}<br/>{account.id}</small></td><td className="status-cell">{account.dm_disabled?'Restricted':'Allowed'}</td><td className="reason-cell"><input aria-label={'Reason for '+account.email} value={reasons[account.id]??account.dm_reason} maxLength={500} onChange={event=>setReasons({...reasons,[account.id]:event.target.value})}/></td><td className="id-cell"><input aria-label={'Confirmation for '+account.email} value={confirms[account.id]||''} onChange={event=>setConfirms({...confirms,[account.id]:event.target.value})}/></td><td className="action-cell"><button className="admin-button" disabled={busy||confirms[account.id]!==account.id||(!account.dm_disabled&&!(reasons[account.id]||'').trim())} onClick={()=>void save(account,!account.dm_disabled)}>{account.dm_disabled?'Allow DMs':'Restrict DMs'}</button></td></tr>)}{!items.length&&<tr><td colSpan={5}>Search for a member to manage DM access.</td></tr>}</tbody></table></div>{message&&<p role="status">{message}</p>}</section>;
}
function MessageRestrictionControls(){
 const [q,setQ]=useState(''),[items,setItems]=useState<Restriction[]>([]),[drafts,setDrafts]=useState<Record<string,RestrictionDraft>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const draftFor=(row:Restriction):RestrictionDraft=>drafts[row.profile_id]||{send:row.send_disabled,receive:row.receive_disabled,until:toLocalInput(row.suspended_until),reason:row.reason,confirm:''};
 const patch=(id:string,next:Partial<RestrictionDraft>)=>setDrafts(current=>{const base=current[id]||draftFor(items.find(row=>row.profile_id===id)!);return {...current,[id]:{...base,...next}};});
 const load=async()=>setItems(await request<Restriction[]>('/api/admin/comms?view=restrictions&q='+encodeURIComponent(q)));
 useEffect(()=>{let active=true;request<Restriction[]>('/api/admin/comms?view=restrictions&q=').then(rows=>{if(active)setItems(rows);}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load account restrictions.');});return()=>{active=false;};},[]);
 const save=async(row:Restriction)=>{const draft=draftFor(row);setBusy(true);setMessage('');try{
   await request('/api/admin/comms',{action:'setMessageRestriction',profileId:row.profile_id,send:draft.send,receive:draft.receive,suspendedUntil:draft.until?new Date(draft.until).toISOString():null,reason:draft.reason,confirmation:draft.confirm});
   setDrafts(current=>({...current,[row.profile_id]:blankDraft()}));await load();setMessage('Restriction saved and audited. New sends are rejected immediately.');
 }catch(e){setMessage(e instanceof Error?e.message:'Could not update the restriction.');}finally{setBusy(false);}};
 return <section className="admin-card"><h2>Per-account message restrictions</h2><p>Three separate switches: <strong>sending</strong> stops this account from writing, <strong>receiving</strong> stops anyone writing to it, and <strong>suspension</strong> pauses messaging in both directions until the chosen moment. They stack on top of the global DM switch above and on the Messages feature flag under Features. Nothing is retroactive: existing conversations stay readable.</p>
 <form className="admin-search" onSubmit={event=>{event.preventDefault();void load().catch(e=>setMessage(e.message));}}><label>Find account<input minLength={2} maxLength={100} value={q} onChange={event=>setQ(event.target.value)}/></label><div className="admin-filter-actions"><button className="admin-button">Search</button></div></form>
 <div className="admin-table-scroll" tabIndex={0} role="region" aria-label="Per-account message restrictions"><table><thead><tr><th>Account</th><th>Sending</th><th>Receiving</th><th>Suspended until</th><th>Reason</th><th>Confirm account ID</th><th>Action</th></tr></thead><tbody>{items.map(row=>{const draft=draftFor(row);const restricted=draft.send||draft.receive||!!draft.until;
  return <tr key={row.profile_id}><td className="actor-cell">{row.username||row.name}<small>{row.email}<br/>{row.profile_id}</small></td>
   <td className="status-cell"><label className="feature-switch"><input type="checkbox" checked={draft.send} onChange={event=>patch(row.profile_id,{send:event.target.checked})}/>Blocked</label></td>
   <td className="status-cell"><label className="feature-switch"><input type="checkbox" checked={draft.receive} onChange={event=>patch(row.profile_id,{receive:event.target.checked})}/>Blocked</label></td>
   <td className="reason-cell"><input type="datetime-local" aria-label={'Suspension end for '+row.email} value={draft.until} onChange={event=>patch(row.profile_id,{until:event.target.value})}/></td>
   <td className="reason-cell"><input aria-label={'Reason for '+row.email} maxLength={500} value={draft.reason} onChange={event=>patch(row.profile_id,{reason:event.target.value})}/></td>
   <td className="id-cell"><input aria-label={'Confirmation for '+row.email} value={draft.confirm} onChange={event=>patch(row.profile_id,{confirm:event.target.value})}/></td>
   <td className="action-cell"><button className="admin-button" disabled={busy||draft.confirm!==row.profile_id||(restricted&&draft.reason.trim().length<3)} onClick={()=>void save(row)}>{restricted?'Apply restriction':'Lift restriction'}</button></td></tr>;})}{!items.length&&<tr><td colSpan={7}>Search for a member to manage restrictions.</td></tr>}</tbody></table></div>{message&&<p role="status">{message}</p>}</section>;
}
function MessagingLimitsEditor(){
 const [state,setState]=useState<MessagingLimits|null>(null),[maxLength,setMaxLength]=useState(2000),[window,setWindow]=useState(60),[cap,setCap]=useState(30),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const limits=await request<MessagingLimits>('/api/admin/comms?view=limits');setState(limits);setMaxLength(limits.maxLength);setWindow(limits.rateWindowSeconds);setCap(limits.rateMaxMessages);};
 useEffect(()=>{let active=true;request<MessagingLimits>('/api/admin/comms?view=limits').then(limits=>{if(active){setState(limits);setMaxLength(limits.maxLength);setWindow(limits.rateWindowSeconds);setCap(limits.rateMaxMessages);}}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load messaging limits.');});return()=>{active=false;};},[]);
 const save=async()=>{setBusy(true);setMessage('');try{
   await request('/api/admin/comms',{action:'saveMessagingLimits','messages.maxLength':maxLength,'messages.rateWindowSeconds':window,'messages.rateMaxMessages':cap});
   await load();setMessage('Messaging limits saved and audited. The API and the composer follow them immediately.');
 }catch(e){setMessage(e instanceof Error?e.message:'Could not save messaging limits.');}finally{setBusy(false);}};
 return <div className="comms-grid"><section className="admin-card"><h2>Message length</h2><p>Longest message a member may send, counted in characters. The composer stops at the same number, and the API rejects anything longer, so a stale browser tab cannot slip past it.</p><label>Maximum characters (1–4000)<input type="number" min={1} max={4000} value={maxLength} onChange={event=>setMaxLength(Number(event.target.value))}/></label></section>
 <section className="admin-card"><h2>Send quota</h2><p>Sliding window counted from the messages table itself. Set the window to 0 to switch the quota off entirely. The API answers 429 once a member reaches the cap; the composer never shows the quota, because it is a server rule.</p><label>Window in seconds (0–86400, 0 disables)<input type="number" min={0} max={86400} value={window} onChange={event=>setWindow(Number(event.target.value))}/></label><label>Maximum messages in the window (1–1000)<input type="number" min={1} max={1000} value={cap} onChange={event=>setCap(Number(event.target.value))}/></label></section>
 <section className="admin-card admin-confirm"><h2>Save messaging limits</h2><p>{state?`Currently stored: ${state.maxLength} characters, ${state.rateWindowSeconds?state.rateMaxMessages+' messages per '+state.rateWindowSeconds+' seconds':'quota off'}.`:'Loading the stored values…'}</p><button className="admin-button admin-primary" type="button" disabled={busy} onClick={()=>void save()}>Save limits and audit</button>{message&&<p role="status">{message}</p>}</section></div>;
}
function NotificationTemplateEditor(){
 const [templates,setTemplates]=useState<Template[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>setTemplates(await request<Template[]>('/api/admin/comms?view=templates'));
 useEffect(()=>{let active=true;request<Template[]>('/api/admin/comms?view=templates').then(rows=>{if(active)setTemplates(rows);}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load notification templates.');});return()=>{active=false;};},[]);
 const save=async(item:Template)=>{setBusy(true);setMessage('');try{await request('/api/admin/comms',{action:'saveNotificationTemplate',kind:item.kind,enabled:item.enabled,templateText:item.template_text});await load();setMessage('Notification template saved and audited.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save template.');}finally{setBusy(false);}};
 return <section className="admin-card"><h2>Notification kinds and templates</h2><p>Disabling a kind stops new notifications and hides its historical entries from the public inbox. Templates are plain text suffixes; HTML is not supported. The global Notifications feature flag still overrides all kinds.</p>{templates.map((item,index)=><fieldset className="admin-confirm notification-template-row" key={item.kind}><legend>{item.kind}</legend><label className="feature-switch"><input type="checkbox" checked={item.enabled} onChange={event=>setTemplates(templates.map((row,i)=>i===index?{...row,enabled:event.target.checked}:row))}/>Enabled</label><label>Displayed text<input maxLength={140} value={item.template_text} onChange={event=>setTemplates(templates.map((row,i)=>i===index?{...row,template_text:event.target.value}:row))}/></label><button className="admin-button" type="button" disabled={busy} onClick={()=>void save(item)}>Save {item.kind}</button></fieldset>)}{message&&<p role="status">{message}</p>}</section>;
}
function BroadcastEditor(){
 const [audience,setAudience]=useState<'all_members'|'selected'>('all_members'),[userIds,setUserIds]=useState(''),[body,setBody]=useState(''),[reason,setReason]=useState(''),[preview,setPreview]=useState<{count:number;confirmation:string}|null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const data=()=>({audience,userIds:audience==='selected'?userIds.split(/[\s,]+/).filter(Boolean):undefined,message:body});
 const dryRun=async()=>{setBusy(true);setMessage('');try{const result=await request<{count:number;confirmation:string}>('/api/admin/comms',{action:'previewInAppBroadcast',...data()});setPreview(result);setConfirmation('');setMessage(`Dry run only: ${result.count} active members match. No notifications were created.`);}catch(e){setMessage(e instanceof Error?e.message:'Preview failed.');}finally{setBusy(false);}};
 const send=async()=>{if(!preview)return;setBusy(true);setMessage('');try{const result=await request<{recipients:number}>('/api/admin/comms',{action:'sendInAppBroadcast',...data(),confirmation,reason});setMessage(`Broadcast delivered to ${result.recipients} members and audited.`);setPreview(null);setConfirmation('');}catch(e){setMessage(e instanceof Error?e.message:'Broadcast failed.');}finally{setBusy(false);}};
 return <section className="admin-card admin-confirm"><h2>In-app broadcast</h2><p>Dry-run first, then confirm the exact audience count. Eligible audience excludes admins, moderators, demos, unverified, banned, and deleted accounts. Maximum 10,000 recipients.</p><label>Audience<select value={audience} onChange={event=>{setAudience(event.target.value as typeof audience);setPreview(null);}}><option value="all_members">All active members</option><option value="selected">Exact selected account IDs</option></select></label>{audience==='selected'&&<label>Account IDs, comma or newline separated<textarea rows={4} value={userIds} onChange={event=>{setUserIds(event.target.value);setPreview(null);}}/></label>}<label>Notification message<textarea maxLength={500} required rows={4} value={body} onChange={event=>{setBody(event.target.value);setPreview(null);}}/></label><label>Audit reason<input maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></label><button type="button" className="admin-button" disabled={busy||!body.trim()} onClick={()=>void dryRun()}>{busy?'Working…':'Dry-run audience'}</button>{preview&&<><p>Preview: <strong>{preview.count}</strong> exact recipients.</p><label>Type {preview.confirmation}<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button type="button" className="admin-button admin-primary" disabled={busy||confirmation!==preview.confirmation} onClick={()=>void send()}>Send in-app broadcast</button></>}{message&&<p role="status">{message}</p>}</section>;
}
function EmailCampaignEditor(){
 const [controls,setControls]=useState<EmailState|null>(null),[paused,setPaused]=useState(true),[cap,setCap]=useState(25),[audience,setAudience]=useState<'all_members'|'selected'>('all_members'),[userIds,setUserIds]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[preview,setPreview]=useState<{count:number;withinCap:boolean;paused:boolean;remaining:number;campaignCap:number}|null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const state=await request<EmailState>('/api/admin/comms?view=email');setControls(state);setPaused(state.paused);setCap(state.daily_cap);};
 useEffect(()=>{let active=true;request<EmailState>('/api/admin/comms?view=email').then(state=>{if(active){setControls(state);setPaused(state.paused);setCap(state.daily_cap);}}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load email controls.');});return()=>{active=false;};},[]);
 const data=()=>({audience,userIds:audience==='selected'?userIds.split(/[\s,]+/).filter(Boolean):undefined,subject,message:body});
 const saveControls=async()=>{setBusy(true);setMessage('');try{const state=await request<EmailState>('/api/admin/comms',{action:'updateEmailControls',paused,dailyCap:cap});setControls(state);setMessage('Global email pause and daily cap saved and audited.');}catch(e){setMessage(e instanceof Error?e.message:'Could not update controls.');}finally{setBusy(false);}};
 const dryRun=async()=>{setBusy(true);setMessage('');try{const result=await request<{count:number;withinCap:boolean;paused:boolean;remaining:number;campaignCap:number}>('/api/admin/comms',{action:'previewEmailCampaign',...data()});setPreview(result);setConfirmation('');setMessage(`Dry run only: ${result.count} active, verified email recipients. No email was sent.`);}catch(e){setMessage(e instanceof Error?e.message:'Preview failed.');}finally{setBusy(false);}};
 const send=async()=>{setBusy(true);setMessage('');try{const result=await request<{sent:number;failed:number;throttled:number;attempted:number}>('/api/admin/comms',{action:'sendEmailCampaign',...data(),confirmation});setMessage(`Campaign complete: ${result.sent} sent, ${result.failed} failed, ${result.throttled} rate-limited. ${result.attempted} attempts reserved against the cap.`);setPreview(null);setConfirmation('');await load();}catch(e){setMessage(e instanceof Error?e.message:'Campaign failed.');}finally{setBusy(false);}};
 return <div className="comms-grid"><section className="admin-card admin-confirm"><h2>Brevo safety controls</h2><p>Paused by default. Dry-run never sends. The database-enforced UTC daily cap defaults to 25 and cannot exceed 300. Attempts reserve capacity even if provider delivery fails.</p><label className="feature-switch"><input type="checkbox" checked={paused} onChange={event=>setPaused(event.target.checked)}/>Pause administrator email sending</label><label>Daily maximum (1–300)<input type="number" min={1} max={300} value={cap} onChange={event=>setCap(Number(event.target.value))}/></label><button className="admin-button" type="button" disabled={busy} onClick={()=>void saveControls()}>Save pause and cap</button>{controls&&<p>{controls.sent_today} reserved today · {controls.remaining} remaining</p>}</section>
  <section className="admin-card admin-confirm"><h2>Admin email campaign</h2><p>Only active, verified, non-demo member accounts are eligible. Selected IDs are validated against the exact current audience. Maximum 25 per campaign so provider timeouts stay bounded; the daily cap is enforced across requests.</p><label>Audience<select value={audience} onChange={event=>{setAudience(event.target.value as typeof audience);setPreview(null);}}><option value="all_members">All active members</option><option value="selected">Exact selected account IDs</option></select></label>{audience==='selected'&&<label>Account IDs, comma or newline separated<textarea rows={4} value={userIds} onChange={event=>{setUserIds(event.target.value);setPreview(null);}}/></label>}<label>Subject<input maxLength={160} value={subject} onChange={event=>{setSubject(event.target.value);setPreview(null);}}/></label><label>Plain-text email<textarea maxLength={5000} rows={8} value={body} onChange={event=>{setBody(event.target.value);setPreview(null);}}/></label><button className="admin-button" type="button" disabled={busy||!subject.trim()||!body.trim()} onClick={()=>void dryRun()}>{busy?'Working…':'Dry-run recipients'}</button>{preview&&<><p>Preview: {preview.count} recipients · per-campaign cap {preview.campaignCap} · {preview.remaining} daily cap remaining · {preview.paused?'Sending is paused':preview.withinCap?'Within cap':'Exceeds cap'}. Preview sends nothing.</p><label>Type SEND {preview.count} EMAILS<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button className="admin-button admin-danger" type="button" disabled={busy||preview.paused||!preview.withinCap||confirmation!==`SEND ${preview.count} EMAILS`} onClick={()=>void send()}>Send real email</button></>}{message&&<p role="status">{message}</p>}</section>
 </div>;
}
function AnnouncementEditor(){
 type AnnouncementForm={id:string;title:string;body:string;href:string;tone:'info'|'success'|'warning';startsAt:string;endsAt:string;dismissible:boolean;audience:'all'|'members';published:boolean};
 const blank=():AnnouncementForm=>({id:'',title:'',body:'',href:'',tone:'info',startsAt:'',endsAt:'',dismissible:true,audience:'all',published:false});
 const [rows,setRows]=useState<Announcement[]>([]),[form,setForm]=useState<AnnouncementForm>(blank()),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>setRows(await request<Announcement[]>('/api/admin/comms?view=announcements'));
 useEffect(()=>{let active=true;request<Announcement[]>('/api/admin/comms?view=announcements').then(rows=>{if(active)setRows(rows);}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:'Could not load announcements.');});return()=>{active=false;};},[]);
 const localDateTime=(value:number)=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 const isoDateTime=(value:string)=>value?new Date(value).toISOString():'';
 const value=(row:Announcement):AnnouncementForm=>({...blank(),id:row.id,title:row.title,body:row.body,href:row.href||'',tone:(['info','success','warning'].includes(row.tone)?row.tone:'info') as AnnouncementForm['tone'],startsAt:row.starts_at?localDateTime(Number(row.starts_at)):'',endsAt:row.ends_at?localDateTime(Number(row.ends_at)):'',dismissible:row.dismissible,audience:row.audience==='members'?'members':'all',published:row.published});
 const save=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);try{const result=await request<{id:string}>('/api/admin/comms',{action:'saveAnnouncement',...form});setForm({...form,id:result.id});await load();setMessage('Announcement saved and audited.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save announcement.');}finally{setBusy(false);}};
 const remove=async()=>{setBusy(true);try{await request('/api/admin/comms',{action:'deleteAnnouncement',id:form.id,confirmation});setForm(blank());setConfirmation('');await load();setMessage('Announcement deleted and audited.');}catch(e){setMessage(e instanceof Error?e.message:'Could not delete announcement.');}finally{setBusy(false);}};
 return <div className="comms-grid"><section className="admin-card"><h2>Announcements</h2><p>Published announcements appear on the public home feed, respect their schedule and audience, and can be dismissed on a browser. Existing Appearance banners remain separate.</p><div className="admin-table-scroll" tabIndex={0} role="region" aria-label="Announcement list"><table><thead><tr><th>Title</th><th>State</th><th>Audience</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td className="target-cell">{row.title}</td><td className="status-cell">{row.published?'Published':'Draft'}</td><td>{row.audience}</td><td className="action-cell"><button type="button" className="admin-button" onClick={()=>{setForm(value(row));setConfirmation('');}}>Edit</button></td></tr>)}{!rows.length&&<tr><td colSpan={4}>No announcements.</td></tr>}</tbody></table></div><button type="button" className="admin-button" onClick={()=>{setForm(blank());setConfirmation('');}}>New announcement</button></section>
  <form className="admin-card admin-confirm" onSubmit={save}><h2>{form.id?'Edit announcement':'Create announcement'}</h2><label>Title<input required maxLength={120} value={form.title} onChange={event=>setForm({...form,title:event.target.value})}/></label><label>Message<textarea required maxLength={2000} rows={5} value={form.body} onChange={event=>setForm({...form,body:event.target.value})}/></label><label>Optional link<input maxLength={2048} value={form.href||''} onChange={event=>setForm({...form,href:event.target.value})}/></label><div className="admin-detail"><label>Style<select value={form.tone} onChange={event=>setForm({...form,tone:event.target.value as AnnouncementForm['tone']})}><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option></select></label><label>Audience<select value={form.audience} onChange={event=>setForm({...form,audience:event.target.value as AnnouncementForm['audience']})}><option value="all">Everyone</option><option value="members">Signed-in members</option></select></label><label>Start<input type="datetime-local" value={form.startsAt?localDateTime(Date.parse(form.startsAt)):''} onChange={event=>setForm({...form,startsAt:isoDateTime(event.target.value)})}/></label><label>End<input type="datetime-local" value={form.endsAt?localDateTime(Date.parse(form.endsAt)):''} onChange={event=>setForm({...form,endsAt:isoDateTime(event.target.value)})}/></label></div><label className="feature-switch"><input type="checkbox" checked={form.dismissible} onChange={event=>setForm({...form,dismissible:event.target.checked})}/>Dismissible</label><label className="feature-switch"><input type="checkbox" checked={form.published} onChange={event=>setForm({...form,published:event.target.checked})}/>Published</label>{form.id&&<label>Type announcement ID to delete<input value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label>}{message&&<p role="status">{message}</p>}<div className="admin-action-grid"><button className="admin-button admin-primary" disabled={busy}>Save and audit</button>{form.id&&<button type="button" className="admin-button admin-danger" disabled={busy||confirmation!==form.id} onClick={()=>void remove()}>Delete</button>}</div></form>
 </div>;
}
