'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {FEATURE_KEYS,type FeatureConfig} from '@/lib/features';
import {request} from '@/components/social/common';
export function FeatureEditor({initial}:{initial:FeatureConfig}){
 const [value,setValue]=useState(initial),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[confirmation,setConfirmation]=useState('');const router=useRouter();
 return <form className="admin-confirm feature-editor" onSubmit={async event=>{event.preventDefault();setPending(true);setMessage('');try{await request('/api/admin/features',{value,confirmation});setMessage('Feature controls saved and audited. Existing public tabs should reload.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not save.');}finally{setPending(false);}}}>
 <section className="admin-card"><h2>Feature rollouts</h2><p>Assignments are deterministic per feature and account ID. Anonymous visitors (including signup requests) share one stable cohort, not a random percentage of visitors. 100% is everyone; 0% is nobody. Feature flags do not grant permissions or bypass private accounts.</p><div className="feature-grid">{FEATURE_KEYS.map(key=><fieldset key={key}><legend>{key}</legend><label className="feature-switch admin-switch"><input type="checkbox" checked={value.flags[key].enabled} onChange={e=>setValue({...value,flags:{...value.flags,[key]:{...value.flags[key],enabled:e.target.checked}}})}/>Enabled</label><label>Rollout percent<input aria-label={key+' rollout percent'} type="number" min={0} max={100} step={1} value={value.flags[key].percent} onChange={e=>setValue({...value,flags:{...value.flags,[key]:{...value.flags[key],percent:Number(e.target.value)}}})}/></label></fieldset>)}</div></section>
 <section className="admin-card admin-confirm"><h2>Maintenance</h2><p>Verified, active admins/owners bypass maintenance only. Feature flags still apply to them. Admin pages, sign-in, recovery and sign-out remain reachable. Existing private content stays private.</p><label className="feature-switch admin-switch"><input type="checkbox" checked={value.maintenance.enabled} onChange={e=>setValue({...value,maintenance:{...value.maintenance,enabled:e.target.checked}})}/>Enable maintenance mode</label><label>Public title<input maxLength={100} required value={value.maintenance.title} onChange={e=>setValue({...value,maintenance:{...value.maintenance,title:e.target.value}})}/></label><label>Public message<input maxLength={500} value={value.maintenance.message} onChange={e=>setValue({...value,maintenance:{...value.maintenance,message:e.target.value}})}/></label>{value.maintenance.enabled&&<label>Type MAINTENANCE to confirm<input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)} required/></label>}</section>
 <section className="admin-card admin-confirm"><h2>Displayed engagement</h2><p>Displayed total = floor((real interactions + per-post baseline) × multiplier + deterministic jitter), clamped to 0–1 trillion. Jitter is a stable per-post offset, not a fresh random number on each request. Views count unique recorded “seen” reactions, not video plays.</p><label>Multiplier (0–100)<input type="number" min={0} max={100} step="0.01" value={value.counters.multiplier} onChange={e=>setValue({...value,counters:{...value.counters,multiplier:Number(e.target.value)}})}/></label><label>Jitter amplitude (0–1000)<input type="number" min={0} max={1000} step={1} value={value.counters.jitter} onChange={e=>setValue({...value,counters:{...value.counters,jitter:Number(e.target.value)}})}/></label><label className="feature-switch admin-switch"><input type="checkbox" checked={value.counters.hide} onChange={e=>setValue({...value,counters:{...value.counters,hide:e.target.checked}})}/>Hide public post engagement counts</label><p>Open a post in Content for baseline editing. Hiding displayed counts does not erase actual engagement or alter private-profile access.</p></section>
 {message&&<p role="status">{message}</p>}<button type="submit" className="admin-button admin-primary" disabled={pending||(value.maintenance.enabled&&confirmation!=='MAINTENANCE')}>{pending?'Saving…':'Publish feature controls'}</button>
 </form>;
}
export function CounterEditor({id,likes,comments,views,disabled}:{id:string;likes:number;comments:number;views:number;disabled:boolean}){
 const [values,setValues]=useState([likes,comments,views]),[confirmation,setConfirmation]=useState(''),[pending,setPending]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 return <form className="admin-confirm" onSubmit={async event=>{event.preventDefault();setPending(true);try{await request('/api/admin',{action:'moderateContent',resource:'posts',operation:'counters',ids:[id],confirmation,base_likes:values[0],base_comments:values[1],base_views:values[2]});setMessage('Baselines saved and audited.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not save.');}finally{setPending(false);}}}><fieldset disabled={disabled||pending} className="admin-confirm">{['Likes','Comments','Views'].map((name,i)=><label key={name}>{name} baseline<input type="number" min={0} max={1000000000} step={1} required value={values[i]} onChange={e=>setValues(values.map((v,j)=>i===j?Number(e.target.value):v))}/></label>)}<label>Type {id} to confirm baseline changes<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} required autoComplete="off"/></label><button className="admin-button" disabled={confirmation!==id} type="submit">Save counter baselines</button></fieldset>{message&&<p role="status">{message}</p>}</form>;
}
