'use client';
import {useState,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {LABEL_DEFAULTS,validateLabels,parseLabelsImport,MAX_LABEL_IMPORT_BYTES,type LabelKey,type LabelOverrides} from '@/lib/admin/labels';
import {request} from '@/components/social/common';
const keys=Object.keys(LABEL_DEFAULTS) as LabelKey[];
export function LabelsEditor({initial}:{initial:LabelOverrides}){
 const [draft,setDraft]=useState(initial),[query,setQuery]=useState(''),[page,setPage]=useState(0),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[reset,setReset]=useState('');
 const input=useRef<HTMLInputElement>(null);const router=useRouter();
 const matches=keys.filter(key=>(key+' '+LABEL_DEFAULTS[key]+' '+(draft[key]||'')).toLowerCase().includes(query.toLowerCase()));
 const pages=Math.max(1,Math.ceil(matches.length/40));const current=Math.min(page,pages-1);
 const update=(key:LabelKey,value:string|undefined)=>setDraft(previous=>{const next={...previous};if(value===undefined||value===LABEL_DEFAULTS[key])delete next[key];else next[key]=value;return next;});
 return <form className="admin-confirm labels-editor" onSubmit={async event=>{event.preventDefault();setPending(true);setMessage('');try{const value=validateLabels(draft);await request('/api/admin/labels',{value});setDraft(value);setMessage('Labels published and audited. Reload public tabs to see changes.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not publish labels.');}finally{setPending(false);}}}>
 <section className="admin-card admin-confirm"><h2>Find and edit</h2><p>Navigation label overrides take precedence over Appearance labels for the same built-in target; resetting a label restores the Appearance value. Rename <code>nav.reels</code> to update the sidebar, dock, heading, page title and default copy mentioning Reels. Explicitly edited copy is retained. User content, category IDs, URLs and branding/banner/footer text from Appearance are not rewritten.</p><p>Keep placeholders such as <code>{'{site}'}</code> unchanged. Text is escaped by React; HTML is never executed. Published blank values are not allowed. Reset a field to use its default.</p>
 <label>Search keys, defaults or current values<input type="search" value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}}/></label>
 <div className="labels-toolbar"><button type="button" className="admin-button" onClick={()=>{try{const value=validateLabels(draft);const url=URL.createObjectURL(new Blob([JSON.stringify({...LABEL_DEFAULTS,...value},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='functiongram-labels-en.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){setMessage(error instanceof Error?error.message:'Could not export labels.');}}}>Export JSON</button><label className="admin-button">Import JSON<input ref={input} type="file" accept="application/json,.json" disabled={pending} onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>MAX_LABEL_IMPORT_BYTES)throw new Error('Label import file is too large.');const value=parseLabelsImport(await file.text());setDraft(value);setMessage('Import staged. Review it, then Publish labels. This replaces the draft, not the live site.');setPage(0);}catch(error){setMessage(error instanceof Error?error.message:'Invalid JSON.');}finally{if(input.current)input.current.value='';}}}/></label></div>
 <p role="status">{message}</p><p>{matches.length} matching keys · {Object.keys(draft).length} overrides · page {current+1} of {pages}</p>
 <div className="labels-rows">{matches.slice(current*40,(current+1)*40).map(key=><fieldset key={key} className="label-row" disabled={pending}><legend><code>{key}</code></legend><p className="admin-muted">Default: {LABEL_DEFAULTS[key]}</p><label>Text for {key}<textarea rows={2} maxLength={2000} required value={draft[key]??LABEL_DEFAULTS[key]} onChange={event=>update(key,event.target.value)}/></label><button type="button" className="admin-button" disabled={!Object.hasOwn(draft,key)} onClick={()=>update(key,undefined)}>Reset to default</button></fieldset>)}</div>
 <div className="labels-toolbar"><button type="button" className="admin-button" disabled={current===0} onClick={()=>setPage(current-1)}>Previous labels</button><button type="button" className="admin-button" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>Next labels</button></div>
 </section>
 <section className="admin-card admin-confirm"><h2>Reset all overrides</h2><p>This only changes the draft until you publish.</p><label>Type RESET to reset the draft<input value={reset} onChange={event=>setReset(event.target.value)} autoComplete="off"/></label><button type="button" className="admin-button" disabled={reset!=='RESET'||pending} onClick={()=>{setDraft({});setReset('');setMessage('Default labels staged. Publish to apply.');}}>Reset all to defaults</button></section>
 <button type="submit" className="admin-button admin-primary" disabled={pending}>{pending?'Publishing…':'Publish labels'}</button>
 </form>;
}
