'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {mediaTypes} from '@/lib/media-type';
import type {MediaConfig} from '@/lib/media-config';
import type {mediaReport} from '@/lib/admin/media';
import {request} from '@/components/social/common';
const formatBytes=(bytes:number)=>new Intl.NumberFormat('en').format(bytes)+' bytes';
export function MediaEditor({initial}:{initial:MediaConfig}){
 const [value,setValue]=useState(initial),[pending,setPending]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 const numbers=[['maxFileMb','File limit (MB)',1,100],['dailyQuotaMb','Rolling 24-hour quota per account (MB)',1,10000],['maxMedia','Maximum photos per post',1,20],['imageQuality','Image quality',1,100],['imageMaxDimension','Maximum image dimension (pixels)',320,4096],['videoMaxSeconds','Maximum video seconds (0 = unlimited)',0,3600]] as const;
 return <details className="admin-card admin-drawer" open><summary>Upload controls</summary><form className="admin-confirm" onSubmit={async event=>{event.preventDefault();setPending(true);setMessage('');try{await request('/api/admin/media',{action:'settings',value});setMessage('Media settings published and audited. Reload public tabs to update hints.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not save.');}finally{setPending(false);}}}>
 <p>The Phase 5 Uploads flag and maintenance rules still apply. Limits use MiB (1,048,576 bytes). Active reservations hold quota for one hour; completed transfers count for 24 hours, even if quarantined or later deleted. Images are decoded, orientation-corrected and re-encoded on the server; the quality setting does not trust client preprocessing. GIF animation is preserved after bounded validation; oversized GIFs must be resized before upload. The older content-level reel cap also applies; the stricter nonzero cap wins.</p>
 <label className="feature-switch"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/>Enable uploads</label>
 <div className="media-settings-grid">{numbers.map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} step={1} required value={value[key]} onChange={e=>setValue({...value,[key]:Number(e.target.value)})}/></label>)}<label>Image output format<select value={value.imageFormat} onChange={e=>setValue({...value,imageFormat:e.target.value as MediaConfig['imageFormat']})}><option value="jpeg">JPEG</option><option value="png">PNG</option><option value="webp">WebP</option></select></label></div>
 <fieldset className="admin-confirm"><legend>Allowed types</legend>{mediaTypes.map(type=><label key={type} className="feature-switch"><input type="checkbox" checked={value.allowedTypes.includes(type)} onChange={e=>setValue({...value,allowedTypes:e.target.checked?[...value.allowedTypes,type]:value.allowedTypes.filter(t=>t!==type)})}/>{type}</label>)}</fieldset>
 {message&&<p role="status">{message}</p>}<button className="admin-button admin-primary" disabled={pending}>{pending?'Saving…':'Publish media settings'}</button></form></details>;
}
export function StorageInventory({report,owner}:{report:Awaited<ReturnType<typeof mediaReport>>;owner:boolean}){
 const [selected,setSelected]=useState(''),[action,setAction]=useState('quarantine'),[confirmation,setConfirmation]=useState(''),[reason,setReason]=useState(''),[pending,setPending]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 const url=(page:number)=>'/rstmcadmin/media?'+new URLSearchParams({...report.filter,page:String(page)}).toString();
 const manage=(key:string,next:string)=>{setSelected(key);setAction(next);setConfirmation('');setReason('');setMessage('');};
 return <section className="admin-card admin-confirm"><h2>Storage inventory</h2><p>Registered objects: {String(report.summary.assets)} · {formatBytes(Number(report.summary.bytes))} · retained originals: {formatBytes(Number(report.summary.retained_source_bytes))}. Quarantined: {String(report.summary.quarantined)} · Trash: {String(report.summary.trashed)}.</p><p>Active reservations: {String(report.pending.reservations)} · {formatBytes(Number(report.pending.reserved_bytes))} reserved, not confirmed storage. Totals include quarantine and trash. Bundled demo media and unrelated objects in a shared Blob store are excluded.</p>
 <form className="media-filters" action="/rstmcadmin/media"><label>Status<select name="status" defaultValue={report.filter.status}>{['all','ready','quarantined','trash','purging','orphans'].map(value=><option key={value}>{value}</option>)}</select></label><label>Order<select name="sort" defaultValue={report.filter.sort}><option value="newest">Newest</option><option value="largest">Biggest assets</option></select></label><label>Owner ID<input name="owner" defaultValue={report.filter.owner} maxLength={100}/></label><div className="admin-form-actions"><button className="admin-button admin-primary">Filter assets</button></div></form>
 <p>Orphans have no references from any posts (including hidden, expired and trashed posts), avatars, account images or branding settings. Trash is restorable for 30 days. Permanent deletion requires an owner and a typed asset key. Quarantine blocks the application media URL immediately; already-known public Blob URLs and downloaded bytes cannot be recalled.</p>
 <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Asset / owner</th><th>Stored size / type</th><th>State</th><th>Actions</th></tr></thead><tbody>{report.items.map(item=><tr key={item.key}><td><code>{item.key}</code><small>{item.storage_owner||item.owner_id||'Deleted account'}</small></td><td>{formatBytes(Number(item.size)+Number(item.source_retained_bytes))}<small>{item.mime}</small></td><td>{item.status}{item.referenced?' · referenced':' · unreferenced'}{item.reason&&<p>{item.reason}</p>}</td><td><div className="media-row-actions">{item.status==='ready'&&<button className="admin-button" onClick={()=>manage(item.key,'quarantine')}>Quarantine</button>}{item.status==='quarantined'&&item.verified&&<button className="admin-button" onClick={()=>manage(item.key,'release')}>Release</button>}{['ready','quarantined'].includes(item.status)&&!item.referenced&&<button className="admin-button" data-tone="danger" onClick={()=>manage(item.key,'trash')}>Trash unreferenced</button>}{item.status==='trash'&&<button className="admin-button" onClick={()=>manage(item.key,'restore')}>Restore</button>}{owner&&['trash','purging'].includes(item.status)&&<button className="admin-button" data-tone="danger" onClick={()=>manage(item.key,'purge')}>Permanently delete</button>}</div></td></tr>)}</tbody></table></div>
 {!report.items.length&&<p>No matching assets.</p>}<nav className="admin-pagination" aria-label="Media pages">{report.filter.page>1&&<Link className="admin-button" href={url(report.filter.page-1)}>Previous</Link>}<span>Page {report.filter.page} · {report.total} matching assets</span>{report.total>report.filter.page*50&&<Link className="admin-button" href={url(report.filter.page+1)}>Next</Link>}</nav>
 <h3>Storage by account (25 accounts per page)</h3><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Owner ID</th><th>Assets</th><th>Bytes</th></tr></thead><tbody>{report.owners.map(item=><tr key={item.owner_id||'unknown'}><td>{item.owner_id||'Unknown'}</td><td>{String(item.assets)}</td><td>{formatBytes(Number(item.bytes))}</td></tr>)}</tbody></table></div>
 <h3>Expired reservations (25 per page)</h3><p>Reconcile checks for an abandoned object from a known app reservation, then registers it in quarantine for safe cleanup. Missing objects are not reported as deleted. Unknown objects from other applications are never swept.</p>{report.expired.map(item=><div key={item.key} className="media-reservation"><code>{item.key}</code><span>{formatBytes(Number(item.expected_size))}</span><button className="admin-button" onClick={()=>manage(item.key,'reconcile')}>Reconcile reservation</button></div>)}{(report.owners.length===25||report.expired.length===25)&&<Link className="admin-button" href={url(report.filter.page+1)}>Next accounts / reservations</Link>}
 {selected&&<form className="admin-confirm media-confirm" onSubmit={async event=>{event.preventDefault();setPending(true);setMessage('');try{await request('/api/admin/media',{action,key:selected,confirmation,reason});setMessage('Media operation completed and audited.');setSelected('');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Could not change media.');}finally{setPending(false);}}}><h3>Confirm {action}</h3><p><code>{selected}</code></p><label>Reason<input maxLength={500} required={action==='quarantine'} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Type asset key<input autoComplete="off" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button className="admin-button admin-primary" disabled={pending||confirmation!==selected}>{pending?'Working…':'Confirm media operation'}</button><button type="button" className="admin-button" disabled={pending} onClick={()=>setSelected('')}>Cancel</button></form>}{message&&<p role="status">{message}</p>}
 </section>;
}
