'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {ModerationConfig} from '@/lib/moderation-policy';
import type {AdminRole} from '@/lib/admin/config';
type Report={id:string;reporter_id:string;reporter_username:string|null;target_type:string;target_id:string;reason:string;details:string;created_at:number;status:string;assigned_to:string|null;assignee_username:string|null;notes:string|null;action_taken:string|null;action_target_type:string|null;action_target_id:string|null;target_username:string|null;target_author_id:string|null;target_email:string|null};
type Queue={filter:{status:string;reason:string;target:string;q:string;page:number};total:number;items:Report[];counts:Record<string,number>};
type Rate={page:number;total:number;hits:number;items:{client:string;path:string;count:number;lastRequest:number;clientToken:string}[]};
type Account={shadow_banned:boolean;comment_banned:boolean;shadow_reason:string;comment_reason:string;updated_at?:number;updated_by?:string};
const reasons=['spam','harassment','false_information','misleading','inappropriate','other'];
async function api<T=Record<string,unknown>>(path:string,body?:unknown):Promise<T>{const response=await fetch(path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
const ago=(time:number)=>new Date(time).toLocaleString();
export function ModerationConsole({actorId,role,initialReports,initialConfig,initialRates}:{actorId:string;role:AdminRole;initialReports:Queue;initialConfig:ModerationConfig;initialRates:Rate}){
 const canManageSettings=role!=='moderator',canManageAccounts=role!=='moderator';
 const [reports,setReports]=useState(initialReports),[config,setConfig]=useState(initialConfig),[rates,setRates]=useState(initialRates),[view,setView]=useState('all'),[text,setText]=useState(''),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[accountId,setAccountId]=useState(''),[account,setAccount]=useState<Account|null>(null),[accountReason,setAccountReason]=useState(''),[accountConfirm,setAccountConfirm]=useState(''),[page,setPage]=useState(1);
 const mutate=async(work:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await work();setMessage('Saved and audited.');}catch(error){setMessage(error instanceof Error?error.message:'Request failed.');}finally{setBusy(false);}};
 const reloadReports=async(filters=reports.filter)=>{const q=new URLSearchParams(Object.entries(filters).map(([key,value])=>[key,String(value)]));setReports(await api('/api/admin/moderation?'+q));};
 const reloadRates=async(next=page)=>{const result=await api<Rate>('/api/admin/moderation?view=rateLimits&page='+next);setRates(result);setPage(next);};
 const loadAccount=async(id:string)=>{const result=await api<Account>('/api/admin/moderation?view=account&id='+encodeURIComponent(id));setAccount(result);setAccountReason(result.shadow_reason||result.comment_reason||'');};
 const saveNotes=(report:Report,notes:string)=>mutate(async()=>{await api('/api/admin/moderation',{action:'updateReport',operation:'notes',id:report.id,notes});await reloadReports();});
 const act=(report:Report,action:string,reason:string,confirmation:string)=>mutate(async()=>{await api('/api/admin/moderation',{op:'resolveReport',id:report.id,action,reason,confirmation,notes:report.notes||''});await reloadReports();});
 return <div className="moderation-console">
  <nav className="moderation-tabs" aria-label="Moderation tools">{[['all','Reports'],...(canManageSettings?[['filters','Word & domain filters']]:[]),...(canManageAccounts?[['accounts','Account safety'],['rates','Rate limits']]:[])].map(([key,label])=><button key={key} className="admin-button" aria-pressed={view===key} onClick={()=>setView(key)}>{label}</button>)}</nav>
  {message&&<p role="status">{message}</p>}
  {view==='all'&&<section className="admin-card admin-confirm"><h2>Reports inbox</h2><p>New {reports.counts.new||0} · Triage {reports.counts.triage||0} · Actioned {reports.counts.actioned||0} · Dismissed {reports.counts.dismissed||0} · {reports.total} matching this page&apos;s filters.</p>
   <form className="moderation-filters" onSubmit={event=>{event.preventDefault();void reloadReports({...reports.filter,page:1});}}><label>Status<select value={reports.filter.status} onChange={e=>setReports({...reports,filter:{...reports.filter,status:e.target.value}})}>{['new','triage','actioned','dismissed','all'].map(x=><option key={x}>{x}</option>)}</select></label><label>Reason<select value={reports.filter.reason} onChange={e=>setReports({...reports,filter:{...reports.filter,reason:e.target.value}})}><option value="">All reasons</option>{reasons.map(x=><option key={x}>{x}</option>)}</select></label><label>Target<select value={reports.filter.target} onChange={e=>setReports({...reports,filter:{...reports.filter,target:e.target.value}})}><option value="all">All targets</option><option value="post">Posts</option><option value="profile">Profiles</option></select></label><label>Search ID or username<input value={reports.filter.q} maxLength={100} onChange={e=>setReports({...reports,filter:{...reports.filter,q:e.target.value}})}/></label><button className="admin-button admin-primary">Apply filters</button></form>
   {!reports.items.length&&<p>No reports match the current filters.</p>}
   <div className="moderation-report-list">{reports.items.map(report=><ReportCard key={report.id} report={report} busy={busy} actorId={actorId} role={role} onAssign={()=>void mutate(async()=>{await api('/api/admin/moderation',{action:'updateReport',operation:'assign',id:report.id});await reloadReports();})} onSaveNotes={notes=>saveNotes(report,notes)} onAction={(action,reason,confirmation)=>act(report,action,reason,confirmation||report.id)} onLoadAccount={id=>{setAccountId(id);setView('accounts');}}/>)}</div>
   <div className="admin-pagination"><button className="admin-button" disabled={reports.filter.page<=1} onClick={()=>void reloadReports({...reports.filter,page:reports.filter.page-1})}>Previous</button><span>Page {reports.filter.page} · up to 50 reports</span><button className="admin-button" disabled={reports.items.length<50} onClick={()=>void reloadReports({...reports.filter,page:reports.filter.page+1})}>Next</button></div>
  </section>}
  {view==='filters'&&canManageSettings&&<section className="admin-card admin-confirm"><h2>Word &amp; domain filters</h2><p>Rules are checked on the server for new captions, edited captions, comments and messages. Existing posts remain unchanged. Plain words match whole tokens; domains match exact hosts and their subdomains. Regexes are deliberately restricted to a safe subset.</p>
   <label className="feature-switch"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/>Enable content filters</label><label className="feature-switch"><input type="checkbox" checked={config.regexMode} onChange={e=>setConfig({...config,regexMode:e.target.checked})}/>Treat blocked words as safe-subset regular expressions</label><label>Blocked words / patterns (one per line)<textarea rows={8} maxLength={6049} value={config.blockedWords.join('\n')} onChange={e=>setConfig({...config,blockedWords:e.target.value.split('\n').filter(Boolean)})}/></label><label>Blocked domains (one hostname per line)<textarea rows={6} maxLength={12699} value={config.blockedDomains.join('\n')} onChange={e=>setConfig({...config,blockedDomains:e.target.value.split('\n').filter(Boolean)})}/></label>
   <label>Preview sample<textarea rows={3} maxLength={2200} value={text} onChange={e=>setText(e.target.value)}/></label><div className="media-row-actions"><button className="admin-button" disabled={busy} onClick={()=>void mutate(async()=>{const result=await api('/api/admin/moderation',{action:'preview',config,text});setPreview(result.blocked?'Blocked by the current draft rules.':'Allowed by the current draft rules.');})}>Preview draft</button><button className="admin-button admin-primary" disabled={busy} onClick={()=>void mutate(async()=>{const next={...config,blockedWords:config.blockedWords.map(x=>x.trim()).filter(Boolean),blockedDomains:config.blockedDomains.map(x=>x.trim()).filter(Boolean)};await api('/api/admin/moderation',{action:'settings',value:next});setConfig(next);})}>Publish filters</button></div>{preview&&<p role="status">{preview}</p>}</section>}
  {view==='accounts'&&canManageAccounts&&<section className="admin-card admin-confirm"><h2>Account-specific safety controls</h2><p>Enter the account/profile ID from a report. Shadow-banned accounts can see their own posts; other viewers will not receive those posts. Comment bans block new comments at the API. Neither flag is exposed to the affected user&apos;s client or changes sign-in status.</p><form className="moderation-filters" onSubmit={event=>{event.preventDefault();void mutate(async()=>{await loadAccount(accountId);});}}><label>Profile ID<input required maxLength={100} value={accountId} onChange={e=>{setAccountId(e.target.value);setAccount(null);setAccountConfirm('');setAccountReason('');}}/></label><button className="admin-button">Load account controls</button></form>{account&&<form className="admin-confirm" onSubmit={event=>{event.preventDefault();if(accountConfirm!==accountId){setMessage('Type the exact profile ID to confirm.');return;}void mutate(async()=>{await api('/api/admin/moderation',{action:'accountModeration',profileId:accountId,shadowBanned:account.shadow_banned,commentBanned:account.comment_banned,reason:accountReason});await loadAccount(accountId);setAccountConfirm('');});}}><p>Shadow ban: {String(account.shadow_banned)} · Comment ban: {String(account.comment_banned)}</p><label className="feature-switch"><input type="checkbox" checked={account.shadow_banned} onChange={e=>setAccount({...account,shadow_banned:e.target.checked})}/>Shadow-ban this account</label><label className="feature-switch"><input type="checkbox" checked={account.comment_banned} onChange={e=>setAccount({...account,comment_banned:e.target.checked})}/>Ban new comments</label><label>Reason (required when either is active)<textarea required={account.shadow_banned||account.comment_banned} maxLength={500} value={accountReason} onChange={e=>setAccountReason(e.target.value)}/></label><label>Type exact profile ID<input required maxLength={100} value={accountConfirm} onChange={e=>setAccountConfirm(e.target.value)}/></label><button className="admin-button admin-primary" disabled={busy||accountConfirm!==accountId}>Save restrictions</button></form>}</section>}
  {view==='rates'&&canManageAccounts&&<section className="admin-card admin-confirm"><h2>Rate-limit inspector</h2><p>Recent Better Auth buckets are keyed by client IP + endpoint. Addresses are encrypted in a short-lived admin action token and never displayed or returned in plaintext. Each entry shows an irreversible client hash and endpoint path only.</p><p>{rates.total} recent buckets · {rates.hits} recorded hits across the last 24 hours.</p><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Client hash</th><th>Endpoint</th><th>Hits</th><th>Last request</th><th>Action</th></tr></thead><tbody>{rates.items.map(item=><tr key={item.client+'|'+item.path}><td><code>{item.client}</code></td><td><code>{item.path}</code></td><td>{item.count}</td><td>{ago(item.lastRequest)}</td><td><button className="admin-button" disabled={busy} onClick={()=>{const confirmation=window.prompt('Type client hash '+item.client+' to clear this client’s rate-limit buckets.');if(confirmation!==item.client)return;void mutate(async()=>{await api('/api/admin/moderation',{action:'clearRateLimit',clientToken:item.clientToken});await reloadRates();});}}>Unblock client</button></td></tr>)}</tbody></table></div>{!rates.items.length&&<p>No rate-limit buckets were recorded in the last 24 hours.</p>}<div className="admin-pagination"><button className="admin-button" disabled={rates.page<=1} onClick={()=>void reloadRates(rates.page-1)}>Previous</button><span>Page {rates.page} · max 50</span><button className="admin-button" disabled={rates.items.length<50} onClick={()=>void reloadRates(rates.page+1)}>Next</button></div></section>}
 </div>;
}
function ReportCard({report,busy,actorId,role,onAssign,onSaveNotes,onAction,onLoadAccount}:{report:Report;busy:boolean;actorId:string;role:AdminRole;onAssign:()=>void;onSaveNotes:(notes:string)=>void;onAction:(action:string,reason:string,confirmation?:string)=>void;onLoadAccount:(id:string)=>void}){
 const [notes,setNotes]=useState(report.notes||''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(''),[banConfirm,setBanConfirm]=useState('');const target=report.target_type==='post'?report.target_author_id||report.target_id:report.target_id;const resolved=['actioned','dismissed'].includes(report.status);
 return <article className="moderation-report"><header><div><strong>{report.reason.replaceAll('_',' ')}</strong> · {report.status} · {report.target_type}<p>From {report.reporter_username||'deleted profile'} ({report.reporter_id}) · {ago(report.created_at)}</p></div><code>{report.id}</code></header><p>{report.details||'No additional report details.'}</p><p>Target: <code>{report.target_id}</code>{report.target_username&&' · @'+report.target_username}{report.target_email&&' · '+report.target_email}</p><div className="media-row-actions">{report.target_type==='post'?<Link className="admin-button" href={'/rstmcadmin/content/'+encodeURIComponent(report.target_id)}>Open post</Link>:<Link className="admin-button" href={'/rstmcadmin/users/'+encodeURIComponent(report.target_id)}>Open account</Link>}<button className="admin-button" disabled={resolved||busy} onClick={onAssign}>{report.assigned_to===actorId?'Assigned to you':report.assignee_username?'Assigned to @'+report.assignee_username:'Assign to me'}</button>{role!=='moderator'&&<button className="admin-button" disabled={resolved||busy} onClick={()=>onLoadAccount(target)}>Account safety</button>}</div>{report.action_taken&&<p>Action: {report.action_taken} · <Link href={report.action_target_type==='post'?'/rstmcadmin/content/'+encodeURIComponent(report.action_target_id||''):'/rstmcadmin/users/'+encodeURIComponent(report.action_target_id||'')}>{report.action_target_type} {report.action_target_id}</Link></p>}
 <label>Moderator notes<textarea rows={3} maxLength={2000} value={notes} disabled={resolved} onChange={e=>setNotes(e.target.value)}/></label><button className="admin-button" disabled={resolved||busy} onClick={()=>onSaveNotes(notes)}>Save notes</button>
 {!resolved&&<><label>Action reason (required)<input maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Type report ID to hide or dismiss<input maxLength={100} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{role!=='moderator'&&<label>Type reported account email to ban<code>{report.target_email||'No linked account email'}</code><input type="email" maxLength={254} value={banConfirm} onChange={e=>setBanConfirm(e.target.value)}/></label>}<div className="media-row-actions">{report.target_type==='post'&&<button className="admin-button" disabled={busy||!reason.trim()||confirm!==report.id} onClick={()=>onAction('hide',reason,report.id)}>Hide reported post &amp; resolve</button>}{role!=='moderator'&&<button className="admin-button" disabled={busy||!reason.trim()||!report.target_email||banConfirm!==report.target_email} onClick={()=>onAction('ban',reason,banConfirm)}>Ban reported account &amp; resolve</button>}<button className="admin-button" disabled={busy||confirm!==report.id} onClick={()=>onAction('dismiss',reason,report.id)}>Dismiss report</button></div></>}
 </article>;
}
