'use client';
import { useState } from 'react';
import type { systemOverview } from '@/lib/admin/system';

type Overview = Awaited<ReturnType<typeof systemOverview>>;
type SqlResult = { queryHash: string; columns: string[]; rows: Record<string, unknown>[]; rowLimit: number; truncated: boolean };
const booleanLabel = (value: boolean) => value ? 'Configured' : 'Not configured';
async function readResponse<T>(response: Response): Promise<T> {
  const body = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(body.error || 'System operation failed.');
  return body;
}
export function SystemTools({ initial, canOwnerTools, canPrune }: { initial: Overview; canOwnerTools: boolean; canPrune: boolean }) {
  const [overview,setOverview]=useState(initial),[confirmation,setConfirmation]=useState(''),[reason,setReason]=useState(''),[query,setQuery]=useState('SELECT id,kind,created_at FROM posts ORDER BY created_at DESC LIMIT 20'),[sqlReason,setSqlReason]=useState(''),[result,setResult]=useState<SqlResult|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[section,setSection]=useState('status');
  const refresh=async()=>{setBusy(true);setError('');try{setOverview(await readResponse<Overview>(await fetch('/api/admin/system',{cache:'no-store'})));setMessage('System status refreshed.');}catch(cause){setError(cause instanceof Error?cause.message:'Could not refresh status.');}finally{setBusy(false);}};
  const run=async(action:string)=>{setBusy(true);setError('');setMessage('');try{const payload=await readResponse<Record<string,unknown>>(await fetch('/api/admin/system',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({action,confirmation,reason})}));setMessage(`Operation completed: ${JSON.stringify(payload)}.`);setConfirmation('');setOverview(await readResponse<Overview>(await fetch('/api/admin/system',{cache:'no-store'})));}catch(cause){setError(cause instanceof Error?cause.message:'System operation failed.');}finally{setBusy(false);}};
  const runSql=async()=>{setBusy(true);setError('');setMessage('');setResult(null);try{const payload=await readResponse<SqlResult>(await fetch('/api/admin/system',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({action:'readOnlySql',query,reason:sqlReason})}));setResult(payload);setMessage(`Read-only query returned ${payload.rows.length} rows${payload.truncated?' (capped at 500)':''}. Query hash: ${payload.queryHash}.`);}catch(cause){setError(cause instanceof Error?cause.message:'Query failed.');}finally{setBusy(false);}};
  const env=Object.entries(overview.environment) as [string,boolean][];
  const storyBatch=Math.min(overview.expiredStories,100),orphanBatch=Math.min(overview.orphanAssets,100);
  return <div className="system-tools">
    <div className="admin-tabs" role="tablist" aria-label="System sections">{[['status','Status'],['cache','Cache'],['data','Data tools'],['sql','SQL']].map(([id,label])=><button key={id} type="button" role="tab" aria-selected={section===id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</div>
    {section==='status'&&<><section className="admin-card"><div className="admin-card-heading"><div><h2>Migration status</h2><p>Applied database migrations compared with the registered application sequence. This screen never runs migrations.</p></div><button className="admin-button" type="button" disabled={busy} onClick={()=>void refresh()}>Refresh status</button></div><p>{overview.migrationCount} applied · latest registered version {overview.latestRegisteredMigration} · {overview.missingMigrations.length?`missing ${overview.missingMigrations.join(', ')}`:'up to date'}</p><div className="migration-chips">{overview.migrations.map(item=><span className={item.applied?'is-applied':'is-pending'} key={item.version}>v{item.version} {item.applied?'applied':'pending'}</span>)}</div></section>
    <section className="admin-card"><h2>Environment inspector</h2><p>Only whether each setting is present is exposed. Values, addresses, and secret names are never returned.</p><dl className="system-env-list">{env.map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1')}</dt><dd>{booleanLabel(value)}</dd></div>)}</dl></section></>}
    {section==='cache'&&<section className="admin-card"><h2>Cache invalidation</h2><p>Purges the settings cache and revalidates the public root layout. It does not clear browser/CDN caches or database data.</p><label>Audit reason<input maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Type PURGE SITE CACHE<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button className="admin-button" disabled={busy||confirmation!=='PURGE SITE CACHE'||reason.trim().length<8} onClick={()=>void run('purgeCache')}>Purge settings and public cache</button></section>}
    {section==='data'&&<><section className="admin-card"><h2>Demo-data controls</h2><p>Seeded demo profiles are separate from real accounts. Re-seeding inserts missing fixture rows without replacing edits; wiping permanently removes demo profiles and their cascaded demo content, then disables automatic re-seeding.</p><p>{overview.demoProfiles} demo profiles · {overview.demoPosts} posts · automatic seed {overview.demoSeedEnabled?'enabled':'disabled'}</p>{canOwnerTools?<><label>Reason<input maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Confirmation<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)} placeholder={overview.demoProfiles?`WIPE ${overview.demoProfiles} DEMO PROFILES or RESEED DEMO DATA`:'RESEED DEMO DATA'}/></label><div className="admin-button-row"><button className="admin-button" disabled={busy||confirmation!=='RESEED DEMO DATA'||reason.trim().length<8} onClick={()=>void run('reseedDemoData')}>Re-seed demo fixtures</button><button className="admin-button admin-danger" disabled={busy||confirmation!==`WIPE ${overview.demoProfiles} DEMO PROFILES`||reason.trim().length<8} onClick={()=>void run('wipeDemoData')}>Wipe demo data</button></div></>:<p>Owner-only tools.</p>}</section>
    <section className="admin-card"><h2>Retention and orphan pruning</h2><p>Expired stories are permanently removed only after 30 days past expiry. Orphan assets are only staged into the existing Trash workflow after seven days; no Blob object is physically deleted. Each batch is capped at 100 and audited.</p><p>{overview.expiredStories} expired stories eligible · {overview.orphanAssets} old orphan assets eligible.</p>{canPrune?<><label>Reason<input maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Confirmation<input autoComplete="off" value={confirmation} onChange={event=>setConfirmation(event.target.value)} placeholder={`PRUNE ${storyBatch} EXPIRED STORIES or MOVE ${orphanBatch} ORPHAN ASSETS TO TRASH`}/></label><div className="admin-button-row"><button className="admin-button admin-danger" disabled={busy||!storyBatch||confirmation!==`PRUNE ${storyBatch} EXPIRED STORIES`||reason.trim().length<8} onClick={()=>void run('pruneExpiredStories')}>Prune expired stories</button><button className="admin-button" disabled={busy||!orphanBatch||confirmation!==`MOVE ${orphanBatch} ORPHAN ASSETS TO TRASH`||reason.trim().length<8} onClick={()=>void run('pruneOrphanAssets')}>Move orphan assets to Trash</button></div></>:<p>Owner-only tools.</p>}</section></>}
    {section==='sql'&&canOwnerTools&&<section className="admin-card system-sql"><h2>Read-only SQL runner · owner only</h2><p>Exactly one SELECT; approved application tables only, no auth/session/account/settings tables, joins only, 500-row cap, five-second database timeout. The query is logged by SHA-256 hash and is never stored in the audit record. A read-only transaction is enforced by PostgreSQL.</p><label>SELECT query<textarea rows={7} maxLength={4000} spellCheck={false} value={query} onChange={event=>setQuery(event.target.value)}/></label><label>Reason for running this query<input maxLength={500} value={sqlReason} onChange={event=>setSqlReason(event.target.value)}/></label><button className="admin-button admin-primary" type="button" disabled={busy||!query.trim()||sqlReason.trim().length<10} onClick={()=>void runSql()}>{busy?'Running…':'Run SELECT'}</button>{result&&<><p>{result.rows.length} rows · {result.columns.length} columns · hash {result.queryHash}</p><pre className="system-sql-result">{JSON.stringify(result.rows,null,2)}</pre></>}</section>}
    {section==='sql'&&!canOwnerTools&&<section className="admin-card"><h2>Read-only SQL</h2><p>Owner-only. This account can read system status, not run SQL.</p></section>}
    {(message||error)&&<p role={error?'alert':'status'} className={error?'admin-error':''}>{error||message}</p>}
  </div>;
}
