import Link from 'next/link';
import { requireAdminPage, assertAdminPagePermission } from '@/lib/admin/guard';
import { ADMIN_BASE_PATH } from '@/lib/admin/config';

export default async function AdminGuidePage() {
  const actor = await requireAdminPage();
  assertAdminPagePermission(actor, 'system.read');
  return <>
    <p className="admin-eyebrow">Control room / Operator guide</p><h1>Operations guide</h1>
    <section className="admin-card admin-guide"><h2>Analytics and exports</h2><p>Analytics uses UTC day buckets. “Active sign-in proxy” counts distinct accounts whose Better Auth session was refreshed that day; it is not a per-request DAU event. Uploaded storage is the sum of asset bytes added during the chosen window, not a historical snapshot of retained storage. The signup funnel counts non-demo member accounts with at least one non-deleted post; stories and reels are not counted as first posts.</p><p>Exports are streamed and capped at 1,000 records. User exports contain email addresses, report exports can include moderation details, and audit exports include recorded network/client metadata. Save and share these files only with a justified operational need.</p>
      <p><Link href={ADMIN_BASE_PATH+'/analytics'}>Open analytics</Link> · <Link href={ADMIN_BASE_PATH+'/exports'}>Open exports</Link></p></section>
    <section className="admin-card admin-guide"><h2>Migration status and cache</h2><p>The system page compares applied migration versions with the application registry; it does not apply migrations. Run migrations through the normal deployment process. Cache invalidation clears the tagged settings cache and revalidates the public root layout; it cannot clear a browser cache or a third-party CDN.</p><p>Environment inspection reports booleans only. Keep credentials in deployment environment settings, never in the database-backed site settings.</p></section>
    <section className="admin-card admin-guide"><h2>SQL runner safety</h2><p>Owner-only. It accepts one SELECT over the documented application tables, blocks authentication/session/account and settings tables, denies comments, CTEs, subqueries, locks, writes and non-allowlisted functions, runs in a PostgreSQL read-only transaction, stops after five seconds, and returns at most 500 rows. Each accepted query is audited by hash; SQL text is not retained in the audit log. The runner is not a replacement for a controlled database console.</p><p>Use explicit columns, short time windows, and a LIMIT. Avoid exporting message bodies or personal information unless the task requires it.</p></section>
    <section className="admin-card admin-guide"><h2>Demo-data tools</h2><p>Re-seed inserts missing bundled demo fixtures and does not overwrite existing fixture IDs. Wipe permanently removes profiles marked as demo and their dependent demo rows, and disables automatic re-seeding until an owner explicitly re-seeds. Profiles linked to an authentication account are deliberately excluded from the wipe, even if mistakenly marked as demo; real accounts and uploaded assets are not selected by the demo flag.</p></section>
    <section className="admin-card admin-guide"><h2>Retention tools</h2><p>Expired stories are eligible for permanent pruning only after 30 days past expiry, and are deleted in batches of at most 100; dependent story comments, reactions and highlights cascade. Orphan assets require seven days without an application reference and are moved to the existing Trash state, not physically deleted. The normal Media restore window and owner-only purge protection remain in force.</p><p>Before applying a destructive action, preview the count, enter the exact confirmation, and record a clear reason. Every accepted power-tool operation creates an append-only audit event.</p></section>
    <p className="admin-muted">Keep a verified owner recovery path available. For lockout recovery, use the separately reviewed operator procedure and an authorized database console; never expose SQL write access inside this panel.</p>
  </>;
}
